# Code generated by smithy-python-codegen DO NOT EDIT.

from types import MappingProxyType

from smithy_core.prelude import UNIT
from smithy_core.schemas import Schema
from smithy_core.shapes import ShapeID, ShapeType
from smithy_core.traits import Trait


STRING = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#String"), shape_type=ShapeType.STRING
)

ACCESS_DENIED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#AccessDeniedException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=403),
    ],
    members={
        "message": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

PARAMETER_NAME = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#ParameterName"), shape_type=ShapeType.STRING
)

TEXT = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#Text"),
    shape_type=ShapeType.STRING,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
)

ACTIVE_CONTEXT_PARAMETERS_MAP = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#ActiveContextParametersMap"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": PARAMETER_NAME}, "value": {"target": TEXT}},
)

ACTIVE_CONTEXT_NAME = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#ActiveContextName"),
    shape_type=ShapeType.STRING,
)

ACTIVE_CONTEXT_TIME_TO_LIVE_IN_SECONDS = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#ActiveContextTimeToLiveInSeconds"),
    shape_type=ShapeType.INTEGER,
)

ACTIVE_CONTEXT_TURNS_TO_LIVE = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#ActiveContextTurnsToLive"),
    shape_type=ShapeType.INTEGER,
)

ACTIVE_CONTEXT_TIME_TO_LIVE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#ActiveContextTimeToLive"),
    members={
        "timeToLiveInSeconds": {
            "target": ACTIVE_CONTEXT_TIME_TO_LIVE_IN_SECONDS,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "turnsToLive": {
            "target": ACTIVE_CONTEXT_TURNS_TO_LIVE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

ACTIVE_CONTEXT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#ActiveContext"),
    members={
        "name": {
            "target": ACTIVE_CONTEXT_NAME,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "timeToLive": {
            "target": ACTIVE_CONTEXT_TIME_TO_LIVE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "contextAttributes": {
            "target": ACTIVE_CONTEXT_PARAMETERS_MAP,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

ACTIVE_CONTEXTS_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#ActiveContextsList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": ACTIVE_CONTEXT}},
)

ATTACHMENT_TITLE = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#AttachmentTitle"),
    shape_type=ShapeType.STRING,
)

ATTACHMENT_URL = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#AttachmentUrl"), shape_type=ShapeType.STRING
)

AUDIO_CHUNK = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#AudioChunk"), shape_type=ShapeType.BLOB
)

EPOCH_MILLIS = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#EpochMillis"),
    shape_type=ShapeType.LONG,
    traits=[Trait.new(id=ShapeID("smithy.api#default"), value=0)],
)

NON_EMPTY_STRING = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#NonEmptyString"), shape_type=ShapeType.STRING
)

EVENT_ID = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#EventId"), shape_type=ShapeType.STRING
)

AUDIO_INPUT_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#AudioInputEvent"),
    members={
        "audioChunk": {"target": AUDIO_CHUNK},
        "contentType": {
            "target": NON_EMPTY_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "eventId": {"target": EVENT_ID},
        "clientTimestampMillis": {
            "target": EPOCH_MILLIS,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=0)],
        },
    },
)

AUDIO_RESPONSE_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#AudioResponseEvent"),
    members={
        "audioChunk": {"target": AUDIO_CHUNK},
        "contentType": {"target": NON_EMPTY_STRING},
        "eventId": {"target": EVENT_ID},
    },
)

CONFLICT_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#ConflictException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=409),
    ],
    members={
        "message": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

BOT_ALIAS_IDENTIFIER = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#BotAliasIdentifier"),
    shape_type=ShapeType.STRING,
)

BOT_IDENTIFIER = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#BotIdentifier"), shape_type=ShapeType.STRING
)

LOCALE_ID = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#LocaleId"), shape_type=ShapeType.STRING
)

SESSION_ID = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#SessionId"), shape_type=ShapeType.STRING
)

DELETE_SESSION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#DeleteSessionInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.lexruntimev2#DeleteSessionRequest",
        )
    ],
    members={
        "botId": {
            "target": BOT_IDENTIFIER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "botAliasId": {
            "target": BOT_ALIAS_IDENTIFIER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "localeId": {
            "target": LOCALE_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "sessionId": {
            "target": SESSION_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
    },
)

DELETE_SESSION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#DeleteSessionOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.lexruntimev2#DeleteSessionResponse",
        )
    ],
    members={
        "botId": {"target": BOT_IDENTIFIER},
        "botAliasId": {"target": BOT_ALIAS_IDENTIFIER},
        "localeId": {"target": LOCALE_ID},
        "sessionId": {"target": SESSION_ID},
    },
)

INTERNAL_SERVER_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#InternalServerException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="server"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=500),
    ],
    members={
        "message": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

RESOURCE_NOT_FOUND_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#ResourceNotFoundException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=404),
    ],
    members={
        "message": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

THROTTLING_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#ThrottlingException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=429),
    ],
    members={
        "message": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

VALIDATION_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#ValidationException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
    ],
    members={
        "message": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

DELETE_SESSION = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#DeleteSession"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {
                    "method": "DELETE",
                    "uri": "/bots/{botId}/botAliases/{botAliasId}/botLocales/{localeId}/sessions/{sessionId}",
                    "code": 200,
                }
            ),
        )
    ],
)

GET_SESSION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#GetSessionInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.lexruntimev2#GetSessionRequest",
        )
    ],
    members={
        "botId": {
            "target": BOT_IDENTIFIER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "botAliasId": {
            "target": BOT_ALIAS_IDENTIFIER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "localeId": {
            "target": LOCALE_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "sessionId": {
            "target": SESSION_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
    },
)

CONFIRMATION_STATE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#ConfirmationState"),
    shape_type=ShapeType.ENUM,
    members={
        "CONFIRMED": {"target": UNIT},
        "DENIED": {"target": UNIT},
        "NONE": {"target": UNIT},
    },
)

SHAPE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#Shape"),
    shape_type=ShapeType.ENUM,
    members={
        "SCALAR": {"target": UNIT},
        "LIST": {"target": UNIT},
        "COMPOSITE": {"target": UNIT},
    },
)

STRING_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#StringList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": NON_EMPTY_STRING}},
)

VALUE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#Value"),
    members={
        "originalValue": {"target": NON_EMPTY_STRING},
        "interpretedValue": {
            "target": NON_EMPTY_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "resolvedValues": {"target": STRING_LIST},
    },
)

INTENT_STATE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#IntentState"),
    shape_type=ShapeType.ENUM,
    members={
        "FAILED": {"target": UNIT},
        "FULFILLED": {"target": UNIT},
        "IN_PROGRESS": {"target": UNIT},
        "READY_FOR_FULFILLMENT": {"target": UNIT},
        "WAITING": {"target": UNIT},
        "FULFILLMENT_IN_PROGRESS": {"target": UNIT},
    },
)

INTERPRETATION_SOURCE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#InterpretationSource"),
    shape_type=ShapeType.ENUM,
    members={"BEDROCK": {"target": UNIT}, "LEX": {"target": UNIT}},
)

DOUBLE = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#Double"),
    shape_type=ShapeType.DOUBLE,
    traits=[Trait.new(id=ShapeID("smithy.api#default"), value=0)],
)

CONFIDENCE_SCORE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#ConfidenceScore"),
    members={
        "score": {
            "target": DOUBLE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=0)],
        }
    },
)

SENTIMENT_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#SentimentType"),
    shape_type=ShapeType.ENUM,
    members={
        "MIXED": {"target": UNIT},
        "NEGATIVE": {"target": UNIT},
        "NEUTRAL": {"target": UNIT},
        "POSITIVE": {"target": UNIT},
    },
)

SENTIMENT_SCORE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#SentimentScore"),
    members={
        "positive": {
            "target": DOUBLE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=0)],
        },
        "negative": {
            "target": DOUBLE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=0)],
        },
        "neutral": {
            "target": DOUBLE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=0)],
        },
        "mixed": {
            "target": DOUBLE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=0)],
        },
    },
)

SENTIMENT_RESPONSE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#SentimentResponse"),
    members={
        "sentiment": {"target": SENTIMENT_TYPE},
        "sentimentScore": {"target": SENTIMENT_SCORE},
    },
)

MESSAGE_CONTENT_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#MessageContentType"),
    shape_type=ShapeType.ENUM,
    members={
        "CUSTOM_PAYLOAD": {"target": UNIT},
        "IMAGE_RESPONSE_CARD": {"target": UNIT},
        "PLAIN_TEXT": {"target": UNIT},
        "SSML": {"target": UNIT},
    },
)

BUTTON_TEXT = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#ButtonText"), shape_type=ShapeType.STRING
)

BUTTON_VALUE = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#ButtonValue"), shape_type=ShapeType.STRING
)

BUTTON = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#Button"),
    members={
        "text": {
            "target": BUTTON_TEXT,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "value": {
            "target": BUTTON_VALUE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

BUTTONS_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#ButtonsList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": BUTTON}},
)

IMAGE_RESPONSE_CARD = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#ImageResponseCard"),
    members={
        "title": {
            "target": ATTACHMENT_TITLE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "subtitle": {"target": ATTACHMENT_TITLE},
        "imageUrl": {"target": ATTACHMENT_URL},
        "buttons": {"target": BUTTONS_LIST},
    },
)

MESSAGE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#Message"),
    members={
        "content": {"target": TEXT},
        "contentType": {
            "target": MESSAGE_CONTENT_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "imageResponseCard": {"target": IMAGE_RESPONSE_CARD},
    },
)

MESSAGES = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#Messages"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": MESSAGE}},
)

STYLE_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#StyleType"),
    shape_type=ShapeType.ENUM,
    members={
        "DEFAULT": {"target": UNIT},
        "SPELL_BY_LETTER": {"target": UNIT},
        "SPELL_BY_WORD": {"target": UNIT},
    },
)

DIALOG_ACTION_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#DialogActionType"),
    shape_type=ShapeType.ENUM,
    members={
        "CLOSE": {"target": UNIT},
        "CONFIRM_INTENT": {"target": UNIT},
        "DELEGATE": {"target": UNIT},
        "ELICIT_INTENT": {"target": UNIT},
        "ELICIT_SLOT": {"target": UNIT},
        "NONE": {"target": UNIT},
    },
)

NAME = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#Name"), shape_type=ShapeType.STRING
)

RUNTIME_HINT_PHRASE = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#RuntimeHintPhrase"),
    shape_type=ShapeType.STRING,
)

RUNTIME_HINT_VALUE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#RuntimeHintValue"),
    members={
        "phrase": {
            "target": RUNTIME_HINT_PHRASE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

RUNTIME_HINT_VALUES_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#RuntimeHintValuesList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": RUNTIME_HINT_VALUE}},
)

STRING_MAP = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#StringMap"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": NON_EMPTY_STRING}, "value": {"target": STRING}},
)

BAD_GATEWAY_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#BadGatewayException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="server"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=502),
    ],
    members={
        "message": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

DEPENDENCY_FAILED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#DependencyFailedException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=424),
    ],
    members={
        "message": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

BLOB_STREAM = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#BlobStream"),
    shape_type=ShapeType.BLOB,
    traits=[Trait.new(id=ShapeID("smithy.api#streaming"))],
)

PUT_SESSION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#PutSessionOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.lexruntimev2#PutSessionResponse",
        )
    ],
    members={
        "contentType": {
            "target": NON_EMPTY_STRING,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#httpHeader"), value="Content-Type")
            ],
        },
        "messages": {
            "target": NON_EMPTY_STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"), value="x-amz-lex-messages"
                )
            ],
        },
        "sessionState": {
            "target": NON_EMPTY_STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"), value="x-amz-lex-session-state"
                )
            ],
        },
        "requestAttributes": {
            "target": NON_EMPTY_STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amz-lex-request-attributes",
                )
            ],
        },
        "sessionId": {
            "target": SESSION_ID,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"), value="x-amz-lex-session-id"
                )
            ],
        },
        "audioStream": {
            "target": BLOB_STREAM,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#default"), value=""),
                Trait.new(id=ShapeID("smithy.api#httpPayload")),
            ],
        },
    },
)

RECOGNIZED_BOT_MEMBER = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#RecognizedBotMember"),
    members={
        "botId": {
            "target": BOT_IDENTIFIER,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "botName": {"target": NAME},
    },
)

SENSITIVE_NON_EMPTY_STRING = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#SensitiveNonEmptyString"),
    shape_type=ShapeType.STRING,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
)

RECOGNIZE_UTTERANCE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#RecognizeUtteranceInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.lexruntimev2#RecognizeUtteranceRequest",
        )
    ],
    members={
        "botId": {
            "target": BOT_IDENTIFIER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "botAliasId": {
            "target": BOT_ALIAS_IDENTIFIER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "localeId": {
            "target": LOCALE_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "sessionId": {
            "target": SESSION_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "sessionState": {
            "target": SENSITIVE_NON_EMPTY_STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"), value="x-amz-lex-session-state"
                )
            ],
        },
        "requestAttributes": {
            "target": SENSITIVE_NON_EMPTY_STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amz-lex-request-attributes",
                )
            ],
        },
        "requestContentType": {
            "target": NON_EMPTY_STRING,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#httpHeader"), value="Content-Type"),
                Trait.new(id=ShapeID("smithy.api#required")),
            ],
        },
        "responseContentType": {
            "target": NON_EMPTY_STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"), value="Response-Content-Type"
                )
            ],
        },
        "inputStream": {
            "target": BLOB_STREAM,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#default"), value=""),
                Trait.new(id=ShapeID("smithy.api#httpPayload")),
            ],
        },
    },
)

RECOGNIZE_UTTERANCE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#RecognizeUtteranceOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.lexruntimev2#RecognizeUtteranceResponse",
        )
    ],
    members={
        "inputMode": {
            "target": NON_EMPTY_STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"), value="x-amz-lex-input-mode"
                )
            ],
        },
        "contentType": {
            "target": NON_EMPTY_STRING,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#httpHeader"), value="Content-Type")
            ],
        },
        "messages": {
            "target": NON_EMPTY_STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"), value="x-amz-lex-messages"
                )
            ],
        },
        "interpretations": {
            "target": NON_EMPTY_STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amz-lex-interpretations",
                )
            ],
        },
        "sessionState": {
            "target": NON_EMPTY_STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"), value="x-amz-lex-session-state"
                )
            ],
        },
        "requestAttributes": {
            "target": NON_EMPTY_STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amz-lex-request-attributes",
                )
            ],
        },
        "sessionId": {
            "target": SESSION_ID,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"), value="x-amz-lex-session-id"
                )
            ],
        },
        "inputTranscript": {
            "target": NON_EMPTY_STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amz-lex-input-transcript",
                )
            ],
        },
        "audioStream": {
            "target": BLOB_STREAM,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#default"), value=""),
                Trait.new(id=ShapeID("smithy.api#httpPayload")),
            ],
        },
        "recognizedBotMember": {
            "target": NON_EMPTY_STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amz-lex-recognized-bot-member",
                )
            ],
        },
    },
)

RECOGNIZE_UTTERANCE = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#RecognizeUtterance"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(id=ShapeID("aws.auth#unsignedPayload")),
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {
                    "method": "POST",
                    "uri": "/bots/{botId}/botAliases/{botAliasId}/botLocales/{localeId}/sessions/{sessionId}/utterance",
                    "code": 200,
                }
            ),
        ),
    ],
)

CONVERSATION_MODE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#ConversationMode"),
    shape_type=ShapeType.ENUM,
    members={"AUDIO": {"target": UNIT}, "TEXT": {"target": UNIT}},
)

BOOLEAN = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#Boolean"),
    shape_type=ShapeType.BOOLEAN,
    traits=[Trait.new(id=ShapeID("smithy.api#default"), value=False)],
)

DISCONNECTION_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#DisconnectionEvent"),
    members={
        "eventId": {"target": EVENT_ID},
        "clientTimestampMillis": {
            "target": EPOCH_MILLIS,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=0)],
        },
    },
)

DTMF_REGEX = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#DTMFRegex"),
    shape_type=ShapeType.STRING,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
)

DTMF_INPUT_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#DTMFInputEvent"),
    members={
        "inputCharacter": {
            "target": DTMF_REGEX,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "eventId": {"target": EVENT_ID},
        "clientTimestampMillis": {
            "target": EPOCH_MILLIS,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=0)],
        },
    },
)

PLAYBACK_COMPLETION_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#PlaybackCompletionEvent"),
    members={
        "eventId": {"target": EVENT_ID},
        "clientTimestampMillis": {
            "target": EPOCH_MILLIS,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=0)],
        },
    },
)

TEXT_INPUT_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#TextInputEvent"),
    members={
        "text": {
            "target": TEXT,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "eventId": {"target": EVENT_ID},
        "clientTimestampMillis": {
            "target": EPOCH_MILLIS,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=0)],
        },
    },
)

HEARTBEAT_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#HeartbeatEvent"),
    members={"eventId": {"target": EVENT_ID}},
)

INPUT_MODE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#InputMode"),
    shape_type=ShapeType.ENUM,
    members={
        "TEXT": {"target": UNIT},
        "SPEECH": {"target": UNIT},
        "DTMF": {"target": UNIT},
    },
)

PLAYBACK_INTERRUPTION_REASON = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#PlaybackInterruptionReason"),
    shape_type=ShapeType.ENUM,
    members={
        "DTMF_START_DETECTED": {"target": UNIT},
        "TEXT_DETECTED": {"target": UNIT},
        "VOICE_START_DETECTED": {"target": UNIT},
    },
)

PLAYBACK_INTERRUPTION_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#PlaybackInterruptionEvent"),
    members={
        "eventReason": {"target": PLAYBACK_INTERRUPTION_REASON},
        "causedByEventId": {"target": EVENT_ID},
        "eventId": {"target": EVENT_ID},
    },
)

TEXT_RESPONSE_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#TextResponseEvent"),
    members={"messages": {"target": MESSAGES}, "eventId": {"target": EVENT_ID}},
)

TRANSCRIPT_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#TranscriptEvent"),
    members={"transcript": {"target": STRING}, "eventId": {"target": EVENT_ID}},
)

ELICIT_SUB_SLOT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#ElicitSubSlot"),
    members={
        "name": {
            "target": NON_EMPTY_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        # This needs to reference a schema that isn't defined yet.
        # It will be populated with a non-null value at the end of the file.
        "subSlotToElicit": None,
    },
)

DIALOG_ACTION = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#DialogAction"),
    members={
        "type": {
            "target": DIALOG_ACTION_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "slotToElicit": {"target": NON_EMPTY_STRING},
        "slotElicitationStyle": {"target": STYLE_TYPE},
        "subSlotToElicit": {"target": ELICIT_SUB_SLOT},
    },
)

RUNTIME_HINT_DETAILS = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#RuntimeHintDetails"),
    members={
        "runtimeHintValues": {"target": RUNTIME_HINT_VALUES_LIST},
        # This needs to reference a schema that isn't defined yet.
        # It will be populated with a non-null value at the end of the file.
        "subSlotHints": None,
    },
)

SLOT_HINTS_SLOT_MAP = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#SlotHintsSlotMap"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": NAME}, "value": {"target": RUNTIME_HINT_DETAILS}},
)

SLOT_HINTS_INTENT_MAP = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#SlotHintsIntentMap"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": NAME}, "value": {"target": SLOT_HINTS_SLOT_MAP}},
)

RUNTIME_HINTS = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#RuntimeHints"),
    members={"slotHints": {"target": SLOT_HINTS_INTENT_MAP}},
)

SLOT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#Slot"),
    members={
        "value": {"target": VALUE},
        "shape": {"target": SHAPE},
        # This needs to reference a schema that isn't defined yet.
        # It will be populated with a non-null value at the end of the file.
        "values": None,
        # This needs to reference a schema that isn't defined yet.
        # It will be populated with a non-null value at the end of the file.
        "subSlots": None,
    },
)

SLOTS = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#Slots"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": NON_EMPTY_STRING}, "value": {"target": SLOT}},
)

VALUES = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#Values"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": SLOT}},
)

INTENT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#Intent"),
    members={
        "name": {
            "target": NON_EMPTY_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "slots": {"target": SLOTS},
        "state": {"target": INTENT_STATE},
        "confirmationState": {"target": CONFIRMATION_STATE},
    },
)

INTERPRETATION = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#Interpretation"),
    members={
        "nluConfidence": {"target": CONFIDENCE_SCORE},
        "sentimentResponse": {"target": SENTIMENT_RESPONSE},
        "intent": {"target": INTENT},
        "interpretationSource": {"target": INTERPRETATION_SOURCE},
    },
)

INTERPRETATIONS = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#Interpretations"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": INTERPRETATION}},
)

SESSION_STATE = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#SessionState"),
    members={
        "dialogAction": {"target": DIALOG_ACTION},
        "intent": {"target": INTENT},
        "activeContexts": {"target": ACTIVE_CONTEXTS_LIST},
        "sessionAttributes": {"target": STRING_MAP},
        "originatingRequestId": {"target": NON_EMPTY_STRING},
        "runtimeHints": {"target": RUNTIME_HINTS},
    },
)

CONFIGURATION_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#ConfigurationEvent"),
    members={
        "requestAttributes": {"target": STRING_MAP},
        "responseContentType": {
            "target": NON_EMPTY_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "sessionState": {"target": SESSION_STATE},
        "welcomeMessages": {"target": MESSAGES},
        "disablePlayback": {
            "target": BOOLEAN,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=False)],
        },
        "eventId": {"target": EVENT_ID},
        "clientTimestampMillis": {
            "target": EPOCH_MILLIS,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=0)],
        },
    },
)

PUT_SESSION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#PutSessionInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.lexruntimev2#PutSessionRequest",
        )
    ],
    members={
        "botId": {
            "target": BOT_IDENTIFIER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "botAliasId": {
            "target": BOT_ALIAS_IDENTIFIER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "localeId": {
            "target": LOCALE_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "sessionId": {
            "target": SESSION_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "messages": {"target": MESSAGES},
        "sessionState": {
            "target": SESSION_STATE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "requestAttributes": {"target": STRING_MAP},
        "responseContentType": {
            "target": NON_EMPTY_STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"), value="ResponseContentType"
                )
            ],
        },
    },
)

RECOGNIZE_TEXT_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#RecognizeTextInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.lexruntimev2#RecognizeTextRequest",
        )
    ],
    members={
        "botId": {
            "target": BOT_IDENTIFIER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "botAliasId": {
            "target": BOT_ALIAS_IDENTIFIER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "localeId": {
            "target": LOCALE_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "sessionId": {
            "target": SESSION_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "text": {
            "target": TEXT,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "sessionState": {"target": SESSION_STATE},
        "requestAttributes": {"target": STRING_MAP},
    },
)

PUT_SESSION = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#PutSession"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {
                    "method": "POST",
                    "uri": "/bots/{botId}/botAliases/{botAliasId}/botLocales/{localeId}/sessions/{sessionId}",
                    "code": 200,
                }
            ),
        )
    ],
)

START_CONVERSATION_REQUEST_EVENT_STREAM = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#StartConversationRequestEventStream"),
    shape_type=ShapeType.UNION,
    traits=[Trait.new(id=ShapeID("smithy.api#streaming"))],
    members={
        "ConfigurationEvent": {"target": CONFIGURATION_EVENT},
        "AudioInputEvent": {"target": AUDIO_INPUT_EVENT},
        "DTMFInputEvent": {"target": DTMF_INPUT_EVENT},
        "TextInputEvent": {"target": TEXT_INPUT_EVENT},
        "PlaybackCompletionEvent": {"target": PLAYBACK_COMPLETION_EVENT},
        "DisconnectionEvent": {"target": DISCONNECTION_EVENT},
    },
)

START_CONVERSATION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#StartConversationInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.lexruntimev2#StartConversationRequest",
        )
    ],
    members={
        "botId": {
            "target": BOT_IDENTIFIER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "botAliasId": {
            "target": BOT_ALIAS_IDENTIFIER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "localeId": {
            "target": LOCALE_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "sessionId": {
            "target": SESSION_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "conversationMode": {
            "target": CONVERSATION_MODE,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amz-lex-conversation-mode",
                )
            ],
        },
        "requestEventStream": {
            "target": START_CONVERSATION_REQUEST_EVENT_STREAM,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpPayload")),
            ],
        },
    },
)

GET_SESSION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#GetSessionOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.lexruntimev2#GetSessionResponse",
        )
    ],
    members={
        "sessionId": {"target": NON_EMPTY_STRING},
        "messages": {"target": MESSAGES},
        "interpretations": {"target": INTERPRETATIONS},
        "sessionState": {"target": SESSION_STATE},
    },
)

INTENT_RESULT_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#IntentResultEvent"),
    members={
        "inputMode": {"target": INPUT_MODE},
        "interpretations": {"target": INTERPRETATIONS},
        "sessionState": {"target": SESSION_STATE},
        "requestAttributes": {"target": STRING_MAP},
        "sessionId": {"target": SESSION_ID},
        "eventId": {"target": EVENT_ID},
        "recognizedBotMember": {"target": RECOGNIZED_BOT_MEMBER},
    },
)

RECOGNIZE_TEXT_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#RecognizeTextOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.lexruntimev2#RecognizeTextResponse",
        )
    ],
    members={
        "messages": {"target": MESSAGES},
        "sessionState": {"target": SESSION_STATE},
        "interpretations": {"target": INTERPRETATIONS},
        "requestAttributes": {"target": STRING_MAP},
        "sessionId": {"target": SESSION_ID},
        "recognizedBotMember": {"target": RECOGNIZED_BOT_MEMBER},
    },
)

GET_SESSION = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#GetSession"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {
                    "method": "GET",
                    "uri": "/bots/{botId}/botAliases/{botAliasId}/botLocales/{localeId}/sessions/{sessionId}",
                    "code": 200,
                }
            ),
        )
    ],
)

START_CONVERSATION_RESPONSE_EVENT_STREAM = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#StartConversationResponseEventStream"),
    shape_type=ShapeType.UNION,
    traits=[Trait.new(id=ShapeID("smithy.api#streaming"))],
    members={
        "PlaybackInterruptionEvent": {"target": PLAYBACK_INTERRUPTION_EVENT},
        "TranscriptEvent": {"target": TRANSCRIPT_EVENT},
        "IntentResultEvent": {"target": INTENT_RESULT_EVENT},
        "TextResponseEvent": {"target": TEXT_RESPONSE_EVENT},
        "AudioResponseEvent": {"target": AUDIO_RESPONSE_EVENT},
        "HeartbeatEvent": {"target": HEARTBEAT_EVENT},
        "AccessDeniedException": {"target": ACCESS_DENIED_EXCEPTION},
        "ResourceNotFoundException": {"target": RESOURCE_NOT_FOUND_EXCEPTION},
        "ValidationException": {"target": VALIDATION_EXCEPTION},
        "ThrottlingException": {"target": THROTTLING_EXCEPTION},
        "InternalServerException": {"target": INTERNAL_SERVER_EXCEPTION},
        "ConflictException": {"target": CONFLICT_EXCEPTION},
        "DependencyFailedException": {"target": DEPENDENCY_FAILED_EXCEPTION},
        "BadGatewayException": {"target": BAD_GATEWAY_EXCEPTION},
    },
)

START_CONVERSATION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.lexruntimev2#StartConversationOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.lexruntimev2#StartConversationResponse",
        )
    ],
    members={
        "responseEventStream": {
            "target": START_CONVERSATION_RESPONSE_EVENT_STREAM,
            "traits": [Trait.new(id=ShapeID("smithy.api#httpPayload"))],
        }
    },
)

RECOGNIZE_TEXT = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#RecognizeText"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {
                    "method": "POST",
                    "uri": "/bots/{botId}/botAliases/{botAliasId}/botLocales/{localeId}/sessions/{sessionId}/text",
                    "code": 200,
                }
            ),
        )
    ],
)

START_CONVERSATION = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#StartConversation"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {
                    "method": "POST",
                    "uri": "/bots/{botId}/botAliases/{botAliasId}/botLocales/{localeId}/sessions/{sessionId}/conversation",
                    "code": 200,
                }
            ),
        )
    ],
)

AWS_DEEP_SENSE_RUN_TIME_SERVICE_API2_0 = Schema(
    id=ShapeID("com.amazonaws.lexruntimev2#AWSDeepSenseRunTimeServiceApi2_0"),
    shape_type=ShapeType.SERVICE,
    traits=[
        Trait.new(
            id=ShapeID("aws.auth#sigv4"), value=MappingProxyType({"name": "lex"})
        ),
        Trait.new(
            id=ShapeID("smithy.rules#endpointBdd"),
            value=MappingProxyType(
                {
                    "version": "1.1",
                    "parameters": MappingProxyType(
                        {
                            "Region": MappingProxyType(
                                {
                                    "builtIn": "AWS::Region",
                                    "required": False,
                                    "documentation": "The AWS region used to dispatch the request.",
                                    "type": "string",
                                }
                            ),
                            "UseDualStack": MappingProxyType(
                                {
                                    "builtIn": "AWS::UseDualStack",
                                    "required": True,
                                    "default": False,
                                    "documentation": "When true, use the dual-stack endpoint. If the configured endpoint does not support dual-stack, dispatching the request MAY return an error.",
                                    "type": "boolean",
                                }
                            ),
                            "UseFIPS": MappingProxyType(
                                {
                                    "builtIn": "AWS::UseFIPS",
                                    "required": True,
                                    "default": False,
                                    "documentation": "When true, send this request to the FIPS-compliant regional endpoint. If the configured endpoint does not have a FIPS compliant endpoint, dispatching the request will return an error.",
                                    "type": "boolean",
                                }
                            ),
                            "Endpoint": MappingProxyType(
                                {
                                    "builtIn": "SDK::Endpoint",
                                    "required": False,
                                    "documentation": "Override the endpoint used to send this request",
                                    "type": "string",
                                }
                            ),
                        }
                    ),
                    "conditions": (
                        MappingProxyType(
                            {
                                "fn": "isSet",
                                "argv": (MappingProxyType({"ref": "Endpoint"}),),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "isSet",
                                "argv": (MappingProxyType({"ref": "Region"}),),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "aws.partition",
                                "argv": (MappingProxyType({"ref": "Region"}),),
                                "assign": "PartitionResult",
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (MappingProxyType({"ref": "UseFIPS"}), True),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (
                                    MappingProxyType({"ref": "UseDualStack"}),
                                    True,
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "supportsDualStack",
                                            ),
                                        }
                                    ),
                                    True,
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "supportsFIPS",
                                            ),
                                        }
                                    ),
                                    True,
                                ),
                            }
                        ),
                    ),
                    "results": (
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: FIPS and custom endpoint are not supported",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: Dualstack and custom endpoint are not supported",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": MappingProxyType({"ref": "Endpoint"}),
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://runtime-v2-lex-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "FIPS and DualStack are enabled, but this partition does not support one or both",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://runtime-v2-lex-fips.{Region}.{PartitionResult#dnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "FIPS is enabled but this partition does not support FIPS",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://runtime-v2-lex.{Region}.{PartitionResult#dualStackDnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "DualStack is enabled but this partition does not support DualStack",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://runtime-v2-lex.{Region}.{PartitionResult#dnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: Missing Region",
                                "type": "error",
                            }
                        ),
                    ),
                    "root": 2,
                    "nodeCount": 13,
                    "nodes": "/////wAAAAH/////AAAAAAAAAAwAAAADAAAAAQAAAAQF9eELAAAAAgAAAAUF9eELAAAAAwAAAAgAAAAGAAAABAAAAAcF9eEKAAAABQX14QgF9eEJAAAABAAAAAoAAAAJAAAABgX14QYF9eEHAAAABQAAAAsF9eEFAAAABgX14QQF9eEFAAAAAwX14QEAAAANAAAABAX14QIF9eED",
                }
            ),
        ),
        Trait.new(
            id=ShapeID("aws.api#service"),
            value=MappingProxyType(
                {
                    "sdkId": "Lex Runtime V2",
                    "arnNamespace": "lex",
                    "cloudFormationName": "LexRuntimeV2",
                    "cloudTrailEventSource": "lexruntimev2.amazonaws.com",
                    "docId": "runtime.lex.v2-2020-08-07",
                    "endpointPrefix": "runtime-v2-lex",
                }
            ),
        ),
        Trait.new(
            id=ShapeID("aws.protocols#restJson1"),
            value=MappingProxyType(
                {"http": ("http/1.1", "h2"), "eventStreamHttp": ("h2",)}
            ),
        ),
    ],
)

ELICIT_SUB_SLOT.members["subSlotToElicit"] = Schema.member(
    id=ELICIT_SUB_SLOT.id.with_member("subSlotToElicit"),
    target=ELICIT_SUB_SLOT,
    index=1,
)

RUNTIME_HINT_DETAILS.members["subSlotHints"] = Schema.member(
    id=RUNTIME_HINT_DETAILS.id.with_member("subSlotHints"),
    target=SLOT_HINTS_SLOT_MAP,
    index=1,
)

SLOT.members["subSlots"] = Schema.member(
    id=SLOT.id.with_member("subSlots"), target=SLOTS, index=3
)

SLOT.members["values"] = Schema.member(
    id=SLOT.id.with_member("values"), target=VALUES, index=2
)
