# Code generated by smithy-python-codegen DO NOT EDIT.

from types import MappingProxyType

from smithy_core.prelude import UNIT
from smithy_core.schemas import Schema
from smithy_core.shapes import ShapeID, ShapeType
from smithy_core.traits import Trait


KMS_KEY_ID_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#KmsKeyIdType"), shape_type=ShapeType.STRING
)

REGION_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#RegionType"), shape_type=ShapeType.STRING
)

REPLICA_REGION_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ReplicaRegionType"),
    members={
        "Region": {"target": REGION_TYPE},
        "KmsKeyId": {"target": KMS_KEY_ID_TYPE},
    },
)

ADD_REPLICA_REGION_LIST_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#AddReplicaRegionListType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": REPLICA_REGION_TYPE}},
)

ERROR_CODE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#ErrorCode"), shape_type=ShapeType.STRING
)

ERROR_MESSAGE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#ErrorMessage"), shape_type=ShapeType.STRING
)

SECRET_ID_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#SecretIdType"), shape_type=ShapeType.STRING
)

API_ERROR_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#APIErrorType"),
    members={
        "SecretId": {"target": SECRET_ID_TYPE},
        "ErrorCode": {"target": ERROR_CODE},
        "Message": {"target": ERROR_MESSAGE},
    },
)

API_ERROR_LIST_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#APIErrorListType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": API_ERROR_TYPE}},
)

AUTOMATICALLY_ROTATE_AFTER_DAYS_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#AutomaticallyRotateAfterDaysType"),
    shape_type=ShapeType.LONG,
)

FILTER_NAME_STRING_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#FilterNameStringType"),
    shape_type=ShapeType.ENUM,
    members={
        "description": {"target": UNIT},
        "name": {"target": UNIT},
        "tag_key": {"target": UNIT},
        "tag_value": {"target": UNIT},
        "primary_region": {"target": UNIT},
        "owning_service": {"target": UNIT},
        "all": {"target": UNIT},
    },
)

FILTER_VALUE_STRING_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#FilterValueStringType"),
    shape_type=ShapeType.STRING,
)

FILTER_VALUES_STRING_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#FilterValuesStringList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": FILTER_VALUE_STRING_TYPE}},
)

FILTER = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#Filter"),
    members={
        "Key": {"target": FILTER_NAME_STRING_TYPE},
        "Values": {"target": FILTER_VALUES_STRING_LIST},
    },
)

FILTERS_LIST_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#FiltersListType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": FILTER}},
)

MAX_RESULTS_BATCH_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#MaxResultsBatchType"),
    shape_type=ShapeType.INTEGER,
)

NEXT_TOKEN_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#NextTokenType"),
    shape_type=ShapeType.STRING,
)

SECRET_ID_LIST_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#SecretIdListType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": SECRET_ID_TYPE}},
)

BATCH_GET_SECRET_VALUE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#BatchGetSecretValueInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#BatchGetSecretValueRequest",
        )
    ],
    members={
        "SecretIdList": {"target": SECRET_ID_LIST_TYPE},
        "Filters": {"target": FILTERS_LIST_TYPE},
        "MaxResults": {"target": MAX_RESULTS_BATCH_TYPE},
        "NextToken": {"target": NEXT_TOKEN_TYPE},
    },
)

SECRET_ARN_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#SecretARNType"),
    shape_type=ShapeType.STRING,
)

CREATED_DATE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#CreatedDateType"),
    shape_type=ShapeType.TIMESTAMP,
)

SECRET_NAME_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#SecretNameType"),
    shape_type=ShapeType.STRING,
)

SECRET_BINARY_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#SecretBinaryType"),
    shape_type=ShapeType.BLOB,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
)

SECRET_STRING_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#SecretStringType"),
    shape_type=ShapeType.STRING,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
)

SECRET_VERSION_ID_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#SecretVersionIdType"),
    shape_type=ShapeType.STRING,
)

SECRET_VERSION_STAGE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#SecretVersionStageType"),
    shape_type=ShapeType.STRING,
)

SECRET_VERSION_STAGES_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#SecretVersionStagesType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": SECRET_VERSION_STAGE_TYPE}},
)

SECRET_VALUE_ENTRY = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#SecretValueEntry"),
    members={
        "ARN": {"target": SECRET_ARN_TYPE},
        "Name": {"target": SECRET_NAME_TYPE},
        "VersionId": {"target": SECRET_VERSION_ID_TYPE},
        "SecretBinary": {"target": SECRET_BINARY_TYPE},
        "SecretString": {"target": SECRET_STRING_TYPE},
        "VersionStages": {"target": SECRET_VERSION_STAGES_TYPE},
        "CreatedDate": {"target": CREATED_DATE_TYPE},
    },
)

SECRET_VALUES_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#SecretValuesType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": SECRET_VALUE_ENTRY}},
)

BATCH_GET_SECRET_VALUE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#BatchGetSecretValueOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#BatchGetSecretValueResponse",
        )
    ],
    members={
        "SecretValues": {"target": SECRET_VALUES_TYPE},
        "NextToken": {"target": NEXT_TOKEN_TYPE},
        "Errors": {"target": API_ERROR_LIST_TYPE},
    },
)

DECRYPTION_FAILURE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#DecryptionFailure"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="client")],
    members={"Message": {"target": ERROR_MESSAGE}},
)

INTERNAL_SERVICE_ERROR = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#InternalServiceError"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="server")],
    members={"Message": {"target": ERROR_MESSAGE}},
)

INVALID_NEXT_TOKEN_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#InvalidNextTokenException"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="client")],
    members={"Message": {"target": ERROR_MESSAGE}},
)

INVALID_PARAMETER_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#InvalidParameterException"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="client")],
    members={"Message": {"target": ERROR_MESSAGE}},
)

INVALID_REQUEST_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#InvalidRequestException"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="client")],
    members={"Message": {"target": ERROR_MESSAGE}},
)

RESOURCE_NOT_FOUND_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ResourceNotFoundException"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="client")],
    members={"Message": {"target": ERROR_MESSAGE}},
)

BATCH_GET_SECRET_VALUE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#BatchGetSecretValue"),
    shape_type=ShapeType.OPERATION,
)

BOOLEAN_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#BooleanType"),
    shape_type=ShapeType.BOOLEAN,
    traits=[Trait.new(id=ShapeID("smithy.api#default"), value=False)],
)

CANCEL_ROTATE_SECRET_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#CancelRotateSecretInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#CancelRotateSecretRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

CANCEL_ROTATE_SECRET_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#CancelRotateSecretOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#CancelRotateSecretResponse",
        )
    ],
    members={
        "ARN": {"target": SECRET_ARN_TYPE},
        "Name": {"target": SECRET_NAME_TYPE},
        "VersionId": {"target": SECRET_VERSION_ID_TYPE},
    },
)

CANCEL_ROTATE_SECRET = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#CancelRotateSecret"),
    shape_type=ShapeType.OPERATION,
)

CLIENT_REQUEST_TOKEN_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#ClientRequestTokenType"),
    shape_type=ShapeType.STRING,
)

DESCRIPTION_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#DescriptionType"),
    shape_type=ShapeType.STRING,
)

NAME_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#NameType"), shape_type=ShapeType.STRING
)

TAG_KEY_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#TagKeyType"), shape_type=ShapeType.STRING
)

TAG_VALUE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#TagValueType"), shape_type=ShapeType.STRING
)

TAG = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#Tag"),
    members={"Key": {"target": TAG_KEY_TYPE}, "Value": {"target": TAG_VALUE_TYPE}},
)

TAG_LIST_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#TagListType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": TAG}},
)

MEDEA_TYPE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#MedeaTypeType"),
    shape_type=ShapeType.STRING,
)

CREATE_SECRET_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#CreateSecretInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#CreateSecretRequest",
        )
    ],
    members={
        "Name": {
            "target": NAME_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "ClientRequestToken": {
            "target": CLIENT_REQUEST_TOKEN_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#idempotencyToken"))],
        },
        "Description": {"target": DESCRIPTION_TYPE},
        "KmsKeyId": {"target": KMS_KEY_ID_TYPE},
        "SecretBinary": {"target": SECRET_BINARY_TYPE},
        "SecretString": {"target": SECRET_STRING_TYPE},
        "Tags": {"target": TAG_LIST_TYPE},
        "AddReplicaRegions": {"target": ADD_REPLICA_REGION_LIST_TYPE},
        "ForceOverwriteReplicaSecret": {
            "target": BOOLEAN_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=False)],
        },
        "Type": {"target": MEDEA_TYPE_TYPE},
    },
)

LAST_ACCESSED_DATE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#LastAccessedDateType"),
    shape_type=ShapeType.TIMESTAMP,
)

STATUS_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#StatusType"),
    shape_type=ShapeType.ENUM,
    members={
        "InSync": {"target": UNIT},
        "Failed": {"target": UNIT},
        "InProgress": {"target": UNIT},
    },
)

STATUS_MESSAGE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#StatusMessageType"),
    shape_type=ShapeType.STRING,
)

REPLICATION_STATUS_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ReplicationStatusType"),
    members={
        "Region": {"target": REGION_TYPE},
        "KmsKeyId": {"target": KMS_KEY_ID_TYPE},
        "Status": {"target": STATUS_TYPE},
        "StatusMessage": {"target": STATUS_MESSAGE_TYPE},
        "LastAccessedDate": {"target": LAST_ACCESSED_DATE_TYPE},
    },
)

REPLICATION_STATUS_LIST_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ReplicationStatusListType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": REPLICATION_STATUS_TYPE}},
)

CREATE_SECRET_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#CreateSecretOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#CreateSecretResponse",
        )
    ],
    members={
        "ARN": {"target": SECRET_ARN_TYPE},
        "Name": {"target": SECRET_NAME_TYPE},
        "VersionId": {"target": SECRET_VERSION_ID_TYPE},
        "ReplicationStatus": {"target": REPLICATION_STATUS_LIST_TYPE},
    },
)

ENCRYPTION_FAILURE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#EncryptionFailure"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="client")],
    members={"Message": {"target": ERROR_MESSAGE}},
)

LIMIT_EXCEEDED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#LimitExceededException"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="client")],
    members={"Message": {"target": ERROR_MESSAGE}},
)

MALFORMED_POLICY_DOCUMENT_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#MalformedPolicyDocumentException"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="client")],
    members={"Message": {"target": ERROR_MESSAGE}},
)

PRECONDITION_NOT_MET_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#PreconditionNotMetException"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="client")],
    members={"Message": {"target": ERROR_MESSAGE}},
)

RESOURCE_EXISTS_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ResourceExistsException"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="client")],
    members={"Message": {"target": ERROR_MESSAGE}},
)

CREATE_SECRET = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#CreateSecret"),
    shape_type=ShapeType.OPERATION,
)

DELETED_DATE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#DeletedDateType"),
    shape_type=ShapeType.TIMESTAMP,
)

DELETE_RESOURCE_POLICY_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#DeleteResourcePolicyInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#DeleteResourcePolicyRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

DELETE_RESOURCE_POLICY_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#DeleteResourcePolicyOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#DeleteResourcePolicyResponse",
        )
    ],
    members={"ARN": {"target": SECRET_ARN_TYPE}, "Name": {"target": NAME_TYPE}},
)

DELETE_RESOURCE_POLICY = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#DeleteResourcePolicy"),
    shape_type=ShapeType.OPERATION,
)

RECOVERY_WINDOW_IN_DAYS_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#RecoveryWindowInDaysType"),
    shape_type=ShapeType.LONG,
    traits=[Trait.new(id=ShapeID("smithy.api#default"), value=0)],
)

DELETE_SECRET_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#DeleteSecretInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#DeleteSecretRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "RecoveryWindowInDays": {
            "target": RECOVERY_WINDOW_IN_DAYS_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=None)],
        },
        "ForceDeleteWithoutRecovery": {
            "target": BOOLEAN_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=None)],
        },
    },
)

DELETION_DATE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#DeletionDateType"),
    shape_type=ShapeType.TIMESTAMP,
)

DELETE_SECRET_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#DeleteSecretOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#DeleteSecretResponse",
        )
    ],
    members={
        "ARN": {"target": SECRET_ARN_TYPE},
        "Name": {"target": SECRET_NAME_TYPE},
        "DeletionDate": {"target": DELETION_DATE_TYPE},
    },
)

DELETE_SECRET = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#DeleteSecret"),
    shape_type=ShapeType.OPERATION,
)

DESCRIBE_SECRET_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#DescribeSecretInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#DescribeSecretRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

TIMESTAMP_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#TimestampType"),
    shape_type=ShapeType.TIMESTAMP,
)

EXTERNAL_SECRET_ROTATION_METADATA_ITEM_KEY_TYPE = Schema(
    id=ShapeID(
        "com.amazonaws.secretsmanager#ExternalSecretRotationMetadataItemKeyType"
    ),
    shape_type=ShapeType.STRING,
)

EXTERNAL_SECRET_ROTATION_METADATA_ITEM_VALUE_TYPE = Schema(
    id=ShapeID(
        "com.amazonaws.secretsmanager#ExternalSecretRotationMetadataItemValueType"
    ),
    shape_type=ShapeType.STRING,
)

EXTERNAL_SECRET_ROTATION_METADATA_ITEM = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ExternalSecretRotationMetadataItem"),
    members={
        "Key": {"target": EXTERNAL_SECRET_ROTATION_METADATA_ITEM_KEY_TYPE},
        "Value": {"target": EXTERNAL_SECRET_ROTATION_METADATA_ITEM_VALUE_TYPE},
    },
)

EXTERNAL_SECRET_ROTATION_METADATA_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ExternalSecretRotationMetadataType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": EXTERNAL_SECRET_ROTATION_METADATA_ITEM}},
)

ROLE_ARN_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#RoleARNType"), shape_type=ShapeType.STRING
)

LAST_CHANGED_DATE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#LastChangedDateType"),
    shape_type=ShapeType.TIMESTAMP,
)

LAST_ROTATED_DATE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#LastRotatedDateType"),
    shape_type=ShapeType.TIMESTAMP,
)

NEXT_ROTATION_DATE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#NextRotationDateType"),
    shape_type=ShapeType.TIMESTAMP,
)

OWNING_SERVICE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#OwningServiceType"),
    shape_type=ShapeType.STRING,
)

ROTATION_ENABLED_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#RotationEnabledType"),
    shape_type=ShapeType.BOOLEAN,
    traits=[Trait.new(id=ShapeID("smithy.api#default"), value=False)],
)

ROTATION_LAMBDA_ARN_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#RotationLambdaARNType"),
    shape_type=ShapeType.STRING,
)

DURATION_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#DurationType"), shape_type=ShapeType.STRING
)

SCHEDULE_EXPRESSION_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#ScheduleExpressionType"),
    shape_type=ShapeType.STRING,
)

ROTATION_RULES_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#RotationRulesType"),
    members={
        "AutomaticallyAfterDays": {"target": AUTOMATICALLY_ROTATE_AFTER_DAYS_TYPE},
        "Duration": {"target": DURATION_TYPE},
        "ScheduleExpression": {"target": SCHEDULE_EXPRESSION_TYPE},
    },
)

SECRET_VERSIONS_TO_STAGES_MAP_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#SecretVersionsToStagesMapType"),
    shape_type=ShapeType.MAP,
    members={
        "key": {"target": SECRET_VERSION_ID_TYPE},
        "value": {"target": SECRET_VERSION_STAGES_TYPE},
    },
)

DESCRIBE_SECRET_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#DescribeSecretOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#DescribeSecretResponse",
        )
    ],
    members={
        "ARN": {"target": SECRET_ARN_TYPE},
        "Name": {"target": SECRET_NAME_TYPE},
        "Type": {"target": MEDEA_TYPE_TYPE},
        "Description": {"target": DESCRIPTION_TYPE},
        "KmsKeyId": {"target": KMS_KEY_ID_TYPE},
        "RotationEnabled": {
            "target": ROTATION_ENABLED_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=None)],
        },
        "RotationLambdaARN": {"target": ROTATION_LAMBDA_ARN_TYPE},
        "RotationRules": {"target": ROTATION_RULES_TYPE},
        "ExternalSecretRotationMetadata": {
            "target": EXTERNAL_SECRET_ROTATION_METADATA_TYPE
        },
        "ExternalSecretRotationRoleArn": {"target": ROLE_ARN_TYPE},
        "LastRotatedDate": {"target": LAST_ROTATED_DATE_TYPE},
        "LastChangedDate": {"target": LAST_CHANGED_DATE_TYPE},
        "LastAccessedDate": {"target": LAST_ACCESSED_DATE_TYPE},
        "DeletedDate": {"target": DELETED_DATE_TYPE},
        "NextRotationDate": {"target": NEXT_ROTATION_DATE_TYPE},
        "Tags": {"target": TAG_LIST_TYPE},
        "VersionIdsToStages": {"target": SECRET_VERSIONS_TO_STAGES_MAP_TYPE},
        "OwningService": {"target": OWNING_SERVICE_TYPE},
        "CreatedDate": {"target": TIMESTAMP_TYPE},
        "PrimaryRegion": {"target": REGION_TYPE},
        "ReplicationStatus": {"target": REPLICATION_STATUS_LIST_TYPE},
    },
)

DESCRIBE_SECRET = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#DescribeSecret"),
    shape_type=ShapeType.OPERATION,
)

EXCLUDE_CHARACTERS_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#ExcludeCharactersType"),
    shape_type=ShapeType.STRING,
)

EXCLUDE_LOWERCASE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#ExcludeLowercaseType"),
    shape_type=ShapeType.BOOLEAN,
    traits=[Trait.new(id=ShapeID("smithy.api#default"), value=False)],
)

EXCLUDE_NUMBERS_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#ExcludeNumbersType"),
    shape_type=ShapeType.BOOLEAN,
    traits=[Trait.new(id=ShapeID("smithy.api#default"), value=False)],
)

EXCLUDE_PUNCTUATION_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#ExcludePunctuationType"),
    shape_type=ShapeType.BOOLEAN,
    traits=[Trait.new(id=ShapeID("smithy.api#default"), value=False)],
)

EXCLUDE_UPPERCASE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#ExcludeUppercaseType"),
    shape_type=ShapeType.BOOLEAN,
    traits=[Trait.new(id=ShapeID("smithy.api#default"), value=False)],
)

INCLUDE_SPACE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#IncludeSpaceType"),
    shape_type=ShapeType.BOOLEAN,
    traits=[Trait.new(id=ShapeID("smithy.api#default"), value=False)],
)

PASSWORD_LENGTH_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#PasswordLengthType"),
    shape_type=ShapeType.LONG,
)

REQUIRE_EACH_INCLUDED_TYPE_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#RequireEachIncludedTypeType"),
    shape_type=ShapeType.BOOLEAN,
    traits=[Trait.new(id=ShapeID("smithy.api#default"), value=False)],
)

GET_RANDOM_PASSWORD_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#GetRandomPasswordInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#GetRandomPasswordRequest",
        )
    ],
    members={
        "PasswordLength": {"target": PASSWORD_LENGTH_TYPE},
        "ExcludeCharacters": {"target": EXCLUDE_CHARACTERS_TYPE},
        "ExcludeNumbers": {
            "target": EXCLUDE_NUMBERS_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=None)],
        },
        "ExcludePunctuation": {
            "target": EXCLUDE_PUNCTUATION_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=None)],
        },
        "ExcludeUppercase": {
            "target": EXCLUDE_UPPERCASE_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=None)],
        },
        "ExcludeLowercase": {
            "target": EXCLUDE_LOWERCASE_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=None)],
        },
        "IncludeSpace": {
            "target": INCLUDE_SPACE_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=None)],
        },
        "RequireEachIncludedType": {
            "target": REQUIRE_EACH_INCLUDED_TYPE_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=None)],
        },
    },
)

RANDOM_PASSWORD_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#RandomPasswordType"),
    shape_type=ShapeType.STRING,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
)

GET_RANDOM_PASSWORD_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#GetRandomPasswordOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#GetRandomPasswordResponse",
        )
    ],
    members={"RandomPassword": {"target": RANDOM_PASSWORD_TYPE}},
)

GET_RANDOM_PASSWORD = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#GetRandomPassword"),
    shape_type=ShapeType.OPERATION,
)

GET_RESOURCE_POLICY_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#GetResourcePolicyInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#GetResourcePolicyRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

NON_EMPTY_RESOURCE_POLICY_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#NonEmptyResourcePolicyType"),
    shape_type=ShapeType.STRING,
)

GET_RESOURCE_POLICY_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#GetResourcePolicyOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#GetResourcePolicyResponse",
        )
    ],
    members={
        "ARN": {"target": SECRET_ARN_TYPE},
        "Name": {"target": NAME_TYPE},
        "ResourcePolicy": {"target": NON_EMPTY_RESOURCE_POLICY_TYPE},
    },
)

GET_RESOURCE_POLICY = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#GetResourcePolicy"),
    shape_type=ShapeType.OPERATION,
)

GET_SECRET_VALUE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#GetSecretValueInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#GetSecretValueRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "VersionId": {"target": SECRET_VERSION_ID_TYPE},
        "VersionStage": {"target": SECRET_VERSION_STAGE_TYPE},
    },
)

GET_SECRET_VALUE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#GetSecretValueOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#GetSecretValueResponse",
        )
    ],
    members={
        "ARN": {"target": SECRET_ARN_TYPE},
        "Name": {"target": SECRET_NAME_TYPE},
        "VersionId": {"target": SECRET_VERSION_ID_TYPE},
        "SecretBinary": {"target": SECRET_BINARY_TYPE},
        "SecretString": {"target": SECRET_STRING_TYPE},
        "VersionStages": {"target": SECRET_VERSION_STAGES_TYPE},
        "CreatedDate": {"target": CREATED_DATE_TYPE},
    },
)

GET_SECRET_VALUE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#GetSecretValue"),
    shape_type=ShapeType.OPERATION,
)

KMS_KEY_ID_LIST_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#KmsKeyIdListType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": KMS_KEY_ID_TYPE}},
)

MAX_RESULTS_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#MaxResultsType"),
    shape_type=ShapeType.INTEGER,
)

SORT_BY_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#SortByType"),
    shape_type=ShapeType.ENUM,
    members={
        "created_date": {"target": UNIT},
        "last_accessed_date": {"target": UNIT},
        "last_changed_date": {"target": UNIT},
        "name": {"target": UNIT},
    },
)

SORT_ORDER_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#SortOrderType"),
    shape_type=ShapeType.ENUM,
    members={"asc": {"target": UNIT}, "desc": {"target": UNIT}},
)

LIST_SECRETS_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ListSecretsInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#ListSecretsRequest",
        )
    ],
    members={
        "IncludePlannedDeletion": {
            "target": BOOLEAN_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=None)],
        },
        "MaxResults": {"target": MAX_RESULTS_TYPE},
        "NextToken": {"target": NEXT_TOKEN_TYPE},
        "Filters": {"target": FILTERS_LIST_TYPE},
        "SortOrder": {"target": SORT_ORDER_TYPE},
        "SortBy": {"target": SORT_BY_TYPE},
    },
)

SECRET_LIST_ENTRY = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#SecretListEntry"),
    members={
        "ARN": {"target": SECRET_ARN_TYPE},
        "Name": {"target": SECRET_NAME_TYPE},
        "Type": {"target": MEDEA_TYPE_TYPE},
        "Description": {"target": DESCRIPTION_TYPE},
        "KmsKeyId": {"target": KMS_KEY_ID_TYPE},
        "RotationEnabled": {
            "target": ROTATION_ENABLED_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=None)],
        },
        "RotationLambdaARN": {"target": ROTATION_LAMBDA_ARN_TYPE},
        "RotationRules": {"target": ROTATION_RULES_TYPE},
        "ExternalSecretRotationMetadata": {
            "target": EXTERNAL_SECRET_ROTATION_METADATA_TYPE
        },
        "ExternalSecretRotationRoleArn": {"target": ROLE_ARN_TYPE},
        "LastRotatedDate": {"target": LAST_ROTATED_DATE_TYPE},
        "LastChangedDate": {"target": LAST_CHANGED_DATE_TYPE},
        "LastAccessedDate": {"target": LAST_ACCESSED_DATE_TYPE},
        "DeletedDate": {"target": DELETED_DATE_TYPE},
        "NextRotationDate": {"target": NEXT_ROTATION_DATE_TYPE},
        "Tags": {"target": TAG_LIST_TYPE},
        "SecretVersionsToStages": {"target": SECRET_VERSIONS_TO_STAGES_MAP_TYPE},
        "OwningService": {"target": OWNING_SERVICE_TYPE},
        "CreatedDate": {"target": TIMESTAMP_TYPE},
        "PrimaryRegion": {"target": REGION_TYPE},
    },
)

SECRET_LIST_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#SecretListType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": SECRET_LIST_ENTRY}},
)

LIST_SECRETS_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ListSecretsOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#ListSecretsResponse",
        )
    ],
    members={
        "SecretList": {"target": SECRET_LIST_TYPE},
        "NextToken": {"target": NEXT_TOKEN_TYPE},
    },
)

LIST_SECRETS = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#ListSecrets"),
    shape_type=ShapeType.OPERATION,
)

LIST_SECRET_VERSION_IDS_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ListSecretVersionIdsInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#ListSecretVersionIdsRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "MaxResults": {"target": MAX_RESULTS_TYPE},
        "NextToken": {"target": NEXT_TOKEN_TYPE},
        "IncludeDeprecated": {
            "target": BOOLEAN_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=None)],
        },
    },
)

SECRET_VERSIONS_LIST_ENTRY = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#SecretVersionsListEntry"),
    members={
        "VersionId": {"target": SECRET_VERSION_ID_TYPE},
        "VersionStages": {"target": SECRET_VERSION_STAGES_TYPE},
        "LastAccessedDate": {"target": LAST_ACCESSED_DATE_TYPE},
        "CreatedDate": {"target": CREATED_DATE_TYPE},
        "KmsKeyIds": {"target": KMS_KEY_ID_LIST_TYPE},
    },
)

SECRET_VERSIONS_LIST_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#SecretVersionsListType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": SECRET_VERSIONS_LIST_ENTRY}},
)

LIST_SECRET_VERSION_IDS_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ListSecretVersionIdsOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#ListSecretVersionIdsResponse",
        )
    ],
    members={
        "Versions": {"target": SECRET_VERSIONS_LIST_TYPE},
        "NextToken": {"target": NEXT_TOKEN_TYPE},
        "ARN": {"target": SECRET_ARN_TYPE},
        "Name": {"target": SECRET_NAME_TYPE},
    },
)

LIST_SECRET_VERSION_IDS = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#ListSecretVersionIds"),
    shape_type=ShapeType.OPERATION,
)

PUBLIC_POLICY_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#PublicPolicyException"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="client")],
    members={"Message": {"target": ERROR_MESSAGE}},
)

PUT_RESOURCE_POLICY_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#PutResourcePolicyInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#PutResourcePolicyRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "ResourcePolicy": {
            "target": NON_EMPTY_RESOURCE_POLICY_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "BlockPublicPolicy": {
            "target": BOOLEAN_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=None)],
        },
    },
)

PUT_RESOURCE_POLICY_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#PutResourcePolicyOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#PutResourcePolicyResponse",
        )
    ],
    members={"ARN": {"target": SECRET_ARN_TYPE}, "Name": {"target": NAME_TYPE}},
)

PUT_RESOURCE_POLICY = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#PutResourcePolicy"),
    shape_type=ShapeType.OPERATION,
)

ROTATION_TOKEN_TYPE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#RotationTokenType"),
    shape_type=ShapeType.STRING,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
)

PUT_SECRET_VALUE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#PutSecretValueInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#PutSecretValueRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "ClientRequestToken": {
            "target": CLIENT_REQUEST_TOKEN_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#idempotencyToken"))],
        },
        "SecretBinary": {"target": SECRET_BINARY_TYPE},
        "SecretString": {"target": SECRET_STRING_TYPE},
        "VersionStages": {"target": SECRET_VERSION_STAGES_TYPE},
        "RotationToken": {"target": ROTATION_TOKEN_TYPE},
    },
)

PUT_SECRET_VALUE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#PutSecretValueOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#PutSecretValueResponse",
        )
    ],
    members={
        "ARN": {"target": SECRET_ARN_TYPE},
        "Name": {"target": SECRET_NAME_TYPE},
        "VersionId": {"target": SECRET_VERSION_ID_TYPE},
        "VersionStages": {"target": SECRET_VERSION_STAGES_TYPE},
    },
)

PUT_SECRET_VALUE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#PutSecretValue"),
    shape_type=ShapeType.OPERATION,
)

REMOVE_REPLICA_REGION_LIST_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#RemoveReplicaRegionListType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": REGION_TYPE}},
)

REMOVE_REGIONS_FROM_REPLICATION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#RemoveRegionsFromReplicationInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#RemoveRegionsFromReplicationRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "RemoveReplicaRegions": {
            "target": REMOVE_REPLICA_REGION_LIST_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

REMOVE_REGIONS_FROM_REPLICATION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#RemoveRegionsFromReplicationOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#RemoveRegionsFromReplicationResponse",
        )
    ],
    members={
        "ARN": {"target": SECRET_ARN_TYPE},
        "ReplicationStatus": {"target": REPLICATION_STATUS_LIST_TYPE},
    },
)

REMOVE_REGIONS_FROM_REPLICATION = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#RemoveRegionsFromReplication"),
    shape_type=ShapeType.OPERATION,
)

REPLICATE_SECRET_TO_REGIONS_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ReplicateSecretToRegionsInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#ReplicateSecretToRegionsRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "AddReplicaRegions": {
            "target": ADD_REPLICA_REGION_LIST_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "ForceOverwriteReplicaSecret": {
            "target": BOOLEAN_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=False)],
        },
    },
)

REPLICATE_SECRET_TO_REGIONS_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ReplicateSecretToRegionsOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#ReplicateSecretToRegionsResponse",
        )
    ],
    members={
        "ARN": {"target": SECRET_ARN_TYPE},
        "ReplicationStatus": {"target": REPLICATION_STATUS_LIST_TYPE},
    },
)

REPLICATE_SECRET_TO_REGIONS = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#ReplicateSecretToRegions"),
    shape_type=ShapeType.OPERATION,
)

RESTORE_SECRET_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#RestoreSecretInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#RestoreSecretRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

RESTORE_SECRET_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#RestoreSecretOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#RestoreSecretResponse",
        )
    ],
    members={"ARN": {"target": SECRET_ARN_TYPE}, "Name": {"target": SECRET_NAME_TYPE}},
)

RESTORE_SECRET = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#RestoreSecret"),
    shape_type=ShapeType.OPERATION,
)

ROTATE_SECRET_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#RotateSecretInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#RotateSecretRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "ClientRequestToken": {
            "target": CLIENT_REQUEST_TOKEN_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#idempotencyToken"))],
        },
        "RotationLambdaARN": {"target": ROTATION_LAMBDA_ARN_TYPE},
        "RotationRules": {"target": ROTATION_RULES_TYPE},
        "ExternalSecretRotationMetadata": {
            "target": EXTERNAL_SECRET_ROTATION_METADATA_TYPE
        },
        "ExternalSecretRotationRoleArn": {"target": ROLE_ARN_TYPE},
        "RotateImmediately": {
            "target": BOOLEAN_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=None)],
        },
    },
)

ROTATE_SECRET_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#RotateSecretOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#RotateSecretResponse",
        )
    ],
    members={
        "ARN": {"target": SECRET_ARN_TYPE},
        "Name": {"target": SECRET_NAME_TYPE},
        "VersionId": {"target": SECRET_VERSION_ID_TYPE},
    },
)

ROTATE_SECRET = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#RotateSecret"),
    shape_type=ShapeType.OPERATION,
)

STOP_REPLICATION_TO_REPLICA_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#StopReplicationToReplicaInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#StopReplicationToReplicaRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

STOP_REPLICATION_TO_REPLICA_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#StopReplicationToReplicaOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#StopReplicationToReplicaResponse",
        )
    ],
    members={"ARN": {"target": SECRET_ARN_TYPE}},
)

STOP_REPLICATION_TO_REPLICA = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#StopReplicationToReplica"),
    shape_type=ShapeType.OPERATION,
)

TAG_RESOURCE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#TagResourceInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#TagResourceRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Tags": {
            "target": TAG_LIST_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

TAG_RESOURCE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#TagResourceOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

TAG_RESOURCE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#TagResource"),
    shape_type=ShapeType.OPERATION,
)

TAG_KEY_LIST_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#TagKeyListType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": TAG_KEY_TYPE}},
)

UNTAG_RESOURCE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#UntagResourceInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#UntagResourceRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "TagKeys": {
            "target": TAG_KEY_LIST_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

UNTAG_RESOURCE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#UntagResourceOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

UNTAG_RESOURCE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#UntagResource"),
    shape_type=ShapeType.OPERATION,
)

UPDATE_SECRET_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#UpdateSecretInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#UpdateSecretRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "ClientRequestToken": {
            "target": CLIENT_REQUEST_TOKEN_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#idempotencyToken"))],
        },
        "Description": {"target": DESCRIPTION_TYPE},
        "KmsKeyId": {"target": KMS_KEY_ID_TYPE},
        "SecretBinary": {"target": SECRET_BINARY_TYPE},
        "SecretString": {"target": SECRET_STRING_TYPE},
        "Type": {"target": MEDEA_TYPE_TYPE},
    },
)

UPDATE_SECRET_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#UpdateSecretOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#UpdateSecretResponse",
        )
    ],
    members={
        "ARN": {"target": SECRET_ARN_TYPE},
        "Name": {"target": SECRET_NAME_TYPE},
        "VersionId": {"target": SECRET_VERSION_ID_TYPE},
    },
)

UPDATE_SECRET = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#UpdateSecret"),
    shape_type=ShapeType.OPERATION,
)

UPDATE_SECRET_VERSION_STAGE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#UpdateSecretVersionStageInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#UpdateSecretVersionStageRequest",
        )
    ],
    members={
        "SecretId": {
            "target": SECRET_ID_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "VersionStage": {
            "target": SECRET_VERSION_STAGE_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "RemoveFromVersionId": {"target": SECRET_VERSION_ID_TYPE},
        "MoveToVersionId": {"target": SECRET_VERSION_ID_TYPE},
    },
)

UPDATE_SECRET_VERSION_STAGE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#UpdateSecretVersionStageOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#UpdateSecretVersionStageResponse",
        )
    ],
    members={"ARN": {"target": SECRET_ARN_TYPE}, "Name": {"target": SECRET_NAME_TYPE}},
)

UPDATE_SECRET_VERSION_STAGE = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#UpdateSecretVersionStage"),
    shape_type=ShapeType.OPERATION,
)

VALIDATE_RESOURCE_POLICY_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ValidateResourcePolicyInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#ValidateResourcePolicyRequest",
        )
    ],
    members={
        "SecretId": {"target": SECRET_ID_TYPE},
        "ResourcePolicy": {
            "target": NON_EMPTY_RESOURCE_POLICY_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

VALIDATION_ERRORS_ENTRY = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ValidationErrorsEntry"),
    members={
        "CheckName": {"target": NAME_TYPE},
        "ErrorMessage": {"target": ERROR_MESSAGE},
    },
)

VALIDATION_ERRORS_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ValidationErrorsType"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": VALIDATION_ERRORS_ENTRY}},
)

VALIDATE_RESOURCE_POLICY_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.secretsmanager#ValidateResourcePolicyOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.secretsmanager#ValidateResourcePolicyResponse",
        )
    ],
    members={
        "PolicyValidationPassed": {
            "target": BOOLEAN_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=False)],
        },
        "ValidationErrors": {"target": VALIDATION_ERRORS_TYPE},
    },
)

VALIDATE_RESOURCE_POLICY = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#ValidateResourcePolicy"),
    shape_type=ShapeType.OPERATION,
)

SECRETSMANAGER = Schema(
    id=ShapeID("com.amazonaws.secretsmanager#secretsmanager"),
    shape_type=ShapeType.SERVICE,
    traits=[
        Trait.new(
            id=ShapeID("aws.auth#sigv4"),
            value=MappingProxyType({"name": "secretsmanager"}),
        ),
        Trait.new(id=ShapeID("aws.protocols#awsJson1_1")),
        Trait.new(
            id=ShapeID("smithy.rules#endpointBdd"),
            value=MappingProxyType(
                {
                    "version": "1.1",
                    "parameters": MappingProxyType(
                        {
                            "Region": MappingProxyType(
                                {
                                    "builtIn": "AWS::Region",
                                    "required": False,
                                    "documentation": "The AWS region used to dispatch the request.",
                                    "type": "string",
                                }
                            ),
                            "UseDualStack": MappingProxyType(
                                {
                                    "builtIn": "AWS::UseDualStack",
                                    "required": True,
                                    "default": False,
                                    "documentation": "When true, use the dual-stack endpoint. If the configured endpoint does not support dual-stack, dispatching the request MAY return an error.",
                                    "type": "boolean",
                                }
                            ),
                            "UseFIPS": MappingProxyType(
                                {
                                    "builtIn": "AWS::UseFIPS",
                                    "required": True,
                                    "default": False,
                                    "documentation": "When true, send this request to the FIPS-compliant regional endpoint. If the configured endpoint does not have a FIPS compliant endpoint, dispatching the request will return an error.",
                                    "type": "boolean",
                                }
                            ),
                            "Endpoint": MappingProxyType(
                                {
                                    "builtIn": "SDK::Endpoint",
                                    "required": False,
                                    "documentation": "Override the endpoint used to send this request",
                                    "type": "string",
                                }
                            ),
                        }
                    ),
                    "conditions": (
                        MappingProxyType(
                            {
                                "fn": "isSet",
                                "argv": (MappingProxyType({"ref": "Endpoint"}),),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "isSet",
                                "argv": (MappingProxyType({"ref": "Region"}),),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "aws.partition",
                                "argv": (MappingProxyType({"ref": "Region"}),),
                                "assign": "PartitionResult",
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (MappingProxyType({"ref": "UseFIPS"}), True),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (
                                    MappingProxyType({"ref": "UseDualStack"}),
                                    True,
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "supportsDualStack",
                                            ),
                                        }
                                    ),
                                    True,
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "supportsFIPS",
                                            ),
                                        }
                                    ),
                                    True,
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "stringEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "name",
                                            ),
                                        }
                                    ),
                                    "aws",
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "stringEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "name",
                                            ),
                                        }
                                    ),
                                    "aws-cn",
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "stringEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "name",
                                            ),
                                        }
                                    ),
                                    "aws-us-gov",
                                ),
                            }
                        ),
                    ),
                    "results": (
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: FIPS and custom endpoint are not supported",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: Dualstack and custom endpoint are not supported",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": MappingProxyType({"ref": "Endpoint"}),
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://secretsmanager-fips.{Region}.amazonaws.com",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://secretsmanager-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "FIPS and DualStack are enabled, but this partition does not support one or both",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://secretsmanager-fips.{Region}.{PartitionResult#dnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "FIPS is enabled but this partition does not support FIPS",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://secretsmanager.{Region}.amazonaws.com",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://secretsmanager.{Region}.amazonaws.com.cn",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://secretsmanager.{Region}.{PartitionResult#dualStackDnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "DualStack is enabled but this partition does not support DualStack",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://secretsmanager.{Region}.{PartitionResult#dnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: Missing Region",
                                "type": "error",
                            }
                        ),
                    ),
                    "root": 2,
                    "nodeCount": 18,
                    "nodes": "/////wAAAAH/////AAAAAAAAABEAAAADAAAAAQAAAAQF9eEOAAAAAgAAAAUF9eEOAAAAAwAAAAsAAAAGAAAABAAAAAcF9eENAAAABQAAAAgF9eEMAAAABwX14QkAAAAJAAAACAX14QoAAAAKAAAACQX14QkF9eELAAAABAAAAA0AAAAMAAAABgX14QcF9eEIAAAABQAAAA4F9eEGAAAABgAAAA8F9eEGAAAABwX14QQAAAAQAAAACQX14QQF9eEFAAAAAwX14QEAAAASAAAABAX14QIF9eED",
                }
            ),
        ),
        Trait.new(
            id=ShapeID("aws.api#service"),
            value=MappingProxyType(
                {
                    "sdkId": "Secrets Manager",
                    "arnNamespace": "secretsmanager",
                    "cloudFormationName": "SecretsManager",
                    "cloudTrailEventSource": "secretsmanager.amazonaws.com",
                    "docId": "secretsmanager-2017-10-17",
                    "endpointPrefix": "secretsmanager",
                }
            ),
        ),
    ],
)
