# Code generated by smithy-python-codegen DO NOT EDIT.

from copy import deepcopy
import logging
from typing import Any, cast

from smithy_aws_core.config import ConfigSource
from smithy_aws_core.identity import AWSCredentialsIdentity
from smithy_aws_core.identity.chain import IdentityChain
from smithy_core.aio.client import AsyncClient, ClientCall, RequestPipeline
from smithy_core.aio.eventstream import DuplexEventStream
from smithy_core.deserializers import DeserializeableShape
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.schemas import APIOperation
from smithy_core.serializers import SerializeableShape
from smithy_http.aio.interfaces import HTTPClient
from smithy_http.plugins import user_agent_plugin

from .config import AsyncSageMakerRuntimeHTTP2Config, Plugin
from .models import (
    INVOKE_ENDPOINT_WITH_BIDIRECTIONAL_STREAM,
    InvokeEndpointWithBidirectionalStreamInput,
    InvokeEndpointWithBidirectionalStreamOutput,
    RequestStreamEvent,
    ResponseStreamEvent,
    _ResponseStreamEventDeserializer,
)
from .user_agent import aws_user_agent_plugin


logger = logging.getLogger(__name__)


class AsyncSageMakerRuntimeHTTP2Client(AsyncClient):
    """The Amazon SageMaker AI runtime HTTP/2 API."""

    def __init__(
        self,
        config: AsyncSageMakerRuntimeHTTP2Config | None = None,
        plugins: list[Plugin] | None = None,
    ):
        """
        Constructor for `AsyncSageMakerRuntimeHTTP2Client`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables applied once to the client's base configuration.
                Their changes are inherited by every operation invocation.
        """
        super().__init__()
        self._config = config
        self._plugins = plugins
        self._client_plugins: list[Plugin] = [aws_user_agent_plugin, user_agent_plugin]

    async def _ensure_setup(self) -> AsyncSageMakerRuntimeHTTP2Config:
        if not self._setup_done:
            async with self._derive_lock:
                if self._closed:
                    raise RuntimeError(
                        "Cannot invoke an operation on a client that has been closed."
                    )
                if not self._setup_done:
                    if self._config is None:
                        config = await AsyncSageMakerRuntimeHTTP2Config.resolve()
                    else:
                        # Copy so plugins don't mutate the caller's config.
                        config = deepcopy(self._config)
                    for plugin in self._client_plugins:
                        plugin(config)
                    if self._plugins:
                        for plugin in self._plugins:
                            plugin(config)
                    # Publish state only after setup fully succeeds, so a
                    # failed _post_setup leaves the caller's config untouched
                    # (no re-applied plugins) and the transport closeable.
                    await self._post_setup(config)
                    self._transport = config.transport
                    self._config = config
                    self._setup_done = True
        assert self._config is not None
        return self._config

    async def _post_setup(self, config: AsyncSageMakerRuntimeHTTP2Config) -> None:
        if config.aws_credentials_identity_resolver is None:
            config_context = config.resolution_context()
            config_file = None
            profile_name = None
            if config_context is not None:
                config_file = await config_context.parsed_profiles()
                if config_context.profile_source is ConfigSource.OVERRIDE:
                    profile_name = config_context.profile_name
            config.aws_credentials_identity_resolver = await IdentityChain.create(
                AWSCredentialsIdentity,
                config_file=config_file,
                profile_name=profile_name,
                region_override=config.region,
                http_client=cast(HTTPClient | None, config.transport),
            )

    async def _prepare_call[I: SerializeableShape, O: DeserializeableShape](
        self,
        input: I,
        operation: APIOperation[I, O],
        default_plugins: list[Plugin],
        plugins: list[Plugin] | None,
    ) -> tuple[RequestPipeline[Any, Any], ClientCall[I, O]]:
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )
        config = await self._ensure_setup()
        if default_plugins or plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(config)
            for plugin in default_plugins:
                plugin(config)
            if plugins:
                for plugin in plugins:
                    plugin(config)
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )
        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )
        return self._build_call(
            input, operation, config=config, retry_strategy=retry_strategy
        )

    async def invoke_endpoint_with_bidirectional_stream(
        self,
        input: InvokeEndpointWithBidirectionalStreamInput,
        plugins: list[Plugin] | None = None,
    ) -> DuplexEventStream[
        RequestStreamEvent,
        ResponseStreamEvent,
        InvokeEndpointWithBidirectionalStreamOutput,
    ]:
        """
        Invokes a model endpoint with bidirectional streaming capabilities. This
        operation establishes a persistent connection that allows you to send
        multiple requests and receive streaming responses from the model in
        real-time.

        Bidirectional streaming is useful for interactive applications such as
        chatbots, real-time translation, or any scenario where you need to
        maintain a conversation-like interaction with the model. The connection
        remains open, allowing you to send additional input and receive
        responses without establishing a new connection for each request.

        For an overview of Amazon SageMaker AI, see [How It
        Works](https://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works.html).

        Amazon SageMaker AI strips all POST headers except those supported by
        the API. Amazon SageMaker AI might add additional headers. You should
        not rely on the behavior of headers outside those enumerated in the
        request syntax.

        Calls to `InvokeEndpointWithBidirectionalStream` are authenticated by
        using Amazon Web Services Signature Version 4. For information, see
        [Authenticating Requests (Amazon Web Services Signature Version
        4)](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html)
        in the *Amazon S3 API Reference*.

        The bidirectional stream maintains the connection until either the
        client closes it or the model indicates completion. Each request and
        response in the stream is sent as an event with optional headers for
        data type and completion state.

        Note:
            Endpoints are scoped to an individual account, and are not public. The
            URL does not contain the account ID, but Amazon SageMaker AI determines
            the account ID from the authentication token that is supplied by the
            caller.

        Args:
            input:
                An instance of `InvokeEndpointWithBidirectionalStreamInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            A `DuplexEventStream` for bidirectional streaming.
        """
        pipeline, call = await self._prepare_call(
            input, INVOKE_ENDPOINT_WITH_BIDIRECTIONAL_STREAM, [], plugins
        )
        return await pipeline.duplex_stream(
            call,
            RequestStreamEvent,
            ResponseStreamEvent,
            _ResponseStreamEventDeserializer().deserialize,
        )
