# Code generated by smithy-python-codegen DO NOT EDIT.

from types import MappingProxyType

from smithy_core.prelude import UNIT
from smithy_core.schemas import Schema
from smithy_core.shapes import ShapeID, ShapeType
from smithy_core.traits import Trait


ACCOUNT = Schema(id=ShapeID("com.amazonaws.sns#account"), shape_type=ShapeType.STRING)

ACTION = Schema(id=ShapeID("com.amazonaws.sns#action"), shape_type=ShapeType.STRING)

ACTIONS_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ActionsList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": ACTION}},
)

DELEGATE = Schema(id=ShapeID("com.amazonaws.sns#delegate"), shape_type=ShapeType.STRING)

DELEGATES_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.sns#DelegatesList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": DELEGATE}},
)

LABEL = Schema(id=ShapeID("com.amazonaws.sns#label"), shape_type=ShapeType.STRING)

TOPIC_ARN = Schema(
    id=ShapeID("com.amazonaws.sns#topicARN"), shape_type=ShapeType.STRING
)

ADD_PERMISSION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#AddPermissionInput"),
    members={
        "TopicArn": {
            "target": TOPIC_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Label": {
            "target": LABEL,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "AWSAccountId": {
            "target": DELEGATES_LIST,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "ActionName": {
            "target": ACTIONS_LIST,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

ADD_PERMISSION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#AddPermissionOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

STRING = Schema(id=ShapeID("com.amazonaws.sns#String"), shape_type=ShapeType.STRING)

AUTHORIZATION_ERROR_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#AuthorizationErrorException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=403),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "AuthorizationError", "httpResponseCode": 403}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

INTERNAL_ERROR_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#InternalErrorException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="server"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=500),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType({"code": "InternalError", "httpResponseCode": 500}),
        ),
    ],
    members={"message": {"target": STRING}},
)

INVALID_PARAMETER_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#InvalidParameterException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "InvalidParameter", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

NOT_FOUND_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#NotFoundException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=404),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType({"code": "NotFound", "httpResponseCode": 404}),
        ),
    ],
    members={"message": {"target": STRING}},
)

ADD_PERMISSION = Schema(
    id=ShapeID("com.amazonaws.sns#AddPermission"), shape_type=ShapeType.OPERATION
)

AMAZON_RESOURCE_NAME = Schema(
    id=ShapeID("com.amazonaws.sns#AmazonResourceName"), shape_type=ShapeType.STRING
)

PHONE_NUMBER = Schema(
    id=ShapeID("com.amazonaws.sns#PhoneNumber"),
    shape_type=ShapeType.STRING,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
)

CHECK_IF_PHONE_NUMBER_IS_OPTED_OUT_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#CheckIfPhoneNumberIsOptedOutInput"),
    members={
        "phoneNumber": {
            "target": PHONE_NUMBER,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

BOOLEAN = Schema(
    id=ShapeID("com.amazonaws.sns#boolean"),
    shape_type=ShapeType.BOOLEAN,
    traits=[Trait.new(id=ShapeID("smithy.api#default"), value=False)],
)

CHECK_IF_PHONE_NUMBER_IS_OPTED_OUT_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#CheckIfPhoneNumberIsOptedOutOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#CheckIfPhoneNumberIsOptedOutResponse",
        )
    ],
    members={
        "isOptedOut": {
            "target": BOOLEAN,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=False)],
        }
    },
)

THROTTLED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ThrottledException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=429),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType({"code": "Throttled", "httpResponseCode": 429}),
        ),
    ],
    members={"message": {"target": STRING}},
)

CHECK_IF_PHONE_NUMBER_IS_OPTED_OUT = Schema(
    id=ShapeID("com.amazonaws.sns#CheckIfPhoneNumberIsOptedOut"),
    shape_type=ShapeType.OPERATION,
)

AUTHENTICATE_ON_UNSUBSCRIBE = Schema(
    id=ShapeID("com.amazonaws.sns#authenticateOnUnsubscribe"),
    shape_type=ShapeType.STRING,
)

TOKEN = Schema(id=ShapeID("com.amazonaws.sns#token"), shape_type=ShapeType.STRING)

CONFIRM_SUBSCRIPTION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ConfirmSubscriptionInput"),
    members={
        "TopicArn": {
            "target": TOPIC_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Token": {
            "target": TOKEN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "AuthenticateOnUnsubscribe": {"target": AUTHENTICATE_ON_UNSUBSCRIBE},
    },
)

SUBSCRIPTION_ARN = Schema(
    id=ShapeID("com.amazonaws.sns#subscriptionARN"), shape_type=ShapeType.STRING
)

CONFIRM_SUBSCRIPTION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ConfirmSubscriptionOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#ConfirmSubscriptionResponse",
        )
    ],
    members={"SubscriptionArn": {"target": SUBSCRIPTION_ARN}},
)

FILTER_POLICY_LIMIT_EXCEEDED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#FilterPolicyLimitExceededException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=403),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "FilterPolicyLimitExceeded", "httpResponseCode": 403}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

REPLAY_LIMIT_EXCEEDED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ReplayLimitExceededException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=403),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "ReplayLimitExceeded", "httpResponseCode": 403}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

SUBSCRIPTION_LIMIT_EXCEEDED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SubscriptionLimitExceededException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=403),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "SubscriptionLimitExceeded", "httpResponseCode": 403}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

CONFIRM_SUBSCRIPTION = Schema(
    id=ShapeID("com.amazonaws.sns#ConfirmSubscription"), shape_type=ShapeType.OPERATION
)

MAP_STRING_TO_STRING = Schema.collection(
    id=ShapeID("com.amazonaws.sns#MapStringToString"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": STRING}, "value": {"target": STRING}},
)

CREATE_PLATFORM_APPLICATION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#CreatePlatformApplicationInput"),
    members={
        "Name": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Platform": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Attributes": {
            "target": MAP_STRING_TO_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

CREATE_PLATFORM_APPLICATION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#CreatePlatformApplicationOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#CreatePlatformApplicationResponse",
        )
    ],
    members={"PlatformApplicationArn": {"target": STRING}},
)

CREATE_PLATFORM_APPLICATION = Schema(
    id=ShapeID("com.amazonaws.sns#CreatePlatformApplication"),
    shape_type=ShapeType.OPERATION,
)

CREATE_PLATFORM_ENDPOINT_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#CreatePlatformEndpointInput"),
    members={
        "PlatformApplicationArn": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Token": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "CustomUserData": {"target": STRING},
        "Attributes": {"target": MAP_STRING_TO_STRING},
    },
)

CREATE_PLATFORM_ENDPOINT_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#CreatePlatformEndpointOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#CreateEndpointResponse",
        )
    ],
    members={"EndpointArn": {"target": STRING}},
)

CREATE_PLATFORM_ENDPOINT = Schema(
    id=ShapeID("com.amazonaws.sns#CreatePlatformEndpoint"),
    shape_type=ShapeType.OPERATION,
)

LANGUAGE_CODE_STRING = Schema.collection(
    id=ShapeID("com.amazonaws.sns#LanguageCodeString"),
    shape_type=ShapeType.ENUM,
    members={
        "en_US": {"target": UNIT},
        "en_GB": {"target": UNIT},
        "es_419": {"target": UNIT},
        "es_ES": {"target": UNIT},
        "de_DE": {"target": UNIT},
        "fr_CA": {"target": UNIT},
        "fr_FR": {"target": UNIT},
        "it_IT": {"target": UNIT},
        "jp_JP": {"target": UNIT},
        "pt_BR": {"target": UNIT},
        "kr_KR": {"target": UNIT},
        "zh_CN": {"target": UNIT},
        "zh_TW": {"target": UNIT},
    },
)

PHONE_NUMBER_STRING = Schema(
    id=ShapeID("com.amazonaws.sns#PhoneNumberString"),
    shape_type=ShapeType.STRING,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
)

CREATE_SMS_SANDBOX_PHONE_NUMBER_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#CreateSMSSandboxPhoneNumberInput"),
    members={
        "PhoneNumber": {
            "target": PHONE_NUMBER_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "LanguageCode": {"target": LANGUAGE_CODE_STRING},
    },
)

CREATE_SMS_SANDBOX_PHONE_NUMBER_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#CreateSMSSandboxPhoneNumberOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#CreateSMSSandboxPhoneNumberResult",
        )
    ],
)

OPTED_OUT_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#OptedOutException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType({"code": "OptedOut", "httpResponseCode": 400}),
        ),
    ],
    members={"message": {"target": STRING}},
)

USER_ERROR_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#UserErrorException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType({"code": "UserError", "httpResponseCode": 400}),
        ),
    ],
    members={"message": {"target": STRING}},
)

CREATE_SMS_SANDBOX_PHONE_NUMBER = Schema(
    id=ShapeID("com.amazonaws.sns#CreateSMSSandboxPhoneNumber"),
    shape_type=ShapeType.OPERATION,
)

CONCURRENT_ACCESS_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ConcurrentAccessException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "ConcurrentAccess", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

ATTRIBUTE_NAME = Schema(
    id=ShapeID("com.amazonaws.sns#attributeName"), shape_type=ShapeType.STRING
)

ATTRIBUTE_VALUE = Schema(
    id=ShapeID("com.amazonaws.sns#attributeValue"), shape_type=ShapeType.STRING
)

TOPIC_ATTRIBUTES_MAP = Schema.collection(
    id=ShapeID("com.amazonaws.sns#TopicAttributesMap"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": ATTRIBUTE_NAME}, "value": {"target": ATTRIBUTE_VALUE}},
)

TOPIC_NAME = Schema(
    id=ShapeID("com.amazonaws.sns#topicName"), shape_type=ShapeType.STRING
)

TAG_KEY = Schema(id=ShapeID("com.amazonaws.sns#TagKey"), shape_type=ShapeType.STRING)

TAG_VALUE = Schema(
    id=ShapeID("com.amazonaws.sns#TagValue"), shape_type=ShapeType.STRING
)

TAG = Schema.collection(
    id=ShapeID("com.amazonaws.sns#Tag"),
    members={
        "Key": {
            "target": TAG_KEY,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Value": {
            "target": TAG_VALUE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

TAG_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.sns#TagList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": TAG}},
)

CREATE_TOPIC_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#CreateTopicInput"),
    members={
        "Name": {
            "target": TOPIC_NAME,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Attributes": {"target": TOPIC_ATTRIBUTES_MAP},
        "Tags": {"target": TAG_LIST},
        "DataProtectionPolicy": {"target": ATTRIBUTE_VALUE},
    },
)

CREATE_TOPIC_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#CreateTopicOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#CreateTopicResponse",
        )
    ],
    members={"TopicArn": {"target": TOPIC_ARN}},
)

INVALID_SECURITY_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#InvalidSecurityException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=403),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "InvalidSecurity", "httpResponseCode": 403}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

STALE_TAG_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#StaleTagException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType({"code": "StaleTag", "httpResponseCode": 400}),
        ),
    ],
    members={"message": {"target": STRING}},
)

TAG_LIMIT_EXCEEDED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#TagLimitExceededException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "TagLimitExceeded", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

TAG_POLICY_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#TagPolicyException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType({"code": "TagPolicy", "httpResponseCode": 400}),
        ),
    ],
    members={"message": {"target": STRING}},
)

TOPIC_LIMIT_EXCEEDED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#TopicLimitExceededException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=403),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "TopicLimitExceeded", "httpResponseCode": 403}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

CREATE_TOPIC = Schema(
    id=ShapeID("com.amazonaws.sns#CreateTopic"), shape_type=ShapeType.OPERATION
)

DELETE_ENDPOINT_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#DeleteEndpointInput"),
    members={
        "EndpointArn": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

DELETE_ENDPOINT_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#DeleteEndpointOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

DELETE_ENDPOINT = Schema(
    id=ShapeID("com.amazonaws.sns#DeleteEndpoint"), shape_type=ShapeType.OPERATION
)

DELETE_PLATFORM_APPLICATION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#DeletePlatformApplicationInput"),
    members={
        "PlatformApplicationArn": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

DELETE_PLATFORM_APPLICATION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#DeletePlatformApplicationOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

DELETE_PLATFORM_APPLICATION = Schema(
    id=ShapeID("com.amazonaws.sns#DeletePlatformApplication"),
    shape_type=ShapeType.OPERATION,
)

DELETE_SMS_SANDBOX_PHONE_NUMBER_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#DeleteSMSSandboxPhoneNumberInput"),
    members={
        "PhoneNumber": {
            "target": PHONE_NUMBER_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

DELETE_SMS_SANDBOX_PHONE_NUMBER_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#DeleteSMSSandboxPhoneNumberOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#DeleteSMSSandboxPhoneNumberResult",
        )
    ],
)

RESOURCE_NOT_FOUND_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ResourceNotFoundException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=404),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "ResourceNotFound", "httpResponseCode": 404}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

DELETE_SMS_SANDBOX_PHONE_NUMBER = Schema(
    id=ShapeID("com.amazonaws.sns#DeleteSMSSandboxPhoneNumber"),
    shape_type=ShapeType.OPERATION,
)

DELETE_TOPIC_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#DeleteTopicInput"),
    members={
        "TopicArn": {
            "target": TOPIC_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

DELETE_TOPIC_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#DeleteTopicOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

INVALID_STATE_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#InvalidStateException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType({"code": "InvalidState", "httpResponseCode": 400}),
        ),
    ],
    members={"message": {"target": STRING}},
)

DELETE_TOPIC = Schema(
    id=ShapeID("com.amazonaws.sns#DeleteTopic"), shape_type=ShapeType.OPERATION
)

GET_DATA_PROTECTION_POLICY_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#GetDataProtectionPolicyInput"),
    members={
        "ResourceArn": {
            "target": TOPIC_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

GET_DATA_PROTECTION_POLICY_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#GetDataProtectionPolicyOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#GetDataProtectionPolicyResponse",
        )
    ],
    members={"DataProtectionPolicy": {"target": ATTRIBUTE_VALUE}},
)

GET_DATA_PROTECTION_POLICY = Schema(
    id=ShapeID("com.amazonaws.sns#GetDataProtectionPolicy"),
    shape_type=ShapeType.OPERATION,
)

GET_ENDPOINT_ATTRIBUTES_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#GetEndpointAttributesInput"),
    members={
        "EndpointArn": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

GET_ENDPOINT_ATTRIBUTES_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#GetEndpointAttributesOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#GetEndpointAttributesResponse",
        )
    ],
    members={"Attributes": {"target": MAP_STRING_TO_STRING}},
)

GET_ENDPOINT_ATTRIBUTES = Schema(
    id=ShapeID("com.amazonaws.sns#GetEndpointAttributes"),
    shape_type=ShapeType.OPERATION,
)

GET_PLATFORM_APPLICATION_ATTRIBUTES_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#GetPlatformApplicationAttributesInput"),
    members={
        "PlatformApplicationArn": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

GET_PLATFORM_APPLICATION_ATTRIBUTES_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#GetPlatformApplicationAttributesOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#GetPlatformApplicationAttributesResponse",
        )
    ],
    members={"Attributes": {"target": MAP_STRING_TO_STRING}},
)

GET_PLATFORM_APPLICATION_ATTRIBUTES = Schema(
    id=ShapeID("com.amazonaws.sns#GetPlatformApplicationAttributes"),
    shape_type=ShapeType.OPERATION,
)

LIST_STRING = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListString"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": STRING}},
)

GET_SMS_ATTRIBUTES_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#GetSMSAttributesInput"),
    members={"attributes": {"target": LIST_STRING}},
)

GET_SMS_ATTRIBUTES_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#GetSMSAttributesOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#GetSMSAttributesResponse",
        )
    ],
    members={"attributes": {"target": MAP_STRING_TO_STRING}},
)

GET_SMS_ATTRIBUTES = Schema(
    id=ShapeID("com.amazonaws.sns#GetSMSAttributes"), shape_type=ShapeType.OPERATION
)

GET_SMS_SANDBOX_ACCOUNT_STATUS_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#GetSMSSandboxAccountStatusInput")
)

GET_SMS_SANDBOX_ACCOUNT_STATUS_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#GetSMSSandboxAccountStatusOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#GetSMSSandboxAccountStatusResult",
        )
    ],
    members={
        "IsInSandbox": {
            "target": BOOLEAN,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#default"), value=False),
                Trait.new(id=ShapeID("smithy.api#required")),
            ],
        }
    },
)

GET_SMS_SANDBOX_ACCOUNT_STATUS = Schema(
    id=ShapeID("com.amazonaws.sns#GetSMSSandboxAccountStatus"),
    shape_type=ShapeType.OPERATION,
)

GET_SUBSCRIPTION_ATTRIBUTES_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#GetSubscriptionAttributesInput"),
    members={
        "SubscriptionArn": {
            "target": SUBSCRIPTION_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

SUBSCRIPTION_ATTRIBUTES_MAP = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SubscriptionAttributesMap"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": ATTRIBUTE_NAME}, "value": {"target": ATTRIBUTE_VALUE}},
)

GET_SUBSCRIPTION_ATTRIBUTES_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#GetSubscriptionAttributesOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#GetSubscriptionAttributesResponse",
        )
    ],
    members={"Attributes": {"target": SUBSCRIPTION_ATTRIBUTES_MAP}},
)

GET_SUBSCRIPTION_ATTRIBUTES = Schema(
    id=ShapeID("com.amazonaws.sns#GetSubscriptionAttributes"),
    shape_type=ShapeType.OPERATION,
)

GET_TOPIC_ATTRIBUTES_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#GetTopicAttributesInput"),
    members={
        "TopicArn": {
            "target": TOPIC_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

GET_TOPIC_ATTRIBUTES_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#GetTopicAttributesOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#GetTopicAttributesResponse",
        )
    ],
    members={"Attributes": {"target": TOPIC_ATTRIBUTES_MAP}},
)

GET_TOPIC_ATTRIBUTES = Schema(
    id=ShapeID("com.amazonaws.sns#GetTopicAttributes"), shape_type=ShapeType.OPERATION
)

LIST_ENDPOINTS_BY_PLATFORM_APPLICATION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListEndpointsByPlatformApplicationInput"),
    members={
        "PlatformApplicationArn": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "NextToken": {"target": STRING},
    },
)

ENDPOINT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#Endpoint"),
    members={
        "EndpointArn": {"target": STRING},
        "Attributes": {"target": MAP_STRING_TO_STRING},
    },
)

LIST_OF_ENDPOINTS = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListOfEndpoints"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": ENDPOINT}},
)

LIST_ENDPOINTS_BY_PLATFORM_APPLICATION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListEndpointsByPlatformApplicationOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#ListEndpointsByPlatformApplicationResponse",
        )
    ],
    members={
        "Endpoints": {"target": LIST_OF_ENDPOINTS},
        "NextToken": {"target": STRING},
    },
)

LIST_ENDPOINTS_BY_PLATFORM_APPLICATION = Schema(
    id=ShapeID("com.amazonaws.sns#ListEndpointsByPlatformApplication"),
    shape_type=ShapeType.OPERATION,
)

MAX_ITEMS_LIST_ORIGINATION_NUMBERS = Schema(
    id=ShapeID("com.amazonaws.sns#MaxItemsListOriginationNumbers"),
    shape_type=ShapeType.INTEGER,
)

NEXT_TOKEN = Schema(
    id=ShapeID("com.amazonaws.sns#nextToken"), shape_type=ShapeType.STRING
)

LIST_ORIGINATION_NUMBERS_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListOriginationNumbersInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#ListOriginationNumbersRequest",
        )
    ],
    members={
        "NextToken": {"target": NEXT_TOKEN},
        "MaxResults": {"target": MAX_ITEMS_LIST_ORIGINATION_NUMBERS},
    },
)

TIMESTAMP = Schema(
    id=ShapeID("com.amazonaws.sns#Timestamp"), shape_type=ShapeType.TIMESTAMP
)

ISO2_COUNTRY_CODE = Schema(
    id=ShapeID("com.amazonaws.sns#Iso2CountryCode"), shape_type=ShapeType.STRING
)

NUMBER_CAPABILITY = Schema.collection(
    id=ShapeID("com.amazonaws.sns#NumberCapability"),
    shape_type=ShapeType.ENUM,
    members={
        "SMS": {"target": UNIT},
        "MMS": {"target": UNIT},
        "VOICE": {"target": UNIT},
    },
)

NUMBER_CAPABILITY_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.sns#NumberCapabilityList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": NUMBER_CAPABILITY}},
)

ROUTE_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.sns#RouteType"),
    shape_type=ShapeType.ENUM,
    members={
        "Transactional": {"target": UNIT},
        "Promotional": {"target": UNIT},
        "Premium": {"target": UNIT},
    },
)

PHONE_NUMBER_INFORMATION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#PhoneNumberInformation"),
    members={
        "CreatedAt": {"target": TIMESTAMP},
        "PhoneNumber": {"target": PHONE_NUMBER},
        "Status": {"target": STRING},
        "Iso2CountryCode": {"target": ISO2_COUNTRY_CODE},
        "RouteType": {"target": ROUTE_TYPE},
        "NumberCapabilities": {"target": NUMBER_CAPABILITY_LIST},
    },
)

PHONE_NUMBER_INFORMATION_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.sns#PhoneNumberInformationList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": PHONE_NUMBER_INFORMATION}},
)

LIST_ORIGINATION_NUMBERS_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListOriginationNumbersOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#ListOriginationNumbersResult",
        )
    ],
    members={
        "NextToken": {"target": NEXT_TOKEN},
        "PhoneNumbers": {"target": PHONE_NUMBER_INFORMATION_LIST},
    },
)

VALIDATION_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ValidationException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "ValidationException", "httpResponseCode": 400}
            ),
        ),
    ],
    members={
        "Message": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

LIST_ORIGINATION_NUMBERS = Schema(
    id=ShapeID("com.amazonaws.sns#ListOriginationNumbers"),
    shape_type=ShapeType.OPERATION,
)

LIST_PHONE_NUMBERS_OPTED_OUT_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListPhoneNumbersOptedOutInput"),
    members={"nextToken": {"target": STRING}},
)

PHONE_NUMBER_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.sns#PhoneNumberList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": PHONE_NUMBER}},
)

LIST_PHONE_NUMBERS_OPTED_OUT_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListPhoneNumbersOptedOutOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#ListPhoneNumbersOptedOutResponse",
        )
    ],
    members={
        "phoneNumbers": {"target": PHONE_NUMBER_LIST},
        "nextToken": {"target": STRING},
    },
)

LIST_PHONE_NUMBERS_OPTED_OUT = Schema(
    id=ShapeID("com.amazonaws.sns#ListPhoneNumbersOptedOut"),
    shape_type=ShapeType.OPERATION,
)

LIST_PLATFORM_APPLICATIONS_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListPlatformApplicationsInput"),
    members={"NextToken": {"target": STRING}},
)

PLATFORM_APPLICATION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#PlatformApplication"),
    members={
        "PlatformApplicationArn": {"target": STRING},
        "Attributes": {"target": MAP_STRING_TO_STRING},
    },
)

LIST_OF_PLATFORM_APPLICATIONS = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListOfPlatformApplications"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": PLATFORM_APPLICATION}},
)

LIST_PLATFORM_APPLICATIONS_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListPlatformApplicationsOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#ListPlatformApplicationsResponse",
        )
    ],
    members={
        "PlatformApplications": {"target": LIST_OF_PLATFORM_APPLICATIONS},
        "NextToken": {"target": STRING},
    },
)

LIST_PLATFORM_APPLICATIONS = Schema(
    id=ShapeID("com.amazonaws.sns#ListPlatformApplications"),
    shape_type=ShapeType.OPERATION,
)

MAX_ITEMS = Schema(
    id=ShapeID("com.amazonaws.sns#MaxItems"), shape_type=ShapeType.INTEGER
)

LIST_SMS_SANDBOX_PHONE_NUMBERS_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListSMSSandboxPhoneNumbersInput"),
    members={"NextToken": {"target": NEXT_TOKEN}, "MaxResults": {"target": MAX_ITEMS}},
)

SMS_SANDBOX_PHONE_NUMBER_VERIFICATION_STATUS = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SMSSandboxPhoneNumberVerificationStatus"),
    shape_type=ShapeType.ENUM,
    members={"Pending": {"target": UNIT}, "Verified": {"target": UNIT}},
)

SMS_SANDBOX_PHONE_NUMBER = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SMSSandboxPhoneNumber"),
    members={
        "PhoneNumber": {"target": PHONE_NUMBER_STRING},
        "Status": {"target": SMS_SANDBOX_PHONE_NUMBER_VERIFICATION_STATUS},
    },
)

SMS_SANDBOX_PHONE_NUMBER_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SMSSandboxPhoneNumberList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": SMS_SANDBOX_PHONE_NUMBER}},
)

LIST_SMS_SANDBOX_PHONE_NUMBERS_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListSMSSandboxPhoneNumbersOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#ListSMSSandboxPhoneNumbersResult",
        )
    ],
    members={
        "PhoneNumbers": {
            "target": SMS_SANDBOX_PHONE_NUMBER_LIST,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "NextToken": {"target": STRING},
    },
)

LIST_SMS_SANDBOX_PHONE_NUMBERS = Schema(
    id=ShapeID("com.amazonaws.sns#ListSMSSandboxPhoneNumbers"),
    shape_type=ShapeType.OPERATION,
)

LIST_SUBSCRIPTIONS_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListSubscriptionsInput"),
    members={"NextToken": {"target": NEXT_TOKEN}},
)

ENDPOINT2 = Schema(
    id=ShapeID("com.amazonaws.sns#Endpoint2"), shape_type=ShapeType.STRING
)

PROTOCOL = Schema(id=ShapeID("com.amazonaws.sns#protocol"), shape_type=ShapeType.STRING)

SUBSCRIPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#Subscription"),
    members={
        "SubscriptionArn": {"target": SUBSCRIPTION_ARN},
        "Owner": {"target": ACCOUNT},
        "Protocol": {"target": PROTOCOL},
        "Endpoint": {"target": ENDPOINT2},
        "TopicArn": {"target": TOPIC_ARN},
    },
)

SUBSCRIPTIONS_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SubscriptionsList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": SUBSCRIPTION}},
)

LIST_SUBSCRIPTIONS_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListSubscriptionsOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#ListSubscriptionsResponse",
        )
    ],
    members={
        "Subscriptions": {"target": SUBSCRIPTIONS_LIST},
        "NextToken": {"target": NEXT_TOKEN},
    },
)

LIST_SUBSCRIPTIONS = Schema(
    id=ShapeID("com.amazonaws.sns#ListSubscriptions"), shape_type=ShapeType.OPERATION
)

LIST_SUBSCRIPTIONS_BY_TOPIC_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListSubscriptionsByTopicInput"),
    members={
        "TopicArn": {
            "target": TOPIC_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "NextToken": {"target": NEXT_TOKEN},
    },
)

LIST_SUBSCRIPTIONS_BY_TOPIC_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListSubscriptionsByTopicOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#ListSubscriptionsByTopicResponse",
        )
    ],
    members={
        "Subscriptions": {"target": SUBSCRIPTIONS_LIST},
        "NextToken": {"target": NEXT_TOKEN},
    },
)

LIST_SUBSCRIPTIONS_BY_TOPIC = Schema(
    id=ShapeID("com.amazonaws.sns#ListSubscriptionsByTopic"),
    shape_type=ShapeType.OPERATION,
)

LIST_TAGS_FOR_RESOURCE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListTagsForResourceInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#ListTagsForResourceRequest",
        )
    ],
    members={
        "ResourceArn": {
            "target": AMAZON_RESOURCE_NAME,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

LIST_TAGS_FOR_RESOURCE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListTagsForResourceOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#ListTagsForResourceResponse",
        )
    ],
    members={"Tags": {"target": TAG_LIST}},
)

LIST_TAGS_FOR_RESOURCE = Schema(
    id=ShapeID("com.amazonaws.sns#ListTagsForResource"), shape_type=ShapeType.OPERATION
)

LIST_TOPICS_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListTopicsInput"),
    members={"NextToken": {"target": NEXT_TOKEN}},
)

TOPIC = Schema.collection(
    id=ShapeID("com.amazonaws.sns#Topic"), members={"TopicArn": {"target": TOPIC_ARN}}
)

TOPICS_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.sns#TopicsList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": TOPIC}},
)

LIST_TOPICS_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#ListTopicsOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#ListTopicsResponse",
        )
    ],
    members={"Topics": {"target": TOPICS_LIST}, "NextToken": {"target": NEXT_TOKEN}},
)

LIST_TOPICS = Schema(
    id=ShapeID("com.amazonaws.sns#ListTopics"), shape_type=ShapeType.OPERATION
)

OPT_IN_PHONE_NUMBER_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#OptInPhoneNumberInput"),
    members={
        "phoneNumber": {
            "target": PHONE_NUMBER,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

OPT_IN_PHONE_NUMBER_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#OptInPhoneNumberOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#OptInPhoneNumberResponse",
        )
    ],
)

OPT_IN_PHONE_NUMBER = Schema(
    id=ShapeID("com.amazonaws.sns#OptInPhoneNumber"), shape_type=ShapeType.OPERATION
)

ENDPOINT_DISABLED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#EndpointDisabledException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "EndpointDisabled", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

INVALID_PARAMETER_VALUE_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#InvalidParameterValueException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "ParameterValueInvalid", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

KMS_ACCESS_DENIED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#KMSAccessDeniedException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "KMSAccessDenied", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

KMS_DISABLED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#KMSDisabledException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType({"code": "KMSDisabled", "httpResponseCode": 400}),
        ),
    ],
    members={"message": {"target": STRING}},
)

KMS_INVALID_STATE_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#KMSInvalidStateException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "KMSInvalidState", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

KMS_NOT_FOUND_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#KMSNotFoundException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType({"code": "KMSNotFound", "httpResponseCode": 400}),
        ),
    ],
    members={"message": {"target": STRING}},
)

KMS_OPT_IN_REQUIRED = Schema.collection(
    id=ShapeID("com.amazonaws.sns#KMSOptInRequired"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=403),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "KMSOptInRequired", "httpResponseCode": 403}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

KMS_THROTTLING_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#KMSThrottlingException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType({"code": "KMSThrottling", "httpResponseCode": 400}),
        ),
    ],
    members={"message": {"target": STRING}},
)

PLATFORM_APPLICATION_DISABLED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#PlatformApplicationDisabledException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "PlatformApplicationDisabled", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

MESSAGE = Schema(id=ShapeID("com.amazonaws.sns#message"), shape_type=ShapeType.STRING)

BINARY = Schema(id=ShapeID("com.amazonaws.sns#Binary"), shape_type=ShapeType.BLOB)

MESSAGE_ATTRIBUTE_VALUE = Schema.collection(
    id=ShapeID("com.amazonaws.sns#MessageAttributeValue"),
    members={
        "DataType": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "StringValue": {"target": STRING},
        "BinaryValue": {"target": BINARY},
    },
)

MESSAGE_ATTRIBUTE_MAP = Schema.collection(
    id=ShapeID("com.amazonaws.sns#MessageAttributeMap"),
    shape_type=ShapeType.MAP,
    members={
        "key": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="Name")],
        },
        "value": {
            "target": MESSAGE_ATTRIBUTE_VALUE,
            "traits": [Trait.new(id=ShapeID("smithy.api#xmlName"), value="Value")],
        },
    },
)

MESSAGE_STRUCTURE = Schema(
    id=ShapeID("com.amazonaws.sns#messageStructure"), shape_type=ShapeType.STRING
)

SUBJECT = Schema(id=ShapeID("com.amazonaws.sns#subject"), shape_type=ShapeType.STRING)

PUBLISH_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#PublishInput"),
    members={
        "TopicArn": {"target": TOPIC_ARN},
        "TargetArn": {"target": STRING},
        "PhoneNumber": {"target": PHONE_NUMBER},
        "Message": {
            "target": MESSAGE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Subject": {"target": SUBJECT},
        "MessageStructure": {"target": MESSAGE_STRUCTURE},
        "MessageAttributes": {"target": MESSAGE_ATTRIBUTE_MAP},
        "MessageDeduplicationId": {"target": STRING},
        "MessageGroupId": {"target": STRING},
    },
)

MESSAGE_ID = Schema(
    id=ShapeID("com.amazonaws.sns#messageId"), shape_type=ShapeType.STRING
)

PUBLISH_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#PublishOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#PublishResponse",
        )
    ],
    members={"MessageId": {"target": MESSAGE_ID}, "SequenceNumber": {"target": STRING}},
)

PUBLISH = Schema(
    id=ShapeID("com.amazonaws.sns#Publish"), shape_type=ShapeType.OPERATION
)

BATCH_ENTRY_IDS_NOT_DISTINCT_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#BatchEntryIdsNotDistinctException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "BatchEntryIdsNotDistinct", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

BATCH_REQUEST_TOO_LONG_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#BatchRequestTooLongException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "BatchRequestTooLong", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

EMPTY_BATCH_REQUEST_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#EmptyBatchRequestException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "EmptyBatchRequest", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

INVALID_BATCH_ENTRY_ID_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#InvalidBatchEntryIdException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "InvalidBatchEntryId", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

PUBLISH_BATCH_REQUEST_ENTRY = Schema.collection(
    id=ShapeID("com.amazonaws.sns#PublishBatchRequestEntry"),
    members={
        "Id": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Message": {
            "target": MESSAGE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Subject": {"target": SUBJECT},
        "MessageStructure": {"target": MESSAGE_STRUCTURE},
        "MessageAttributes": {"target": MESSAGE_ATTRIBUTE_MAP},
        "MessageDeduplicationId": {"target": STRING},
        "MessageGroupId": {"target": STRING},
    },
)

PUBLISH_BATCH_REQUEST_ENTRY_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.sns#PublishBatchRequestEntryList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": PUBLISH_BATCH_REQUEST_ENTRY}},
)

PUBLISH_BATCH_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#PublishBatchInput"),
    members={
        "TopicArn": {
            "target": TOPIC_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "PublishBatchRequestEntries": {
            "target": PUBLISH_BATCH_REQUEST_ENTRY_LIST,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

BATCH_RESULT_ERROR_ENTRY = Schema.collection(
    id=ShapeID("com.amazonaws.sns#BatchResultErrorEntry"),
    members={
        "Id": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Code": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Message": {"target": STRING},
        "SenderFault": {
            "target": BOOLEAN,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#default"), value=False),
                Trait.new(id=ShapeID("smithy.api#required")),
            ],
        },
    },
)

BATCH_RESULT_ERROR_ENTRY_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.sns#BatchResultErrorEntryList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": BATCH_RESULT_ERROR_ENTRY}},
)

PUBLISH_BATCH_RESULT_ENTRY = Schema.collection(
    id=ShapeID("com.amazonaws.sns#PublishBatchResultEntry"),
    members={
        "Id": {"target": STRING},
        "MessageId": {"target": MESSAGE_ID},
        "SequenceNumber": {"target": STRING},
    },
)

PUBLISH_BATCH_RESULT_ENTRY_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.sns#PublishBatchResultEntryList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": PUBLISH_BATCH_RESULT_ENTRY}},
)

PUBLISH_BATCH_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#PublishBatchOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#PublishBatchResponse",
        )
    ],
    members={
        "Successful": {"target": PUBLISH_BATCH_RESULT_ENTRY_LIST},
        "Failed": {"target": BATCH_RESULT_ERROR_ENTRY_LIST},
    },
)

TOO_MANY_ENTRIES_IN_BATCH_REQUEST_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#TooManyEntriesInBatchRequestException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
        Trait.new(
            id=ShapeID("aws.protocols#awsQueryError"),
            value=MappingProxyType(
                {"code": "TooManyEntriesInBatchRequest", "httpResponseCode": 400}
            ),
        ),
    ],
    members={"message": {"target": STRING}},
)

PUBLISH_BATCH = Schema(
    id=ShapeID("com.amazonaws.sns#PublishBatch"), shape_type=ShapeType.OPERATION
)

PUT_DATA_PROTECTION_POLICY_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#PutDataProtectionPolicyInput"),
    members={
        "ResourceArn": {
            "target": TOPIC_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "DataProtectionPolicy": {
            "target": ATTRIBUTE_VALUE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

PUT_DATA_PROTECTION_POLICY_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#PutDataProtectionPolicyOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

PUT_DATA_PROTECTION_POLICY = Schema(
    id=ShapeID("com.amazonaws.sns#PutDataProtectionPolicy"),
    shape_type=ShapeType.OPERATION,
)

REMOVE_PERMISSION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#RemovePermissionInput"),
    members={
        "TopicArn": {
            "target": TOPIC_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Label": {
            "target": LABEL,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

REMOVE_PERMISSION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#RemovePermissionOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

REMOVE_PERMISSION = Schema(
    id=ShapeID("com.amazonaws.sns#RemovePermission"), shape_type=ShapeType.OPERATION
)

SET_ENDPOINT_ATTRIBUTES_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SetEndpointAttributesInput"),
    members={
        "EndpointArn": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Attributes": {
            "target": MAP_STRING_TO_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

SET_ENDPOINT_ATTRIBUTES_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SetEndpointAttributesOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

SET_ENDPOINT_ATTRIBUTES = Schema(
    id=ShapeID("com.amazonaws.sns#SetEndpointAttributes"),
    shape_type=ShapeType.OPERATION,
)

SET_PLATFORM_APPLICATION_ATTRIBUTES_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SetPlatformApplicationAttributesInput"),
    members={
        "PlatformApplicationArn": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Attributes": {
            "target": MAP_STRING_TO_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

SET_PLATFORM_APPLICATION_ATTRIBUTES_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SetPlatformApplicationAttributesOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

SET_PLATFORM_APPLICATION_ATTRIBUTES = Schema(
    id=ShapeID("com.amazonaws.sns#SetPlatformApplicationAttributes"),
    shape_type=ShapeType.OPERATION,
)

SET_SMS_ATTRIBUTES_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SetSMSAttributesInput"),
    members={
        "attributes": {
            "target": MAP_STRING_TO_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

SET_SMS_ATTRIBUTES_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SetSMSAttributesOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#SetSMSAttributesResponse",
        )
    ],
)

SET_SMS_ATTRIBUTES = Schema(
    id=ShapeID("com.amazonaws.sns#SetSMSAttributes"), shape_type=ShapeType.OPERATION
)

SET_SUBSCRIPTION_ATTRIBUTES_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SetSubscriptionAttributesInput"),
    members={
        "SubscriptionArn": {
            "target": SUBSCRIPTION_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "AttributeName": {
            "target": ATTRIBUTE_NAME,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "AttributeValue": {"target": ATTRIBUTE_VALUE},
    },
)

SET_SUBSCRIPTION_ATTRIBUTES_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SetSubscriptionAttributesOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

SET_SUBSCRIPTION_ATTRIBUTES = Schema(
    id=ShapeID("com.amazonaws.sns#SetSubscriptionAttributes"),
    shape_type=ShapeType.OPERATION,
)

SET_TOPIC_ATTRIBUTES_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SetTopicAttributesInput"),
    members={
        "TopicArn": {
            "target": TOPIC_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "AttributeName": {
            "target": ATTRIBUTE_NAME,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "AttributeValue": {"target": ATTRIBUTE_VALUE},
    },
)

SET_TOPIC_ATTRIBUTES_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SetTopicAttributesOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

SET_TOPIC_ATTRIBUTES = Schema(
    id=ShapeID("com.amazonaws.sns#SetTopicAttributes"), shape_type=ShapeType.OPERATION
)

SUBSCRIBE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SubscribeInput"),
    members={
        "TopicArn": {
            "target": TOPIC_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Protocol": {
            "target": PROTOCOL,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Endpoint": {"target": ENDPOINT2},
        "Attributes": {"target": SUBSCRIPTION_ATTRIBUTES_MAP},
        "ReturnSubscriptionArn": {
            "target": BOOLEAN,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=False)],
        },
    },
)

SUBSCRIBE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#SubscribeOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#SubscribeResponse",
        )
    ],
    members={"SubscriptionArn": {"target": SUBSCRIPTION_ARN}},
)

SUBSCRIBE = Schema(
    id=ShapeID("com.amazonaws.sns#Subscribe"), shape_type=ShapeType.OPERATION
)

TAG_RESOURCE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#TagResourceInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#TagResourceRequest",
        )
    ],
    members={
        "ResourceArn": {
            "target": AMAZON_RESOURCE_NAME,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Tags": {
            "target": TAG_LIST,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

TAG_RESOURCE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#TagResourceOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#TagResourceResponse",
        )
    ],
)

TAG_RESOURCE = Schema(
    id=ShapeID("com.amazonaws.sns#TagResource"), shape_type=ShapeType.OPERATION
)

UNSUBSCRIBE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#UnsubscribeInput"),
    members={
        "SubscriptionArn": {
            "target": SUBSCRIPTION_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

UNSUBSCRIBE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#UnsubscribeOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

UNSUBSCRIBE = Schema(
    id=ShapeID("com.amazonaws.sns#Unsubscribe"), shape_type=ShapeType.OPERATION
)

TAG_KEY_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.sns#TagKeyList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": TAG_KEY}},
)

UNTAG_RESOURCE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#UntagResourceInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#UntagResourceRequest",
        )
    ],
    members={
        "ResourceArn": {
            "target": AMAZON_RESOURCE_NAME,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "TagKeys": {
            "target": TAG_KEY_LIST,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

UNTAG_RESOURCE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#UntagResourceOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#UntagResourceResponse",
        )
    ],
)

UNTAG_RESOURCE = Schema(
    id=ShapeID("com.amazonaws.sns#UntagResource"), shape_type=ShapeType.OPERATION
)

VERIFICATION_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.sns#VerificationException"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="client")],
    members={
        "Message": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "Status": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

OTP_CODE = Schema(id=ShapeID("com.amazonaws.sns#OTPCode"), shape_type=ShapeType.STRING)

VERIFY_SMS_SANDBOX_PHONE_NUMBER_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#VerifySMSSandboxPhoneNumberInput"),
    members={
        "PhoneNumber": {
            "target": PHONE_NUMBER_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "OneTimePassword": {
            "target": OTP_CODE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

VERIFY_SMS_SANDBOX_PHONE_NUMBER_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.sns#VerifySMSSandboxPhoneNumberOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.sns#VerifySMSSandboxPhoneNumberResult",
        )
    ],
)

VERIFY_SMS_SANDBOX_PHONE_NUMBER = Schema(
    id=ShapeID("com.amazonaws.sns#VerifySMSSandboxPhoneNumber"),
    shape_type=ShapeType.OPERATION,
)

AMAZON_SIMPLE_NOTIFICATION_SERVICE = Schema(
    id=ShapeID("com.amazonaws.sns#AmazonSimpleNotificationService"),
    shape_type=ShapeType.SERVICE,
    traits=[
        Trait.new(
            id=ShapeID("aws.auth#sigv4"), value=MappingProxyType({"name": "sns"})
        ),
        Trait.new(id=ShapeID("aws.protocols#awsQuery")),
        Trait.new(
            id=ShapeID("smithy.rules#endpointBdd"),
            value=MappingProxyType(
                {
                    "version": "1.1",
                    "parameters": MappingProxyType(
                        {
                            "Region": MappingProxyType(
                                {
                                    "builtIn": "AWS::Region",
                                    "required": False,
                                    "documentation": "The AWS region used to dispatch the request.",
                                    "type": "string",
                                }
                            ),
                            "UseDualStack": MappingProxyType(
                                {
                                    "builtIn": "AWS::UseDualStack",
                                    "required": True,
                                    "default": False,
                                    "documentation": "When true, use the dual-stack endpoint. If the configured endpoint does not support dual-stack, dispatching the request MAY return an error.",
                                    "type": "boolean",
                                }
                            ),
                            "UseFIPS": MappingProxyType(
                                {
                                    "builtIn": "AWS::UseFIPS",
                                    "required": True,
                                    "default": False,
                                    "documentation": "When true, send this request to the FIPS-compliant regional endpoint. If the configured endpoint does not have a FIPS compliant endpoint, dispatching the request will return an error.",
                                    "type": "boolean",
                                }
                            ),
                            "Endpoint": MappingProxyType(
                                {
                                    "builtIn": "SDK::Endpoint",
                                    "required": False,
                                    "documentation": "Override the endpoint used to send this request",
                                    "type": "string",
                                }
                            ),
                        }
                    ),
                    "conditions": (
                        MappingProxyType(
                            {
                                "fn": "isSet",
                                "argv": (MappingProxyType({"ref": "Endpoint"}),),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "isSet",
                                "argv": (MappingProxyType({"ref": "Region"}),),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "aws.partition",
                                "argv": (MappingProxyType({"ref": "Region"}),),
                                "assign": "PartitionResult",
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (MappingProxyType({"ref": "UseFIPS"}), True),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (
                                    MappingProxyType({"ref": "UseDualStack"}),
                                    True,
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "supportsDualStack",
                                            ),
                                        }
                                    ),
                                    True,
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "supportsFIPS",
                                            ),
                                        }
                                    ),
                                    True,
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "stringEquals",
                                "argv": (
                                    MappingProxyType({"ref": "Region"}),
                                    "us-gov-east-1",
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "stringEquals",
                                "argv": (
                                    MappingProxyType({"ref": "Region"}),
                                    "us-gov-west-1",
                                ),
                            }
                        ),
                    ),
                    "results": (
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: FIPS and custom endpoint are not supported",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: Dualstack and custom endpoint are not supported",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": MappingProxyType({"ref": "Endpoint"}),
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://sns-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "FIPS and DualStack are enabled, but this partition does not support one or both",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://sns.us-gov-east-1.amazonaws.com",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://sns.us-gov-west-1.amazonaws.com",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://sns-fips.{Region}.{PartitionResult#dnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "FIPS is enabled but this partition does not support FIPS",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://sns.{Region}.{PartitionResult#dualStackDnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "DualStack is enabled but this partition does not support DualStack",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://sns.{Region}.{PartitionResult#dnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: Missing Region",
                                "type": "error",
                            }
                        ),
                    ),
                    "root": 2,
                    "nodeCount": 15,
                    "nodes": "/////wAAAAH/////AAAAAAAAAA4AAAADAAAAAQAAAAQF9eENAAAAAgAAAAUF9eENAAAAAwAAAAgAAAAGAAAABAAAAAcF9eEMAAAABQX14QoF9eELAAAABAAAAAwAAAAJAAAABgAAAAoF9eEJAAAABwX14QYAAAALAAAACAX14QcF9eEIAAAABQAAAA0F9eEFAAAABgX14QQF9eEFAAAAAwX14QEAAAAPAAAABAX14QIF9eED",
                }
            ),
        ),
        Trait.new(
            id=ShapeID("aws.api#service"),
            value=MappingProxyType(
                {
                    "sdkId": "SNS",
                    "arnNamespace": "sns",
                    "cloudFormationName": "SNS",
                    "cloudTrailEventSource": "sns.amazonaws.com",
                    "endpointPrefix": "sns",
                }
            ),
        ),
        Trait.new(
            id=ShapeID("smithy.api#xmlNamespace"),
            value=MappingProxyType({"uri": "http://sns.amazonaws.com/doc/2010-03-31/"}),
        ),
    ],
)
