# Code generated by smithy-python-codegen DO NOT EDIT.

from types import MappingProxyType

from smithy_core.prelude import INTEGER, STRING, TIMESTAMP, UNIT
from smithy_core.schemas import Schema
from smithy_core.shapes import ShapeID, ShapeType
from smithy_core.traits import Trait


ACCESS_DENIED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#AccessDeniedException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=401),
    ],
    members={"message": {"target": STRING}},
)

DOMAIN_ID = Schema(
    id=ShapeID("com.amazonaws.connecthealth#DomainId"), shape_type=ShapeType.STRING
)

SUBSCRIPTION_ID = Schema(
    id=ShapeID("com.amazonaws.connecthealth#SubscriptionId"),
    shape_type=ShapeType.STRING,
)

ACTIVATE_SUBSCRIPTION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ActivateSubscriptionInput"),
    members={
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "subscriptionId": {
            "target": SUBSCRIPTION_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
    },
)

SUBSCRIPTION_ARN = Schema(
    id=ShapeID("com.amazonaws.connecthealth#SubscriptionArn"),
    shape_type=ShapeType.STRING,
)

SUBSCRIPTION_STATUS = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#SubscriptionStatus"),
    shape_type=ShapeType.ENUM,
    members={
        "ACTIVE": {"target": UNIT},
        "INACTIVE": {"target": UNIT},
        "DELETED": {"target": UNIT},
    },
)

SUBSCRIPTION_DESCRIPTION = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#SubscriptionDescription"),
    members={
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "subscriptionId": {
            "target": SUBSCRIPTION_ID,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "arn": {
            "target": SUBSCRIPTION_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "status": {
            "target": SUBSCRIPTION_STATUS,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "createdAt": {
            "target": TIMESTAMP,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "lastUpdatedAt": {
            "target": TIMESTAMP,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "activatedAt": {"target": TIMESTAMP},
        "deactivatedAt": {"target": TIMESTAMP},
    },
)

ACTIVATE_SUBSCRIPTION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ActivateSubscriptionOutput"),
    members={"subscription": {"target": SUBSCRIPTION_DESCRIPTION}},
)

INTERNAL_SERVER_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#InternalServerException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="server"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=500),
    ],
    members={"message": {"target": STRING}},
)

RESOURCE_NOT_FOUND_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ResourceNotFoundException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=404),
    ],
    members={"message": {"target": STRING}},
)

VALIDATION_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ValidationException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
    ],
    members={"message": {"target": STRING}},
)

ACTIVATE_SUBSCRIPTION = Schema(
    id=ShapeID("com.amazonaws.connecthealth#ActivateSubscription"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {
                    "method": "POST",
                    "uri": "/domains/{domainId}/subscriptions/{subscriptionId}/activate",
                    "code": 200,
                }
            ),
        )
    ],
)

ERROR_MESSAGE = Schema(
    id=ShapeID("com.amazonaws.connecthealth#ErrorMessage"), shape_type=ShapeType.STRING
)

URI = Schema(id=ShapeID("com.amazonaws.connecthealth#Uri"), shape_type=ShapeType.STRING)

POST_STREAM_ARTIFACT_GENERATION_STATUS = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#PostStreamArtifactGenerationStatus"),
    shape_type=ShapeType.ENUM,
    members={
        "IN_PROGRESS": {"target": UNIT},
        "FAILED": {"target": UNIT},
        "COMPLETED": {"target": UNIT},
    },
)

ARTIFACT_DETAILS = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ArtifactDetails"),
    members={
        "outputLocation": {"target": URI},
        "status": {"target": POST_STREAM_ARTIFACT_GENERATION_STATUS},
        "failureReason": {"target": ERROR_MESSAGE},
    },
)

AUDIO_CHUNK = Schema(
    id=ShapeID("com.amazonaws.connecthealth#AudioChunk"), shape_type=ShapeType.BLOB
)

AUDIO_OFFSET = Schema(
    id=ShapeID("com.amazonaws.connecthealth#AudioOffset"), shape_type=ShapeType.DOUBLE
)

CLINICAL_NOTE_GENERATION_RESULT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ClinicalNoteGenerationResult"),
    members={
        "noteResult": {"target": ARTIFACT_DETAILS},
        "transcriptResult": {"target": ARTIFACT_DETAILS},
        "afterVisitSummaryResult": {"target": ARTIFACT_DETAILS},
    },
)

SENSITIVE_SECTION_HEADER_STRING = Schema(
    id=ShapeID("com.amazonaws.connecthealth#SensitiveSectionHeaderString"),
    shape_type=ShapeType.STRING,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
)

SENSITIVE_MARKDOWN_STRING = Schema(
    id=ShapeID("com.amazonaws.connecthealth#SensitiveMarkdownString"),
    shape_type=ShapeType.STRING,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
)

TEMPLATE_SECTION_INSTRUCTION = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#TemplateSectionInstruction"),
    members={
        "sectionHeader": {
            "target": SENSITIVE_SECTION_HEADER_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "sectionInstruction": {
            "target": SENSITIVE_MARKDOWN_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

TEMPLATE_INSTRUCTIONS = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#TemplateInstructions"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": TEMPLATE_SECTION_INSTRUCTION}},
)

CUSTOM_TEMPLATE_BASE = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#CustomTemplateBase"),
    shape_type=ShapeType.ENUM,
    members={
        "HISTORY_AND_PHYSICAL": {"target": UNIT},
        "GIRPP": {"target": UNIT},
        "DAP": {"target": UNIT},
        "SIRP": {"target": UNIT},
        "BIRP": {"target": UNIT},
        "BEHAVIORAL_SOAP": {"target": UNIT},
    },
)

CUSTOM_TEMPLATE = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#CustomTemplate"),
    members={
        "templateType": {
            "target": CUSTOM_TEMPLATE_BASE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "templateInstructions": {
            "target": TEMPLATE_INSTRUCTIONS,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

MANAGED_NOTE_TEMPLATE = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ManagedNoteTemplate"),
    shape_type=ShapeType.ENUM,
    members={
        "HISTORY_AND_PHYSICAL": {"target": UNIT},
        "GIRPP": {"target": UNIT},
        "DAP": {"target": UNIT},
        "SIRP": {"target": UNIT},
        "BIRP": {"target": UNIT},
        "BEHAVIORAL_SOAP": {"target": UNIT},
        "PHYSICAL_SOAP": {"target": UNIT},
    },
)

MANAGED_TEMPLATE = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ManagedTemplate"),
    members={
        "templateType": {
            "target": MANAGED_NOTE_TEMPLATE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

NOTE_TEMPLATE_SETTINGS = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#NoteTemplateSettings"),
    shape_type=ShapeType.UNION,
    members={
        "managedTemplate": {"target": MANAGED_TEMPLATE},
        "customTemplate": {"target": CUSTOM_TEMPLATE},
    },
)

CLINICAL_NOTE_GENERATION_SETTINGS = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ClinicalNoteGenerationSettings"),
    members={
        "noteTemplateSettings": {
            "target": NOTE_TEMPLATE_SETTINGS,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

CUSTOM_TEMPLATE_RESPONSE = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#CustomTemplateResponse"),
    members={"templateType": {"target": CUSTOM_TEMPLATE_BASE}},
)

MANAGED_TEMPLATE_RESPONSE = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ManagedTemplateResponse"),
    members={"templateType": {"target": MANAGED_NOTE_TEMPLATE}},
)

NOTE_TEMPLATE_SETTINGS_RESPONSE = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#NoteTemplateSettingsResponse"),
    shape_type=ShapeType.UNION,
    members={
        "managedTemplate": {"target": MANAGED_TEMPLATE_RESPONSE},
        "customTemplate": {"target": CUSTOM_TEMPLATE_RESPONSE},
    },
)

CLINICAL_NOTE_GENERATION_SETTINGS_RESPONSE = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ClinicalNoteGenerationSettingsResponse"),
    members={"noteTemplateSettings": {"target": NOTE_TEMPLATE_SETTINGS_RESPONSE}},
)

CONFLICT_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ConflictException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=409),
    ],
    members={"message": {"target": STRING}},
)

KMS_KEY_ARN = Schema(
    id=ShapeID("com.amazonaws.connecthealth#KmsKeyArn"), shape_type=ShapeType.STRING
)

DOMAIN_NAME = Schema(
    id=ShapeID("com.amazonaws.connecthealth#DomainName"), shape_type=ShapeType.STRING
)

TAG_KEY = Schema(
    id=ShapeID("com.amazonaws.connecthealth#TagKey"), shape_type=ShapeType.STRING
)

TAG_VALUE = Schema(
    id=ShapeID("com.amazonaws.connecthealth#TagValue"), shape_type=ShapeType.STRING
)

TAG_MAP = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#TagMap"),
    shape_type=ShapeType.MAP,
    members={"key": {"target": TAG_KEY}, "value": {"target": TAG_VALUE}},
)

CREATE_WEB_APP_CONFIGURATION = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#CreateWebAppConfiguration"),
    members={
        "ehrRole": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "idcInstanceId": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "idcRegion": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

CREATE_DOMAIN_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#CreateDomainInput"),
    members={
        "name": {
            "target": DOMAIN_NAME,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "kmsKeyArn": {"target": KMS_KEY_ARN},
        "webAppSetupConfiguration": {"target": CREATE_WEB_APP_CONFIGURATION},
        "tags": {"target": TAG_MAP},
    },
)

DOMAIN_ARN = Schema(
    id=ShapeID("com.amazonaws.connecthealth#DomainArn"), shape_type=ShapeType.STRING
)

ENCRYPTION_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#EncryptionType"),
    shape_type=ShapeType.ENUM,
    members={
        "AWS_OWNED_KEY": {"target": UNIT},
        "CUSTOMER_MANAGED_KEY": {"target": UNIT},
    },
)

ENCRYPTION_CONTEXT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#EncryptionContext"),
    members={
        "encryptionType": {
            "target": ENCRYPTION_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "kmsKeyArn": {"target": KMS_KEY_ARN},
    },
)

DOMAIN_STATUS = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#DomainStatus"),
    shape_type=ShapeType.ENUM,
    members={
        "ACTIVE": {"target": UNIT},
        "DELETING": {"target": UNIT},
        "DELETED": {"target": UNIT},
    },
)

WEB_APP_CONFIGURATION = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#WebAppConfiguration"),
    members={
        "ehrRole": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "idcApplicationId": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "idcRegion": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

WEB_APP_URL = Schema(
    id=ShapeID("com.amazonaws.connecthealth#WebAppUrl"), shape_type=ShapeType.STRING
)

CREATE_DOMAIN_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#CreateDomainOutput"),
    members={
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "arn": {
            "target": DOMAIN_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "name": {
            "target": DOMAIN_NAME,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "kmsKeyArn": {"target": KMS_KEY_ARN},
        "encryptionContext": {"target": ENCRYPTION_CONTEXT},
        "status": {
            "target": DOMAIN_STATUS,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "webAppUrl": {"target": WEB_APP_URL},
        "webAppConfiguration": {"target": WEB_APP_CONFIGURATION},
        "createdAt": {
            "target": TIMESTAMP,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

SERVICE_QUOTA_EXCEEDED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ServiceQuotaExceededException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=402),
    ],
    members={"message": {"target": STRING}},
)

CREATE_DOMAIN = Schema(
    id=ShapeID("com.amazonaws.connecthealth#CreateDomain"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType({"method": "POST", "uri": "/domain", "code": 201}),
        )
    ],
)

CREATE_SUBSCRIPTION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#CreateSubscriptionInput"),
    members={
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        }
    },
)

CREATE_SUBSCRIPTION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#CreateSubscriptionOutput"),
    members={
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "subscriptionId": {
            "target": SUBSCRIPTION_ID,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "arn": {
            "target": SUBSCRIPTION_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "status": {
            "target": SUBSCRIPTION_STATUS,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "createdAt": {
            "target": TIMESTAMP,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "lastUpdatedAt": {
            "target": TIMESTAMP,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "activatedAt": {"target": TIMESTAMP},
        "deactivatedAt": {"target": TIMESTAMP},
    },
)

CREATE_SUBSCRIPTION = Schema(
    id=ShapeID("com.amazonaws.connecthealth#CreateSubscription"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {
                    "method": "POST",
                    "uri": "/domains/{domainId}/subscriptions",
                    "code": 201,
                }
            ),
        )
    ],
)

DEACTIVATE_SUBSCRIPTION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#DeactivateSubscriptionInput"),
    members={
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "subscriptionId": {
            "target": SUBSCRIPTION_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
    },
)

DEACTIVATE_SUBSCRIPTION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#DeactivateSubscriptionOutput"),
    members={"subscription": {"target": SUBSCRIPTION_DESCRIPTION}},
)

DEACTIVATE_SUBSCRIPTION = Schema(
    id=ShapeID("com.amazonaws.connecthealth#DeactivateSubscription"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {
                    "method": "POST",
                    "uri": "/domains/{domainId}/subscriptions/{subscriptionId}/deactivate",
                    "code": 200,
                }
            ),
        )
    ],
)

DELETE_DOMAIN_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#DeleteDomainInput"),
    members={
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        }
    },
)

DELETE_DOMAIN_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#DeleteDomainOutput"),
    members={
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "arn": {
            "target": DOMAIN_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "status": {
            "target": DOMAIN_STATUS,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

DELETE_DOMAIN = Schema(
    id=ShapeID("com.amazonaws.connecthealth#DeleteDomain"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType({"method": "DELETE", "uri": "/domain/{domainId}"}),
        )
    ],
)

GET_DOMAIN_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#GetDomainInput"),
    members={
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        }
    },
)

GET_DOMAIN_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#GetDomainOutput"),
    members={
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "arn": {
            "target": DOMAIN_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "name": {
            "target": DOMAIN_NAME,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "kmsKeyArn": {"target": KMS_KEY_ARN},
        "encryptionContext": {"target": ENCRYPTION_CONTEXT},
        "status": {
            "target": DOMAIN_STATUS,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "webAppUrl": {"target": WEB_APP_URL},
        "webAppConfiguration": {"target": WEB_APP_CONFIGURATION},
        "createdAt": {
            "target": TIMESTAMP,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "tags": {"target": TAG_MAP},
    },
)

GET_DOMAIN = Schema(
    id=ShapeID("com.amazonaws.connecthealth#GetDomain"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType({"method": "GET", "uri": "/domain/{domainId}"}),
        )
    ],
)

SCRIBE_SESSION_ID = Schema(
    id=ShapeID("com.amazonaws.connecthealth#ScribeSessionId"),
    shape_type=ShapeType.STRING,
)

GET_MEDICAL_SCRIBE_LISTENING_SESSION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#GetMedicalScribeListeningSessionInput"),
    members={
        "sessionId": {
            "target": SCRIBE_SESSION_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "subscriptionId": {
            "target": SUBSCRIPTION_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
    },
)

MEDICAL_SCRIBE_CHANNEL_ID = Schema(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeChannelId"),
    shape_type=ShapeType.INTEGER,
)

MEDICAL_SCRIBE_PARTICIPANT_ROLE = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeParticipantRole"),
    shape_type=ShapeType.ENUM,
    members={"PATIENT": {"target": UNIT}, "CLINICIAN": {"target": UNIT}},
)

MEDICAL_SCRIBE_CHANNEL_DEFINITION = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeChannelDefinition"),
    members={
        "channelId": {
            "target": MEDICAL_SCRIBE_CHANNEL_ID,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "participantRole": {
            "target": MEDICAL_SCRIBE_PARTICIPANT_ROLE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

MEDICAL_SCRIBE_CHANNEL_DEFINITIONS = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeChannelDefinitions"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": MEDICAL_SCRIBE_CHANNEL_DEFINITION}},
)

NON_NULL_BOOLEAN = Schema(
    id=ShapeID("com.amazonaws.connecthealth#NonNullBoolean"),
    shape_type=ShapeType.BOOLEAN,
)

MEDICAL_SCRIBE_LANGUAGE_CODE = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeLanguageCode"),
    shape_type=ShapeType.ENUM,
    members={"EN_US": {"target": UNIT}, "MULTI": {"target": UNIT}},
)

MEDICAL_SCRIBE_MEDIA_ENCODING = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeMediaEncoding"),
    shape_type=ShapeType.ENUM,
    members={"PCM": {"target": UNIT}, "FLAC": {"target": UNIT}},
)

MEDICAL_SCRIBE_MEDIA_SAMPLE_RATE_HERTZ = Schema(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeMediaSampleRateHertz"),
    shape_type=ShapeType.INTEGER,
)

MEDICAL_SCRIBE_POST_STREAM_ACTIONS_RESULT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribePostStreamActionsResult"),
    members={
        "clinicalNoteGenerationResult": {"target": CLINICAL_NOTE_GENERATION_RESULT}
    },
)

S3_URI = Schema(
    id=ShapeID("com.amazonaws.connecthealth#S3Uri"), shape_type=ShapeType.STRING
)

MEDICAL_SCRIBE_POST_STREAM_ACTION_SETTINGS_RESPONSE = Schema.collection(
    id=ShapeID(
        "com.amazonaws.connecthealth#MedicalScribePostStreamActionSettingsResponse"
    ),
    members={
        "outputS3Uri": {
            "target": S3_URI,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "clinicalNoteGenerationSettings": {
            "target": CLINICAL_NOTE_GENERATION_SETTINGS_RESPONSE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

MEDICAL_SCRIBE_STREAM_STATUS = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeStreamStatus"),
    shape_type=ShapeType.ENUM,
    members={
        "IN_PROGRESS": {"target": UNIT},
        "PAUSED": {"target": UNIT},
        "FAILED": {"target": UNIT},
        "COMPLETED": {"target": UNIT},
    },
)

MEDICAL_SCRIBE_LISTENING_SESSION_DETAILS = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeListeningSessionDetails"),
    members={
        "sessionId": {"target": SCRIBE_SESSION_ID},
        "domainId": {"target": DOMAIN_ID},
        "subscriptionId": {"target": SUBSCRIPTION_ID},
        "languageCode": {"target": MEDICAL_SCRIBE_LANGUAGE_CODE},
        "mediaSampleRateHertz": {"target": MEDICAL_SCRIBE_MEDIA_SAMPLE_RATE_HERTZ},
        "mediaEncoding": {"target": MEDICAL_SCRIBE_MEDIA_ENCODING},
        "channelDefinitions": {"target": MEDICAL_SCRIBE_CHANNEL_DEFINITIONS},
        "postStreamActionSettings": {
            "target": MEDICAL_SCRIBE_POST_STREAM_ACTION_SETTINGS_RESPONSE
        },
        "postStreamActionResult": {"target": MEDICAL_SCRIBE_POST_STREAM_ACTIONS_RESULT},
        "encounterContextProvided": {"target": NON_NULL_BOOLEAN},
        "streamStatus": {"target": MEDICAL_SCRIBE_STREAM_STATUS},
        "streamCreationTime": {"target": TIMESTAMP},
        "streamEndTime": {"target": TIMESTAMP},
    },
)

GET_MEDICAL_SCRIBE_LISTENING_SESSION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#GetMedicalScribeListeningSessionOutput"),
    members={
        "medicalScribeListeningSessionDetails": {
            "target": MEDICAL_SCRIBE_LISTENING_SESSION_DETAILS
        }
    },
)

THROTTLING_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ThrottlingException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=429),
    ],
    members={"message": {"target": STRING}},
)

GET_MEDICAL_SCRIBE_LISTENING_SESSION = Schema(
    id=ShapeID("com.amazonaws.connecthealth#GetMedicalScribeListeningSession"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#endpoint"),
            value=MappingProxyType({"hostPrefix": "streaming."}),
        ),
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {
                    "uri": "/medical-scribe-stream/domain/{domainId}/subscription/{subscriptionId}/session/{sessionId}",
                    "method": "GET",
                }
            ),
        ),
    ],
)

JOB_ID = Schema(
    id=ShapeID("com.amazonaws.connecthealth#JobId"), shape_type=ShapeType.STRING
)

GET_PATIENT_INSIGHTS_JOB_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#GetPatientInsightsJobInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.connecthealth#GetPatientInsightsJobRequest",
        )
    ],
    members={
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "jobId": {
            "target": JOB_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
    },
)

SENSITIVE_NON_EMPTY_STRING = Schema(
    id=ShapeID("com.amazonaws.connecthealth#SensitiveNonEmptyString"),
    shape_type=ShapeType.STRING,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
)

PATIENT_INSIGHTS_ENCOUNTER_CONTEXT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#PatientInsightsEncounterContext"),
    members={
        "encounterReason": {
            "target": SENSITIVE_NON_EMPTY_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

NON_EMPTY_STRING = Schema(
    id=ShapeID("com.amazonaws.connecthealth#NonEmptyString"),
    shape_type=ShapeType.STRING,
)

FHIR_SERVER = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#FHIRServer"),
    members={
        "fhirEndpoint": {
            "target": NON_EMPTY_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "oauthToken": {"target": SENSITIVE_NON_EMPTY_STRING},
    },
)

S3_SOURCE = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#S3Source"),
    members={
        "uri": {
            "target": S3_URI,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

S3_SOURCES = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#S3Sources"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": S3_SOURCE}},
)

INPUT_DATA_CONFIG = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#InputDataConfig"),
    members={
        "fhirServer": {"target": FHIR_SERVER},
        "s3Sources": {"target": S3_SOURCES},
    },
)

INSIGHTS_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#InsightsType"),
    shape_type=ShapeType.ENUM,
    members={"PRE_VISIT": {"target": UNIT}},
)

INSIGHTS_CONTEXT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#InsightsContext"),
    members={
        "insightsType": {
            "target": INSIGHTS_TYPE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

INSIGHTS_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#InsightsOutput"),
    members={
        "uri": {
            "target": S3_URI,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

JOB_ARN = Schema(
    id=ShapeID("com.amazonaws.connecthealth#JobArn"), shape_type=ShapeType.STRING
)

JOB_STATUS = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#JobStatus"),
    shape_type=ShapeType.ENUM,
    members={
        "SUBMITTED": {"target": UNIT},
        "IN_PROGRESS": {"target": UNIT},
        "FAILED": {"target": UNIT},
        "SUCCEEDED": {"target": UNIT},
    },
)

OUTPUT_DATA_CONFIG = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#OutputDataConfig"),
    members={
        "s3OutputPath": {
            "target": S3_URI,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

SENSITIVE_ISO_DATE_STRING = Schema(
    id=ShapeID("com.amazonaws.connecthealth#SensitiveIsoDateString"),
    shape_type=ShapeType.STRING,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
)

PRONOUNS = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#Pronouns"),
    shape_type=ShapeType.ENUM,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
    members={
        "HE_HIM": {"target": UNIT},
        "SHE_HER": {"target": UNIT},
        "THEY_THEM": {"target": UNIT},
    },
)

PATIENT_INSIGHTS_PATIENT_CONTEXT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#PatientInsightsPatientContext"),
    members={
        "patientId": {
            "target": SENSITIVE_NON_EMPTY_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "dateOfBirth": {"target": SENSITIVE_ISO_DATE_STRING},
        "pronouns": {"target": PRONOUNS},
    },
)

PROVIDER_ROLE = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ProviderRole"),
    shape_type=ShapeType.ENUM,
    members={"CLINICIAN": {"target": UNIT}},
)

SPECIALTY = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#Specialty"),
    shape_type=ShapeType.ENUM,
    members={"PRIMARY_CARE": {"target": UNIT}},
)

USER_CONTEXT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#UserContext"),
    members={
        "role": {
            "target": PROVIDER_ROLE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "userId": {
            "target": SENSITIVE_NON_EMPTY_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "specialty": {"target": SPECIALTY},
    },
)

GET_PATIENT_INSIGHTS_JOB_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#GetPatientInsightsJobOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.connecthealth#GetPatientInsightsJobResponse",
        )
    ],
    members={
        "jobId": {
            "target": JOB_ID,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "jobArn": {
            "target": JOB_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "jobStatus": {
            "target": JOB_STATUS,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "creationTime": {
            "target": TIMESTAMP,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#timestampFormat"), value="date-time")
            ],
        },
        "updatedTime": {
            "target": TIMESTAMP,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#timestampFormat"), value="date-time")
            ],
        },
        "insightsOutput": {"target": INSIGHTS_OUTPUT},
        "statusDetails": {"target": NON_EMPTY_STRING},
        "patientContext": {
            "target": PATIENT_INSIGHTS_PATIENT_CONTEXT,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "insightsContext": {
            "target": INSIGHTS_CONTEXT,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "encounterContext": {
            "target": PATIENT_INSIGHTS_ENCOUNTER_CONTEXT,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "userContext": {
            "target": USER_CONTEXT,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "inputDataConfig": {
            "target": INPUT_DATA_CONFIG,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "outputDataConfig": {
            "target": OUTPUT_DATA_CONFIG,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

GET_PATIENT_INSIGHTS_JOB = Schema(
    id=ShapeID("com.amazonaws.connecthealth#GetPatientInsightsJob"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#endpoint"),
            value=MappingProxyType({"hostPrefix": "runtime."}),
        ),
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {
                    "code": 200,
                    "method": "GET",
                    "uri": "/domain/{domainId}/patient-insights-job/{jobId}",
                }
            ),
        ),
    ],
)

GET_SUBSCRIPTION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#GetSubscriptionInput"),
    members={
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "subscriptionId": {
            "target": SUBSCRIPTION_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
    },
)

GET_SUBSCRIPTION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#GetSubscriptionOutput"),
    members={"subscription": {"target": SUBSCRIPTION_DESCRIPTION}},
)

GET_SUBSCRIPTION = Schema(
    id=ShapeID("com.amazonaws.connecthealth#GetSubscription"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {
                    "method": "GET",
                    "uri": "/domains/{domainId}/subscriptions/{subscriptionId}",
                }
            ),
        )
    ],
)

LIST_DOMAINS_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ListDomainsInput"),
    members={
        "status": {
            "target": DOMAIN_STATUS,
            "traits": [Trait.new(id=ShapeID("smithy.api#httpQuery"), value="status")],
        },
        "maxResults": {
            "target": INTEGER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#httpQuery"), value="maxResults")
            ],
        },
        "nextToken": {
            "target": STRING,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#httpQuery"), value="nextToken")
            ],
        },
    },
)

DOMAIN_SUMMARY = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#DomainSummary"),
    members={
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "arn": {
            "target": DOMAIN_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "name": {
            "target": DOMAIN_NAME,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "status": {
            "target": DOMAIN_STATUS,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "createdAt": {
            "target": TIMESTAMP,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

DOMAIN_SUMMARY_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#DomainSummaryList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": DOMAIN_SUMMARY}},
)

LIST_DOMAINS_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ListDomainsOutput"),
    members={
        "domains": {
            "target": DOMAIN_SUMMARY_LIST,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "nextToken": {"target": STRING},
    },
)

LIST_DOMAINS = Schema(
    id=ShapeID("com.amazonaws.connecthealth#ListDomains"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType({"method": "GET", "uri": "/domain"}),
        )
    ],
)

LIST_SUBSCRIPTIONS_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ListSubscriptionsInput"),
    members={
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "maxResults": {
            "target": INTEGER,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#httpQuery"), value="maxResults")
            ],
        },
        "nextToken": {
            "target": STRING,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#httpQuery"), value="nextToken")
            ],
        },
    },
)

SUBSCRIPTION_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#SubscriptionList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": SUBSCRIPTION_DESCRIPTION}},
)

LIST_SUBSCRIPTIONS_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ListSubscriptionsOutput"),
    members={
        "subscriptions": {
            "target": SUBSCRIPTION_LIST,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "nextToken": {"target": STRING},
    },
)

LIST_SUBSCRIPTIONS = Schema(
    id=ShapeID("com.amazonaws.connecthealth#ListSubscriptions"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {"method": "GET", "uri": "/domains/{domainId}/subscriptions"}
            ),
        )
    ],
)

LIST_TAGS_FOR_RESOURCE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ListTagsForResourceInput"),
    members={
        "resourceArn": {
            "target": STRING,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        }
    },
)

LIST_TAGS_FOR_RESOURCE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#ListTagsForResourceOutput"),
    members={"tags": {"target": TAG_MAP}},
)

LIST_TAGS_FOR_RESOURCE = Schema(
    id=ShapeID("com.amazonaws.connecthealth#ListTagsForResource"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {"uri": "/tags/{resourceArn}", "method": "GET", "code": 200}
            ),
        )
    ],
)

MEDICAL_SCRIBE_AUDIO_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeAudioEvent"),
    members={
        "audioChunk": {
            "target": AUDIO_CHUNK,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

MEDICAL_SCRIBE_BINARY_AUDIO_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeBinaryAudioEvent"),
    members={
        "audioChunk": {
            "target": AUDIO_CHUNK,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#eventPayload")),
                Trait.new(id=ShapeID("smithy.api#required")),
            ],
        }
    },
)

ENCOUNTER_CONTEXT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#EncounterContext"),
    members={"unstructuredContext": {"target": SENSITIVE_MARKDOWN_STRING}},
)

MEDICAL_SCRIBE_POST_STREAM_ACTION_SETTINGS = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribePostStreamActionSettings"),
    members={
        "outputS3Uri": {
            "target": S3_URI,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "clinicalNoteGenerationSettings": {
            "target": CLINICAL_NOTE_GENERATION_SETTINGS,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

MEDICAL_SCRIBE_CONFIGURATION_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeConfigurationEvent"),
    members={
        "postStreamActionSettings": {
            "target": MEDICAL_SCRIBE_POST_STREAM_ACTION_SETTINGS,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "channelDefinitions": {"target": MEDICAL_SCRIBE_CHANNEL_DEFINITIONS},
        "encounterContext": {"target": ENCOUNTER_CONTEXT},
    },
)

MEDICAL_SCRIBE_SESSION_CONTROL_EVENT_TYPE = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeSessionControlEventType"),
    shape_type=ShapeType.ENUM,
    members={"END_OF_SESSION": {"target": UNIT}},
)

MEDICAL_SCRIBE_SESSION_CONTROL_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeSessionControlEvent"),
    members={"type": {"target": MEDICAL_SCRIBE_SESSION_CONTROL_EVENT_TYPE}},
)

MEDICAL_SCRIBE_INPUT_STREAM = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeInputStream"),
    shape_type=ShapeType.UNION,
    traits=[Trait.new(id=ShapeID("smithy.api#streaming"))],
    members={
        "audioEvent": {"target": MEDICAL_SCRIBE_AUDIO_EVENT},
        "binaryAudioEvent": {"target": MEDICAL_SCRIBE_BINARY_AUDIO_EVENT},
        "sessionControlEvent": {"target": MEDICAL_SCRIBE_SESSION_CONTROL_EVENT},
        "configurationEvent": {"target": MEDICAL_SCRIBE_CONFIGURATION_EVENT},
    },
)

START_MEDICAL_SCRIBE_LISTENING_SESSION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#StartMedicalScribeListeningSessionInput"),
    members={
        "sessionId": {
            "target": SCRIBE_SESSION_ID,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amzn-medscribe-session-id",
                ),
                Trait.new(id=ShapeID("smithy.api#required")),
            ],
        },
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amzn-medscribe-domain-id",
                ),
                Trait.new(id=ShapeID("smithy.api#required")),
            ],
        },
        "subscriptionId": {
            "target": SUBSCRIPTION_ID,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amzn-medscribe-subscription-id",
                ),
                Trait.new(id=ShapeID("smithy.api#required")),
            ],
        },
        "languageCode": {
            "target": MEDICAL_SCRIBE_LANGUAGE_CODE,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amzn-medscribe-language-code",
                ),
                Trait.new(id=ShapeID("smithy.api#required")),
            ],
        },
        "mediaSampleRateHertz": {
            "target": MEDICAL_SCRIBE_MEDIA_SAMPLE_RATE_HERTZ,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amzn-medscribe-sample-rate",
                ),
                Trait.new(id=ShapeID("smithy.api#required")),
            ],
        },
        "mediaEncoding": {
            "target": MEDICAL_SCRIBE_MEDIA_ENCODING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amzn-medscribe-media-encoding",
                ),
                Trait.new(id=ShapeID("smithy.api#required")),
            ],
        },
        "inputStream": {
            "target": MEDICAL_SCRIBE_INPUT_STREAM,
            "traits": [Trait.new(id=ShapeID("smithy.api#httpPayload"))],
        },
    },
)

REQUEST_ID = Schema(
    id=ShapeID("com.amazonaws.connecthealth#RequestId"), shape_type=ShapeType.STRING
)

MEDICAL_SCRIBE_TRANSCRIPT_SEGMENT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeTranscriptSegment"),
    members={
        "segmentId": {"target": STRING},
        "audioBeginOffset": {"target": AUDIO_OFFSET},
        "audioEndOffset": {"target": AUDIO_OFFSET},
        "isPartial": {"target": NON_NULL_BOOLEAN},
        "channelId": {"target": STRING},
        "content": {"target": STRING},
    },
)

MEDICAL_SCRIBE_TRANSCRIPT_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeTranscriptEvent"),
    members={"transcriptSegment": {"target": MEDICAL_SCRIBE_TRANSCRIPT_SEGMENT}},
)

MEDICAL_SCRIBE_OUTPUT_STREAM = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#MedicalScribeOutputStream"),
    shape_type=ShapeType.UNION,
    traits=[Trait.new(id=ShapeID("smithy.api#streaming"))],
    members={
        "transcriptEvent": {"target": MEDICAL_SCRIBE_TRANSCRIPT_EVENT},
        "internalFailureException": {"target": INTERNAL_SERVER_EXCEPTION},
        "validationException": {"target": VALIDATION_EXCEPTION},
    },
)

START_MEDICAL_SCRIBE_LISTENING_SESSION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#StartMedicalScribeListeningSessionOutput"),
    members={
        "sessionId": {
            "target": SCRIBE_SESSION_ID,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amzn-medscribe-session-id",
                )
            ],
        },
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amzn-medscribe-domain-id",
                )
            ],
        },
        "subscriptionId": {
            "target": SUBSCRIPTION_ID,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amzn-medscribe-subscription-id",
                )
            ],
        },
        "requestId": {
            "target": REQUEST_ID,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"), value="x-amzn-request-id"
                )
            ],
        },
        "languageCode": {
            "target": MEDICAL_SCRIBE_LANGUAGE_CODE,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amzn-medscribe-language-code",
                )
            ],
        },
        "mediaSampleRateHertz": {
            "target": MEDICAL_SCRIBE_MEDIA_SAMPLE_RATE_HERTZ,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amzn-medscribe-sample-rate",
                )
            ],
        },
        "mediaEncoding": {
            "target": MEDICAL_SCRIBE_MEDIA_ENCODING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="x-amzn-medscribe-media-encoding",
                )
            ],
        },
        "responseStream": {
            "target": MEDICAL_SCRIBE_OUTPUT_STREAM,
            "traits": [Trait.new(id=ShapeID("smithy.api#httpPayload"))],
        },
    },
)

START_MEDICAL_SCRIBE_LISTENING_SESSION = Schema(
    id=ShapeID("com.amazonaws.connecthealth#StartMedicalScribeListeningSession"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#endpoint"),
            value=MappingProxyType({"hostPrefix": "streaming."}),
        ),
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {"uri": "/medical-scribe-stream/", "method": "POST"}
            ),
        ),
    ],
)

START_PATIENT_INSIGHTS_JOB_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#StartPatientInsightsJobInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.connecthealth#StartPatientInsightsJobRequest",
        )
    ],
    members={
        "domainId": {
            "target": DOMAIN_ID,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "patientContext": {
            "target": PATIENT_INSIGHTS_PATIENT_CONTEXT,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "insightsContext": {
            "target": INSIGHTS_CONTEXT,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "encounterContext": {
            "target": PATIENT_INSIGHTS_ENCOUNTER_CONTEXT,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "userContext": {
            "target": USER_CONTEXT,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "inputDataConfig": {
            "target": INPUT_DATA_CONFIG,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "outputDataConfig": {
            "target": OUTPUT_DATA_CONFIG,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "clientToken": {
            "target": NON_EMPTY_STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#idempotencyToken"))],
        },
    },
)

START_PATIENT_INSIGHTS_JOB_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#StartPatientInsightsJobOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.connecthealth#StartPatientInsightsJobResponse",
        )
    ],
    members={
        "jobArn": {
            "target": JOB_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "jobId": {
            "target": JOB_ID,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "creationTime": {
            "target": TIMESTAMP,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#timestampFormat"), value="date-time")
            ],
        },
    },
)

START_PATIENT_INSIGHTS_JOB = Schema(
    id=ShapeID("com.amazonaws.connecthealth#StartPatientInsightsJob"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#endpoint"),
            value=MappingProxyType({"hostPrefix": "runtime."}),
        ),
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {
                    "code": 200,
                    "method": "POST",
                    "uri": "/domain/{domainId}/patient-insights-job",
                }
            ),
        ),
    ],
)

TAG_RESOURCE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#TagResourceInput"),
    members={
        "resourceArn": {
            "target": STRING,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "tags": {
            "target": TAG_MAP,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

TAG_RESOURCE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#TagResourceOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

TAG_RESOURCE = Schema(
    id=ShapeID("com.amazonaws.connecthealth#TagResource"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {"uri": "/tags/{resourceArn}", "method": "POST", "code": 204}
            ),
        )
    ],
)

TAG_KEY_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#TagKeyList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": TAG_KEY}},
)

UNTAG_RESOURCE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#UntagResourceInput"),
    members={
        "resourceArn": {
            "target": STRING,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "tagKeys": {
            "target": TAG_KEY_LIST,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpQuery"), value="tagKeys"),
            ],
        },
    },
)

UNTAG_RESOURCE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.connecthealth#UntagResourceOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"), value="smithy.api#Unit"
        )
    ],
)

UNTAG_RESOURCE = Schema(
    id=ShapeID("com.amazonaws.connecthealth#UntagResource"),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {"uri": "/tags/{resourceArn}", "method": "DELETE", "code": 204}
            ),
        )
    ],
)

CONNECT_HEALTH = Schema(
    id=ShapeID("com.amazonaws.connecthealth#ConnectHealth"),
    shape_type=ShapeType.SERVICE,
    traits=[
        Trait.new(
            id=ShapeID("aws.auth#sigv4"),
            value=MappingProxyType({"name": "health-agent"}),
        ),
        Trait.new(
            id=ShapeID("smithy.rules#endpointBdd"),
            value=MappingProxyType(
                {
                    "version": "1.1",
                    "parameters": MappingProxyType(
                        {
                            "UseFIPS": MappingProxyType(
                                {
                                    "builtIn": "AWS::UseFIPS",
                                    "required": True,
                                    "default": False,
                                    "documentation": "When true, send this request to the FIPS-compliant regional endpoint. If the configured endpoint does not have a FIPS compliant endpoint, dispatching the request will return an error.",
                                    "type": "boolean",
                                }
                            ),
                            "Endpoint": MappingProxyType(
                                {
                                    "builtIn": "SDK::Endpoint",
                                    "required": False,
                                    "documentation": "Override the endpoint used to send this request",
                                    "type": "string",
                                }
                            ),
                            "Region": MappingProxyType(
                                {
                                    "builtIn": "AWS::Region",
                                    "required": False,
                                    "documentation": "The AWS region used to dispatch the request.",
                                    "type": "string",
                                }
                            ),
                        }
                    ),
                    "conditions": (
                        MappingProxyType(
                            {
                                "fn": "isSet",
                                "argv": (MappingProxyType({"ref": "Endpoint"}),),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "isSet",
                                "argv": (MappingProxyType({"ref": "Region"}),),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "aws.partition",
                                "argv": (MappingProxyType({"ref": "Region"}),),
                                "assign": "PartitionResult",
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (MappingProxyType({"ref": "UseFIPS"}), True),
                            }
                        ),
                    ),
                    "results": (
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: FIPS and custom endpoint are not supported",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": MappingProxyType({"ref": "Endpoint"}),
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://health-agent-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://health-agent.{Region}.{PartitionResult#dualStackDnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: Missing Region",
                                "type": "error",
                            }
                        ),
                    ),
                    "root": 2,
                    "nodeCount": 6,
                    "nodes": "/////wAAAAH/////AAAAAAAAAAYAAAADAAAAAQAAAAQF9eEFAAAAAgAAAAUF9eEFAAAAAwX14QMF9eEEAAAAAwX14QEF9eEC",
                }
            ),
        ),
        Trait.new(
            id=ShapeID("aws.api#service"),
            value=MappingProxyType(
                {
                    "sdkId": "ConnectHealth",
                    "arnNamespace": "health-agent",
                    "endpointPrefix": "health-agent",
                    "cloudTrailEventSource": "health-agent.amazonaws.com",
                }
            ),
        ),
        Trait.new(
            id=ShapeID("aws.protocols#restJson1"),
            value=MappingProxyType(
                {"http": ("h2", "http/1.1"), "eventStreamHttp": ("h2",)}
            ),
        ),
        Trait.new(
            id=ShapeID("smithy.api#cors"),
            value=MappingProxyType(
                {
                    "origin": "*",
                    "additionalAllowedHeaders": (
                        "*",
                        "content-type",
                        "content-length",
                        "authorization",
                        "x-amz-date",
                        "x-amz-security-token",
                        "x-amz-content-sha256",
                        "x-amz-user-agent",
                        "x-api-key",
                    ),
                    "additionalExposedHeaders": (
                        "x-amzn-errortype",
                        "x-amzn-requestid",
                        "x-amzn-trace-id",
                        "Access-Control-Allow-Origin",
                    ),
                    "maxAge": 86400,
                }
            ),
        ),
    ],
)
