# Code generated by smithy-python-codegen DO NOT EDIT.

from copy import deepcopy
import logging
from typing import Any, cast

from smithy_aws_core.config import ConfigSource
from smithy_aws_core.identity import AWSCredentialsIdentity
from smithy_aws_core.identity.chain import IdentityChain
from smithy_core.aio.client import AsyncClient, ClientCall, RequestPipeline
from smithy_core.deserializers import DeserializeableShape
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.schemas import APIOperation
from smithy_core.serializers import SerializeableShape
from smithy_http.aio.interfaces import HTTPClient
from smithy_http.plugins import user_agent_plugin

from .config import AsyncBedrockDataAutomationConfig, Plugin
from .models import (
    COPY_BLUEPRINT_STAGE,
    CREATE_BLUEPRINT,
    CREATE_BLUEPRINT_VERSION,
    CREATE_DATA_AUTOMATION_LIBRARY,
    CREATE_DATA_AUTOMATION_PROJECT,
    CopyBlueprintStageInput,
    CopyBlueprintStageOutput,
    CreateBlueprintInput,
    CreateBlueprintOutput,
    CreateBlueprintVersionInput,
    CreateBlueprintVersionOutput,
    CreateDataAutomationLibraryInput,
    CreateDataAutomationLibraryOutput,
    CreateDataAutomationProjectInput,
    CreateDataAutomationProjectOutput,
    DELETE_BLUEPRINT,
    DELETE_DATA_AUTOMATION_LIBRARY,
    DELETE_DATA_AUTOMATION_PROJECT,
    DeleteBlueprintInput,
    DeleteBlueprintOutput,
    DeleteDataAutomationLibraryInput,
    DeleteDataAutomationLibraryOutput,
    DeleteDataAutomationProjectInput,
    DeleteDataAutomationProjectOutput,
    GET_BLUEPRINT,
    GET_BLUEPRINT_OPTIMIZATION_STATUS,
    GET_DATA_AUTOMATION_LIBRARY,
    GET_DATA_AUTOMATION_LIBRARY_ENTITY,
    GET_DATA_AUTOMATION_LIBRARY_INGESTION_JOB,
    GET_DATA_AUTOMATION_PROJECT,
    GetBlueprintInput,
    GetBlueprintOptimizationStatusInput,
    GetBlueprintOptimizationStatusOutput,
    GetBlueprintOutput,
    GetDataAutomationLibraryEntityInput,
    GetDataAutomationLibraryEntityOutput,
    GetDataAutomationLibraryIngestionJobInput,
    GetDataAutomationLibraryIngestionJobOutput,
    GetDataAutomationLibraryInput,
    GetDataAutomationLibraryOutput,
    GetDataAutomationProjectInput,
    GetDataAutomationProjectOutput,
    INVOKE_BLUEPRINT_OPTIMIZATION_ASYNC,
    INVOKE_DATA_AUTOMATION_LIBRARY_INGESTION_JOB,
    InvokeBlueprintOptimizationAsyncInput,
    InvokeBlueprintOptimizationAsyncOutput,
    InvokeDataAutomationLibraryIngestionJobInput,
    InvokeDataAutomationLibraryIngestionJobOutput,
    LIST_BLUEPRINTS,
    LIST_DATA_AUTOMATION_LIBRARIES,
    LIST_DATA_AUTOMATION_LIBRARY_ENTITIES,
    LIST_DATA_AUTOMATION_LIBRARY_INGESTION_JOBS,
    LIST_DATA_AUTOMATION_PROJECTS,
    LIST_TAGS_FOR_RESOURCE,
    ListBlueprintsInput,
    ListBlueprintsOutput,
    ListDataAutomationLibrariesInput,
    ListDataAutomationLibrariesOutput,
    ListDataAutomationLibraryEntitiesInput,
    ListDataAutomationLibraryEntitiesOutput,
    ListDataAutomationLibraryIngestionJobsInput,
    ListDataAutomationLibraryIngestionJobsOutput,
    ListDataAutomationProjectsInput,
    ListDataAutomationProjectsOutput,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    TAG_RESOURCE,
    TagResourceInput,
    TagResourceOutput,
    UNTAG_RESOURCE,
    UPDATE_BLUEPRINT,
    UPDATE_DATA_AUTOMATION_LIBRARY,
    UPDATE_DATA_AUTOMATION_PROJECT,
    UntagResourceInput,
    UntagResourceOutput,
    UpdateBlueprintInput,
    UpdateBlueprintOutput,
    UpdateDataAutomationLibraryInput,
    UpdateDataAutomationLibraryOutput,
    UpdateDataAutomationProjectInput,
    UpdateDataAutomationProjectOutput,
)
from .user_agent import aws_user_agent_plugin


logger = logging.getLogger(__name__)


class AsyncBedrockDataAutomationClient(AsyncClient):
    """Amazon Bedrock Data Automation BuildTime"""

    def __init__(
        self,
        config: AsyncBedrockDataAutomationConfig | None = None,
        plugins: list[Plugin] | None = None,
    ):
        """
        Constructor for `AsyncBedrockDataAutomationClient`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables applied once to the client's base configuration.
                Their changes are inherited by every operation invocation.
        """
        super().__init__()
        self._config = config
        self._plugins = plugins
        self._client_plugins: list[Plugin] = [aws_user_agent_plugin, user_agent_plugin]

    async def _ensure_setup(self) -> AsyncBedrockDataAutomationConfig:
        if not self._setup_done:
            async with self._derive_lock:
                if self._closed:
                    raise RuntimeError(
                        "Cannot invoke an operation on a client that has been closed."
                    )
                if not self._setup_done:
                    if self._config is None:
                        config = await AsyncBedrockDataAutomationConfig.resolve()
                    else:
                        # Copy so plugins don't mutate the caller's config.
                        config = deepcopy(self._config)
                    for plugin in self._client_plugins:
                        plugin(config)
                    if self._plugins:
                        for plugin in self._plugins:
                            plugin(config)
                    # Publish state only after setup fully succeeds, so a
                    # failed _post_setup leaves the caller's config untouched
                    # (no re-applied plugins) and the transport closeable.
                    await self._post_setup(config)
                    self._transport = config.transport
                    self._config = config
                    self._setup_done = True
        assert self._config is not None
        return self._config

    async def _post_setup(self, config: AsyncBedrockDataAutomationConfig) -> None:
        if config.aws_credentials_identity_resolver is None:
            config_context = config.resolution_context()
            config_file = None
            profile_name = None
            if config_context is not None:
                config_file = await config_context.parsed_profiles()
                if config_context.profile_source is ConfigSource.OVERRIDE:
                    profile_name = config_context.profile_name
            config.aws_credentials_identity_resolver = await IdentityChain.create(
                AWSCredentialsIdentity,
                config_file=config_file,
                profile_name=profile_name,
                region_override=config.region,
                http_client=cast(HTTPClient | None, config.transport),
            )

    async def _prepare_call[I: SerializeableShape, O: DeserializeableShape](
        self,
        input: I,
        operation: APIOperation[I, O],
        default_plugins: list[Plugin],
        plugins: list[Plugin] | None,
    ) -> tuple[RequestPipeline[Any, Any], ClientCall[I, O]]:
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )
        config = await self._ensure_setup()
        if default_plugins or plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(config)
            for plugin in default_plugins:
                plugin(config)
            if plugins:
                for plugin in plugins:
                    plugin(config)
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )
        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )
        return self._build_call(
            input, operation, config=config, retry_strategy=retry_strategy
        )

    async def copy_blueprint_stage(
        self, input: CopyBlueprintStageInput, plugins: list[Plugin] | None = None
    ) -> CopyBlueprintStageOutput:
        """
        Copies a Blueprint from one stage to another

        Args:
            input:
                An instance of `CopyBlueprintStageInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CopyBlueprintStageOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, COPY_BLUEPRINT_STAGE, [], plugins
        )
        return await pipeline(call)

    async def create_blueprint(
        self, input: CreateBlueprintInput, plugins: list[Plugin] | None = None
    ) -> CreateBlueprintOutput:
        """
        Creates an Amazon Bedrock Data Automation Blueprint

        Args:
            input:
                An instance of `CreateBlueprintInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateBlueprintOutput`.
        """
        pipeline, call = await self._prepare_call(input, CREATE_BLUEPRINT, [], plugins)
        return await pipeline(call)

    async def create_blueprint_version(
        self, input: CreateBlueprintVersionInput, plugins: list[Plugin] | None = None
    ) -> CreateBlueprintVersionOutput:
        """
        Creates a new version of an existing Amazon Bedrock Data Automation
        Blueprint

        Args:
            input:
                An instance of `CreateBlueprintVersionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateBlueprintVersionOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, CREATE_BLUEPRINT_VERSION, [], plugins
        )
        return await pipeline(call)

    async def create_data_automation_library(
        self,
        input: CreateDataAutomationLibraryInput,
        plugins: list[Plugin] | None = None,
    ) -> CreateDataAutomationLibraryOutput:
        """
        Creates an Amazon Bedrock Data Automation Library

        Args:
            input:
                An instance of `CreateDataAutomationLibraryInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateDataAutomationLibraryOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, CREATE_DATA_AUTOMATION_LIBRARY, [], plugins
        )
        return await pipeline(call)

    async def create_data_automation_project(
        self,
        input: CreateDataAutomationProjectInput,
        plugins: list[Plugin] | None = None,
    ) -> CreateDataAutomationProjectOutput:
        """
        Creates an Amazon Bedrock Data Automation Project

        Args:
            input:
                An instance of `CreateDataAutomationProjectInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateDataAutomationProjectOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, CREATE_DATA_AUTOMATION_PROJECT, [], plugins
        )
        return await pipeline(call)

    async def delete_blueprint(
        self, input: DeleteBlueprintInput, plugins: list[Plugin] | None = None
    ) -> DeleteBlueprintOutput:
        """
        Deletes an existing Amazon Bedrock Data Automation Blueprint

        Args:
            input:
                An instance of `DeleteBlueprintInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteBlueprintOutput`.
        """
        pipeline, call = await self._prepare_call(input, DELETE_BLUEPRINT, [], plugins)
        return await pipeline(call)

    async def delete_data_automation_library(
        self,
        input: DeleteDataAutomationLibraryInput,
        plugins: list[Plugin] | None = None,
    ) -> DeleteDataAutomationLibraryOutput:
        """
        Deletes an existing Amazon Bedrock Data Automation Library

        Args:
            input:
                An instance of `DeleteDataAutomationLibraryInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteDataAutomationLibraryOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, DELETE_DATA_AUTOMATION_LIBRARY, [], plugins
        )
        return await pipeline(call)

    async def delete_data_automation_project(
        self,
        input: DeleteDataAutomationProjectInput,
        plugins: list[Plugin] | None = None,
    ) -> DeleteDataAutomationProjectOutput:
        """
        Deletes an existing Amazon Bedrock Data Automation Project

        Args:
            input:
                An instance of `DeleteDataAutomationProjectInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteDataAutomationProjectOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, DELETE_DATA_AUTOMATION_PROJECT, [], plugins
        )
        return await pipeline(call)

    async def get_blueprint(
        self, input: GetBlueprintInput, plugins: list[Plugin] | None = None
    ) -> GetBlueprintOutput:
        """
        Gets an existing Amazon Bedrock Data Automation Blueprint

        Args:
            input:
                An instance of `GetBlueprintInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetBlueprintOutput`.
        """
        pipeline, call = await self._prepare_call(input, GET_BLUEPRINT, [], plugins)
        return await pipeline(call)

    async def get_blueprint_optimization_status(
        self,
        input: GetBlueprintOptimizationStatusInput,
        plugins: list[Plugin] | None = None,
    ) -> GetBlueprintOptimizationStatusOutput:
        """
        API used to get blueprint optimization status.

        Args:
            input:
                An instance of `GetBlueprintOptimizationStatusInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetBlueprintOptimizationStatusOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, GET_BLUEPRINT_OPTIMIZATION_STATUS, [], plugins
        )
        return await pipeline(call)

    async def get_data_automation_library(
        self, input: GetDataAutomationLibraryInput, plugins: list[Plugin] | None = None
    ) -> GetDataAutomationLibraryOutput:
        """
        Gets an existing Amazon Bedrock Data Automation Library

        Args:
            input:
                An instance of `GetDataAutomationLibraryInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetDataAutomationLibraryOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, GET_DATA_AUTOMATION_LIBRARY, [], plugins
        )
        return await pipeline(call)

    async def get_data_automation_library_entity(
        self,
        input: GetDataAutomationLibraryEntityInput,
        plugins: list[Plugin] | None = None,
    ) -> GetDataAutomationLibraryEntityOutput:
        """
        Gets an existing entity based on entity type from the library

        Args:
            input:
                An instance of `GetDataAutomationLibraryEntityInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetDataAutomationLibraryEntityOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, GET_DATA_AUTOMATION_LIBRARY_ENTITY, [], plugins
        )
        return await pipeline(call)

    async def get_data_automation_library_ingestion_job(
        self,
        input: GetDataAutomationLibraryIngestionJobInput,
        plugins: list[Plugin] | None = None,
    ) -> GetDataAutomationLibraryIngestionJobOutput:
        """
        API used to get status of data automation library ingestion job

        Args:
            input:
                An instance of `GetDataAutomationLibraryIngestionJobInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetDataAutomationLibraryIngestionJobOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, GET_DATA_AUTOMATION_LIBRARY_INGESTION_JOB, [], plugins
        )
        return await pipeline(call)

    async def get_data_automation_project(
        self, input: GetDataAutomationProjectInput, plugins: list[Plugin] | None = None
    ) -> GetDataAutomationProjectOutput:
        """
        Gets an existing Amazon Bedrock Data Automation Project

        Args:
            input:
                An instance of `GetDataAutomationProjectInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetDataAutomationProjectOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, GET_DATA_AUTOMATION_PROJECT, [], plugins
        )
        return await pipeline(call)

    async def invoke_blueprint_optimization_async(
        self,
        input: InvokeBlueprintOptimizationAsyncInput,
        plugins: list[Plugin] | None = None,
    ) -> InvokeBlueprintOptimizationAsyncOutput:
        """
        Invoke an async job to perform Blueprint Optimization

        Args:
            input:
                An instance of `InvokeBlueprintOptimizationAsyncInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `InvokeBlueprintOptimizationAsyncOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, INVOKE_BLUEPRINT_OPTIMIZATION_ASYNC, [], plugins
        )
        return await pipeline(call)

    async def invoke_data_automation_library_ingestion_job(
        self,
        input: InvokeDataAutomationLibraryIngestionJobInput,
        plugins: list[Plugin] | None = None,
    ) -> InvokeDataAutomationLibraryIngestionJobOutput:
        """
        Async API: Invoke data automation library ingestion job

        Args:
            input:
                An instance of `InvokeDataAutomationLibraryIngestionJobInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `InvokeDataAutomationLibraryIngestionJobOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, INVOKE_DATA_AUTOMATION_LIBRARY_INGESTION_JOB, [], plugins
        )
        return await pipeline(call)

    async def list_blueprints(
        self, input: ListBlueprintsInput, plugins: list[Plugin] | None = None
    ) -> ListBlueprintsOutput:
        """
        Lists all existing Amazon Bedrock Data Automation Blueprints

        Args:
            input:
                An instance of `ListBlueprintsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListBlueprintsOutput`.
        """
        pipeline, call = await self._prepare_call(input, LIST_BLUEPRINTS, [], plugins)
        return await pipeline(call)

    async def list_data_automation_libraries(
        self,
        input: ListDataAutomationLibrariesInput,
        plugins: list[Plugin] | None = None,
    ) -> ListDataAutomationLibrariesOutput:
        """
        Lists all existing Amazon Bedrock Data Automation Libraries

        Args:
            input:
                An instance of `ListDataAutomationLibrariesInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListDataAutomationLibrariesOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, LIST_DATA_AUTOMATION_LIBRARIES, [], plugins
        )
        return await pipeline(call)

    async def list_data_automation_library_entities(
        self,
        input: ListDataAutomationLibraryEntitiesInput,
        plugins: list[Plugin] | None = None,
    ) -> ListDataAutomationLibraryEntitiesOutput:
        """
        Lists all stored entities in the library

        Args:
            input:
                An instance of `ListDataAutomationLibraryEntitiesInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListDataAutomationLibraryEntitiesOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, LIST_DATA_AUTOMATION_LIBRARY_ENTITIES, [], plugins
        )
        return await pipeline(call)

    async def list_data_automation_library_ingestion_jobs(
        self,
        input: ListDataAutomationLibraryIngestionJobsInput,
        plugins: list[Plugin] | None = None,
    ) -> ListDataAutomationLibraryIngestionJobsOutput:
        """
        Lists all data automation library ingestion jobs

        Args:
            input:
                An instance of `ListDataAutomationLibraryIngestionJobsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListDataAutomationLibraryIngestionJobsOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, LIST_DATA_AUTOMATION_LIBRARY_INGESTION_JOBS, [], plugins
        )
        return await pipeline(call)

    async def list_data_automation_projects(
        self,
        input: ListDataAutomationProjectsInput,
        plugins: list[Plugin] | None = None,
    ) -> ListDataAutomationProjectsOutput:
        """
        Lists all existing Amazon Bedrock Data Automation Projects

        Args:
            input:
                An instance of `ListDataAutomationProjectsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListDataAutomationProjectsOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, LIST_DATA_AUTOMATION_PROJECTS, [], plugins
        )
        return await pipeline(call)

    async def list_tags_for_resource(
        self, input: ListTagsForResourceInput, plugins: list[Plugin] | None = None
    ) -> ListTagsForResourceOutput:
        """
        List tags for an Amazon Bedrock Data Automation resource

        Args:
            input:
                An instance of `ListTagsForResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListTagsForResourceOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, LIST_TAGS_FOR_RESOURCE, [], plugins
        )
        return await pipeline(call)

    async def tag_resource(
        self, input: TagResourceInput, plugins: list[Plugin] | None = None
    ) -> TagResourceOutput:
        """
        Tag an Amazon Bedrock Data Automation resource

        Args:
            input:
                An instance of `TagResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `TagResourceOutput`.
        """
        pipeline, call = await self._prepare_call(input, TAG_RESOURCE, [], plugins)
        return await pipeline(call)

    async def untag_resource(
        self, input: UntagResourceInput, plugins: list[Plugin] | None = None
    ) -> UntagResourceOutput:
        """
        Untag an Amazon Bedrock Data Automation resource

        Args:
            input:
                An instance of `UntagResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UntagResourceOutput`.
        """
        pipeline, call = await self._prepare_call(input, UNTAG_RESOURCE, [], plugins)
        return await pipeline(call)

    async def update_blueprint(
        self, input: UpdateBlueprintInput, plugins: list[Plugin] | None = None
    ) -> UpdateBlueprintOutput:
        """
        Updates an existing Amazon Bedrock Data Automation Blueprint

        Args:
            input:
                An instance of `UpdateBlueprintInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UpdateBlueprintOutput`.
        """
        pipeline, call = await self._prepare_call(input, UPDATE_BLUEPRINT, [], plugins)
        return await pipeline(call)

    async def update_data_automation_library(
        self,
        input: UpdateDataAutomationLibraryInput,
        plugins: list[Plugin] | None = None,
    ) -> UpdateDataAutomationLibraryOutput:
        """
        Updates an existing Amazon Bedrock Data Automation Library

        Args:
            input:
                An instance of `UpdateDataAutomationLibraryInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UpdateDataAutomationLibraryOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, UPDATE_DATA_AUTOMATION_LIBRARY, [], plugins
        )
        return await pipeline(call)

    async def update_data_automation_project(
        self,
        input: UpdateDataAutomationProjectInput,
        plugins: list[Plugin] | None = None,
    ) -> UpdateDataAutomationProjectOutput:
        """
        Updates an existing Amazon Bedrock Data Automation Project

        Args:
            input:
                An instance of `UpdateDataAutomationProjectInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UpdateDataAutomationProjectOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, UPDATE_DATA_AUTOMATION_PROJECT, [], plugins
        )
        return await pipeline(call)
