# Code generated by smithy-python-codegen DO NOT EDIT.

from types import MappingProxyType

from smithy_core.prelude import BLOB, BOOLEAN, INTEGER, LONG, STRING, TIMESTAMP, UNIT
from smithy_core.schemas import Schema
from smithy_core.shapes import ShapeID, ShapeType
from smithy_core.traits import Trait


NON_BLANK_STRING = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#NonBlankString"),
    shape_type=ShapeType.STRING,
)

ACCESS_DENIED_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#AccessDeniedException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=403),
    ],
    members={"message": {"target": NON_BLANK_STRING}},
)

INVOCATION_ARN = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#InvocationArn"),
    shape_type=ShapeType.STRING,
)

GET_DATA_AUTOMATION_STATUS_INPUT = Schema.collection(
    id=ShapeID(
        "com.amazonaws.bedrockdataautomationruntime#GetDataAutomationStatusInput"
    ),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.bedrockdataautomationruntime#GetDataAutomationStatusRequest",
        )
    ],
    members={
        "invocationArn": {
            "target": INVOCATION_ARN,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        }
    },
)

S3_URI = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#S3Uri"),
    shape_type=ShapeType.STRING,
)

OUTPUT_CONFIGURATION = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#OutputConfiguration"),
    members={
        "s3Uri": {
            "target": S3_URI,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

AUTOMATION_JOB_STATUS = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#AutomationJobStatus"),
    shape_type=ShapeType.ENUM,
    members={
        "CREATED": {"target": UNIT},
        "IN_PROGRESS": {"target": UNIT},
        "SUCCESS": {"target": UNIT},
        "SERVICE_ERROR": {"target": UNIT},
        "CLIENT_ERROR": {"target": UNIT},
    },
)

GET_DATA_AUTOMATION_STATUS_OUTPUT = Schema.collection(
    id=ShapeID(
        "com.amazonaws.bedrockdataautomationruntime#GetDataAutomationStatusOutput"
    ),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.bedrockdataautomationruntime#GetDataAutomationStatusResponse",
        )
    ],
    members={
        "status": {"target": AUTOMATION_JOB_STATUS},
        "errorType": {"target": STRING},
        "errorMessage": {"target": STRING},
        "outputConfiguration": {"target": OUTPUT_CONFIGURATION},
        "jobSubmissionTime": {
            "target": TIMESTAMP,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#timestampFormat"), value="date-time")
            ],
        },
        "jobCompletionTime": {
            "target": TIMESTAMP,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#timestampFormat"), value="date-time")
            ],
        },
        "jobDurationInSeconds": {"target": INTEGER},
    },
)

INTERNAL_SERVER_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#InternalServerException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="server"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=500),
    ],
    members={"message": {"target": NON_BLANK_STRING}},
)

RESOURCE_NOT_FOUND_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#ResourceNotFoundException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=404),
    ],
    members={"message": {"target": NON_BLANK_STRING}},
)

THROTTLING_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#ThrottlingException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=429),
    ],
    members={"message": {"target": NON_BLANK_STRING}},
)

VALIDATION_EXCEPTION = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#ValidationException"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
    ],
    members={"message": {"target": NON_BLANK_STRING}},
)

GET_DATA_AUTOMATION_STATUS = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#GetDataAutomationStatus"),
    shape_type=ShapeType.OPERATION,
)

BLUEPRINT_ARN = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#BlueprintArn"),
    shape_type=ShapeType.STRING,
)

BLUEPRINT_STAGE = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#BlueprintStage"),
    shape_type=ShapeType.ENUM,
    members={"DEVELOPMENT": {"target": UNIT}, "LIVE": {"target": UNIT}},
)

BLUEPRINT_VERSION = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#BlueprintVersion"),
    shape_type=ShapeType.STRING,
)

BLUEPRINT = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#Blueprint"),
    members={
        "blueprintArn": {
            "target": BLUEPRINT_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "version": {"target": BLUEPRINT_VERSION},
        "stage": {"target": BLUEPRINT_STAGE},
    },
)

BLUEPRINT_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#BlueprintList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": BLUEPRINT}},
)

IDEMPOTENCY_TOKEN = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#IdempotencyToken"),
    shape_type=ShapeType.STRING,
)

DATA_AUTOMATION_ARN = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#DataAutomationArn"),
    shape_type=ShapeType.STRING,
)

DATA_AUTOMATION_STAGE = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#DataAutomationStage"),
    shape_type=ShapeType.ENUM,
    members={"LIVE": {"target": UNIT}, "DEVELOPMENT": {"target": UNIT}},
)

DATA_AUTOMATION_CONFIGURATION = Schema.collection(
    id=ShapeID(
        "com.amazonaws.bedrockdataautomationruntime#DataAutomationConfiguration"
    ),
    members={
        "dataAutomationProjectArn": {
            "target": DATA_AUTOMATION_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "stage": {"target": DATA_AUTOMATION_STAGE},
    },
)

DATA_AUTOMATION_PROFILE_ARN = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#DataAutomationProfileArn"),
    shape_type=ShapeType.STRING,
)

ENCRYPTION_CONTEXT_KEY = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#EncryptionContextKey"),
    shape_type=ShapeType.STRING,
)

ENCRYPTION_CONTEXT_VALUE = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#EncryptionContextValue"),
    shape_type=ShapeType.STRING,
)

ENCRYPTION_CONTEXT_MAP = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#EncryptionContextMap"),
    shape_type=ShapeType.MAP,
    members={
        "key": {"target": ENCRYPTION_CONTEXT_KEY},
        "value": {"target": ENCRYPTION_CONTEXT_VALUE},
    },
)

KMS_KEY_ID = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#KMSKeyId"),
    shape_type=ShapeType.STRING,
)

ENCRYPTION_CONFIGURATION = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#EncryptionConfiguration"),
    members={
        "kmsKeyId": {
            "target": KMS_KEY_ID,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "kmsEncryptionContext": {"target": ENCRYPTION_CONTEXT_MAP},
    },
)

TIMESTAMP_SEGMENT = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#TimestampSegment"),
    members={
        "startTimeMillis": {
            "target": LONG,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "endTimeMillis": {
            "target": LONG,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

VIDEO_SEGMENT_CONFIGURATION = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#VideoSegmentConfiguration"),
    shape_type=ShapeType.UNION,
    members={"timestampSegment": {"target": TIMESTAMP_SEGMENT}},
)

VIDEO_ASSET_PROCESSING_CONFIGURATION = Schema.collection(
    id=ShapeID(
        "com.amazonaws.bedrockdataautomationruntime#VideoAssetProcessingConfiguration"
    ),
    members={"segmentConfiguration": {"target": VIDEO_SEGMENT_CONFIGURATION}},
)

ASSET_PROCESSING_CONFIGURATION = Schema.collection(
    id=ShapeID(
        "com.amazonaws.bedrockdataautomationruntime#AssetProcessingConfiguration"
    ),
    members={"video": {"target": VIDEO_ASSET_PROCESSING_CONFIGURATION}},
)

INPUT_CONFIGURATION = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#InputConfiguration"),
    members={
        "s3Uri": {
            "target": S3_URI,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "assetProcessingConfiguration": {"target": ASSET_PROCESSING_CONFIGURATION},
    },
)

EVENT_BRIDGE_CONFIGURATION = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#EventBridgeConfiguration"),
    members={
        "eventBridgeEnabled": {
            "target": BOOLEAN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

NOTIFICATION_CONFIGURATION = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#NotificationConfiguration"),
    members={
        "eventBridgeConfiguration": {
            "target": EVENT_BRIDGE_CONFIGURATION,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

TAG_KEY = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#TagKey"),
    shape_type=ShapeType.STRING,
)

TAG_VALUE = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#TagValue"),
    shape_type=ShapeType.STRING,
)

TAG = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#Tag"),
    members={
        "key": {
            "target": TAG_KEY,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "value": {
            "target": TAG_VALUE,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

TAG_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#TagList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": TAG}},
)

INVOKE_DATA_AUTOMATION_ASYNC_INPUT = Schema.collection(
    id=ShapeID(
        "com.amazonaws.bedrockdataautomationruntime#InvokeDataAutomationAsyncInput"
    ),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.bedrockdataautomationruntime#InvokeDataAutomationAsyncRequest",
        )
    ],
    members={
        "clientToken": {
            "target": IDEMPOTENCY_TOKEN,
            "traits": [Trait.new(id=ShapeID("smithy.api#idempotencyToken"))],
        },
        "inputConfiguration": {
            "target": INPUT_CONFIGURATION,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "outputConfiguration": {
            "target": OUTPUT_CONFIGURATION,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "dataAutomationConfiguration": {"target": DATA_AUTOMATION_CONFIGURATION},
        "encryptionConfiguration": {"target": ENCRYPTION_CONFIGURATION},
        "notificationConfiguration": {"target": NOTIFICATION_CONFIGURATION},
        "blueprints": {"target": BLUEPRINT_LIST},
        "dataAutomationProfileArn": {
            "target": DATA_AUTOMATION_PROFILE_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "tags": {"target": TAG_LIST},
    },
)

INVOKE_DATA_AUTOMATION_ASYNC_OUTPUT = Schema.collection(
    id=ShapeID(
        "com.amazonaws.bedrockdataautomationruntime#InvokeDataAutomationAsyncOutput"
    ),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.bedrockdataautomationruntime#InvokeDataAutomationAsyncResponse",
        )
    ],
    members={
        "invocationArn": {
            "target": INVOCATION_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

SERVICE_QUOTA_EXCEEDED_EXCEPTION = Schema.collection(
    id=ShapeID(
        "com.amazonaws.bedrockdataautomationruntime#ServiceQuotaExceededException"
    ),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=402),
    ],
    members={"message": {"target": NON_BLANK_STRING}},
)

INVOKE_DATA_AUTOMATION_ASYNC = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#InvokeDataAutomationAsync"),
    shape_type=ShapeType.OPERATION,
)

SYNC_INPUT_CONFIGURATION = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#SyncInputConfiguration"),
    members={"bytes": {"target": BLOB}, "s3Uri": {"target": S3_URI}},
)

INVOKE_DATA_AUTOMATION_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#InvokeDataAutomationInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.bedrockdataautomationruntime#InvokeDataAutomationRequest",
        )
    ],
    members={
        "inputConfiguration": {
            "target": SYNC_INPUT_CONFIGURATION,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "dataAutomationConfiguration": {"target": DATA_AUTOMATION_CONFIGURATION},
        "blueprints": {"target": BLUEPRINT_LIST},
        "dataAutomationProfileArn": {
            "target": DATA_AUTOMATION_PROFILE_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "encryptionConfiguration": {"target": ENCRYPTION_CONFIGURATION},
        "outputConfiguration": {"target": OUTPUT_CONFIGURATION},
    },
)

CUSTOM_OUTPUT_STATUS = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#CustomOutputStatus"),
    shape_type=ShapeType.ENUM,
    members={"MATCH": {"target": UNIT}, "NO_MATCH": {"target": UNIT}},
)

OUTPUT_SEGMENT = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#OutputSegment"),
    members={
        "customOutputStatus": {"target": CUSTOM_OUTPUT_STATUS},
        "customOutput": {"target": STRING},
        "standardOutput": {"target": STRING},
    },
)

OUTPUT_SEGMENT_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#OutputSegmentList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": OUTPUT_SEGMENT}},
)

SEMANTIC_MODALITY = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#SemanticModality"),
    shape_type=ShapeType.ENUM,
    members={
        "DOCUMENT": {"target": UNIT},
        "IMAGE": {"target": UNIT},
        "AUDIO": {"target": UNIT},
        "VIDEO": {"target": UNIT},
    },
)

INVOKE_DATA_AUTOMATION_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#InvokeDataAutomationOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.bedrockdataautomationruntime#InvokeDataAutomationResponse",
        )
    ],
    members={
        "outputConfiguration": {"target": OUTPUT_CONFIGURATION},
        "semanticModality": {
            "target": SEMANTIC_MODALITY,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "outputSegments": {
            "target": OUTPUT_SEGMENT_LIST,
            "traits": [Trait.new(id=ShapeID("smithy.api#default"), value=())],
        },
    },
)

SERVICE_UNAVAILABLE_EXCEPTION = Schema.collection(
    id=ShapeID(
        "com.amazonaws.bedrockdataautomationruntime#ServiceUnavailableException"
    ),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="server"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=503),
    ],
    members={"message": {"target": NON_BLANK_STRING}},
)

INVOKE_DATA_AUTOMATION = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#InvokeDataAutomation"),
    shape_type=ShapeType.OPERATION,
)

TAGGABLE_RESOURCE_ARN = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#TaggableResourceArn"),
    shape_type=ShapeType.STRING,
)

LIST_TAGS_FOR_RESOURCE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#ListTagsForResourceInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.bedrockdataautomationruntime#ListTagsForResourceRequest",
        )
    ],
    members={
        "resourceARN": {
            "target": TAGGABLE_RESOURCE_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        }
    },
)

LIST_TAGS_FOR_RESOURCE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#ListTagsForResourceOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.bedrockdataautomationruntime#ListTagsForResourceResponse",
        )
    ],
    members={"tags": {"target": TAG_LIST}},
)

LIST_TAGS_FOR_RESOURCE = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#ListTagsForResource"),
    shape_type=ShapeType.OPERATION,
)

TAG_RESOURCE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#TagResourceInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.bedrockdataautomationruntime#TagResourceRequest",
        )
    ],
    members={
        "resourceARN": {
            "target": TAGGABLE_RESOURCE_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "tags": {
            "target": TAG_LIST,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

TAG_RESOURCE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#TagResourceOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.bedrockdataautomationruntime#TagResourceResponse",
        )
    ],
)

TAG_RESOURCE = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#TagResource"),
    shape_type=ShapeType.OPERATION,
)

TAG_KEY_LIST = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#TagKeyList"),
    shape_type=ShapeType.LIST,
    members={"member": {"target": TAG_KEY}},
)

UNTAG_RESOURCE_INPUT = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#UntagResourceInput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.bedrockdataautomationruntime#UntagResourceRequest",
        )
    ],
    members={
        "resourceARN": {
            "target": TAGGABLE_RESOURCE_ARN,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
        "tagKeys": {
            "target": TAG_KEY_LIST,
            "traits": [Trait.new(id=ShapeID("smithy.api#required"))],
        },
    },
)

UNTAG_RESOURCE_OUTPUT = Schema.collection(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#UntagResourceOutput"),
    traits=[
        Trait.new(
            id=ShapeID("smithy.synthetic#originalShapeId"),
            value="com.amazonaws.bedrockdataautomationruntime#UntagResourceResponse",
        )
    ],
)

UNTAG_RESOURCE = Schema(
    id=ShapeID("com.amazonaws.bedrockdataautomationruntime#UntagResource"),
    shape_type=ShapeType.OPERATION,
)

AMAZON_BEDROCK_KEYSTONE_RUNTIME_SERVICE = Schema(
    id=ShapeID(
        "com.amazonaws.bedrockdataautomationruntime#AmazonBedrockKeystoneRuntimeService"
    ),
    shape_type=ShapeType.SERVICE,
    traits=[
        Trait.new(
            id=ShapeID("aws.auth#sigv4"), value=MappingProxyType({"name": "bedrock"})
        ),
        Trait.new(id=ShapeID("aws.protocols#awsJson1_1")),
        Trait.new(
            id=ShapeID("smithy.rules#endpointBdd"),
            value=MappingProxyType(
                {
                    "version": "1.1",
                    "parameters": MappingProxyType(
                        {
                            "Region": MappingProxyType(
                                {
                                    "builtIn": "AWS::Region",
                                    "required": False,
                                    "documentation": "The AWS region used to dispatch the request.",
                                    "type": "string",
                                }
                            ),
                            "UseDualStack": MappingProxyType(
                                {
                                    "builtIn": "AWS::UseDualStack",
                                    "required": True,
                                    "default": False,
                                    "documentation": "When true, use the dual-stack endpoint. If the configured endpoint does not support dual-stack, dispatching the request MAY return an error.",
                                    "type": "boolean",
                                }
                            ),
                            "UseFIPS": MappingProxyType(
                                {
                                    "builtIn": "AWS::UseFIPS",
                                    "required": True,
                                    "default": False,
                                    "documentation": "When true, send this request to the FIPS-compliant regional endpoint. If the configured endpoint does not have a FIPS compliant endpoint, dispatching the request will return an error.",
                                    "type": "boolean",
                                }
                            ),
                            "Endpoint": MappingProxyType(
                                {
                                    "builtIn": "SDK::Endpoint",
                                    "required": False,
                                    "documentation": "Override the endpoint used to send this request",
                                    "type": "string",
                                }
                            ),
                        }
                    ),
                    "conditions": (
                        MappingProxyType(
                            {
                                "fn": "isSet",
                                "argv": (MappingProxyType({"ref": "Endpoint"}),),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "isSet",
                                "argv": (MappingProxyType({"ref": "Region"}),),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "aws.partition",
                                "argv": (MappingProxyType({"ref": "Region"}),),
                                "assign": "PartitionResult",
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (MappingProxyType({"ref": "UseFIPS"}), True),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (
                                    MappingProxyType({"ref": "UseDualStack"}),
                                    True,
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "supportsDualStack",
                                            ),
                                        }
                                    ),
                                    True,
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "supportsFIPS",
                                            ),
                                        }
                                    ),
                                    True,
                                ),
                            }
                        ),
                    ),
                    "results": (
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: FIPS and custom endpoint are not supported",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: Dualstack and custom endpoint are not supported",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": MappingProxyType({"ref": "Endpoint"}),
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://bedrock-data-automation-runtime-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "FIPS and DualStack are enabled, but this partition does not support one or both",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://bedrock-data-automation-runtime-fips.{Region}.{PartitionResult#dnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "FIPS is enabled but this partition does not support FIPS",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://bedrock-data-automation-runtime.{Region}.{PartitionResult#dualStackDnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "DualStack is enabled but this partition does not support DualStack",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://bedrock-data-automation-runtime.{Region}.{PartitionResult#dnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: Missing Region",
                                "type": "error",
                            }
                        ),
                    ),
                    "root": 2,
                    "nodeCount": 13,
                    "nodes": "/////wAAAAH/////AAAAAAAAAAwAAAADAAAAAQAAAAQF9eELAAAAAgAAAAUF9eELAAAAAwAAAAgAAAAGAAAABAAAAAcF9eEKAAAABQX14QgF9eEJAAAABAAAAAoAAAAJAAAABgX14QYF9eEHAAAABQAAAAsF9eEFAAAABgX14QQF9eEFAAAAAwX14QEAAAANAAAABAX14QIF9eED",
                }
            ),
        ),
        Trait.new(
            id=ShapeID("aws.api#service"),
            value=MappingProxyType(
                {
                    "sdkId": "Bedrock Data Automation Runtime",
                    "arnNamespace": "bedrock",
                    "endpointPrefix": "bedrock-data-automation-runtime",
                    "cloudTrailEventSource": "bedrock.amazonaws.com",
                }
            ),
        ),
    ],
)
