# Code generated by smithy-python-codegen DO NOT EDIT.

from copy import deepcopy
import logging
from typing import Any, cast

from smithy_aws_core.config import ConfigSource
from smithy_aws_core.identity import AWSCredentialsIdentity
from smithy_aws_core.identity.chain import IdentityChain
from smithy_core.aio.client import AsyncClient, ClientCall, RequestPipeline
from smithy_core.deserializers import DeserializeableShape
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.schemas import APIOperation
from smithy_core.serializers import SerializeableShape
from smithy_http.aio.interfaces import HTTPClient
from smithy_http.plugins import user_agent_plugin

from .config import AsyncSigninConfig, Plugin
from .models import (
    CREATE_O_AUTH2_TOKEN,
    CREATE_O_AUTH2_TOKEN_WITH_IAM,
    CreateOAuth2TokenInput,
    CreateOAuth2TokenOutput,
    CreateOAuth2TokenWithIAMInput,
    CreateOAuth2TokenWithIAMOutput,
    DELETE_CONSOLE_AUTHORIZATION_CONFIGURATION,
    DELETE_RESOURCE_PERMISSION_STATEMENT,
    DeleteConsoleAuthorizationConfigurationInput,
    DeleteConsoleAuthorizationConfigurationOutput,
    DeleteResourcePermissionStatementInput,
    DeleteResourcePermissionStatementOutput,
    GET_CONSOLE_AUTHORIZATION_CONFIGURATION,
    GET_RESOURCE_POLICY,
    GetConsoleAuthorizationConfigurationInput,
    GetConsoleAuthorizationConfigurationOutput,
    GetResourcePolicyInput,
    GetResourcePolicyOutput,
    INTROSPECT_O_AUTH2_TOKEN_WITH_IAM,
    IntrospectOAuth2TokenWithIAMInput,
    IntrospectOAuth2TokenWithIAMOutput,
    LIST_RESOURCE_PERMISSION_STATEMENTS,
    ListResourcePermissionStatementsInput,
    ListResourcePermissionStatementsOutput,
    PUT_CONSOLE_AUTHORIZATION_CONFIGURATION,
    PUT_RESOURCE_PERMISSION_STATEMENT,
    PutConsoleAuthorizationConfigurationInput,
    PutConsoleAuthorizationConfigurationOutput,
    PutResourcePermissionStatementInput,
    PutResourcePermissionStatementOutput,
    REVOKE_O_AUTH2_TOKEN_WITH_IAM,
    RevokeOAuth2TokenWithIAMInput,
    RevokeOAuth2TokenWithIAMOutput,
)
from .user_agent import aws_user_agent_plugin


logger = logging.getLogger(__name__)


class AsyncSigninClient(AsyncClient):
    """
    AWS Sign-In manages authentication for AWS services. This service
    provides secure authentication flows for accessing AWS resources from
    the console and developer tools.
    """

    def __init__(
        self,
        config: AsyncSigninConfig | None = None,
        plugins: list[Plugin] | None = None,
    ):
        """
        Constructor for `AsyncSigninClient`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables applied once to the client's base configuration.
                Their changes are inherited by every operation invocation.
        """
        super().__init__()
        self._config = config
        self._plugins = plugins
        self._client_plugins: list[Plugin] = [aws_user_agent_plugin, user_agent_plugin]

    async def _ensure_setup(self) -> AsyncSigninConfig:
        if not self._setup_done:
            async with self._derive_lock:
                if self._closed:
                    raise RuntimeError(
                        "Cannot invoke an operation on a client that has been closed."
                    )
                if not self._setup_done:
                    if self._config is None:
                        config = await AsyncSigninConfig.resolve()
                    else:
                        # Copy so plugins don't mutate the caller's config.
                        config = deepcopy(self._config)
                    for plugin in self._client_plugins:
                        plugin(config)
                    if self._plugins:
                        for plugin in self._plugins:
                            plugin(config)
                    # Publish state only after setup fully succeeds, so a
                    # failed _post_setup leaves the caller's config untouched
                    # (no re-applied plugins) and the transport closeable.
                    await self._post_setup(config)
                    self._transport = config.transport
                    self._config = config
                    self._setup_done = True
        assert self._config is not None
        return self._config

    async def _post_setup(self, config: AsyncSigninConfig) -> None:
        if config.aws_credentials_identity_resolver is None:
            config_context = config.resolution_context()
            config_file = None
            profile_name = None
            if config_context is not None:
                config_file = await config_context.parsed_profiles()
                if config_context.profile_source is ConfigSource.OVERRIDE:
                    profile_name = config_context.profile_name
            config.aws_credentials_identity_resolver = await IdentityChain.create(
                AWSCredentialsIdentity,
                config_file=config_file,
                profile_name=profile_name,
                region_override=config.region,
                http_client=cast(HTTPClient | None, config.transport),
            )

    async def _prepare_call[I: SerializeableShape, O: DeserializeableShape](
        self,
        input: I,
        operation: APIOperation[I, O],
        default_plugins: list[Plugin],
        plugins: list[Plugin] | None,
    ) -> tuple[RequestPipeline[Any, Any], ClientCall[I, O]]:
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )
        config = await self._ensure_setup()
        if default_plugins or plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(config)
            for plugin in default_plugins:
                plugin(config)
            if plugins:
                for plugin in plugins:
                    plugin(config)
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )
        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )
        return self._build_call(
            input, operation, config=config, retry_strategy=retry_strategy
        )

    async def create_o_auth2_token(
        self, input: CreateOAuth2TokenInput, plugins: list[Plugin] | None = None
    ) -> CreateOAuth2TokenOutput:
        """
        CreateOAuth2Token API Path: /v1/token Request Method: POST Content-Type:
        application/json or application/x-www-form-urlencoded This API
        implements OAuth 2.0 flows for AWS Sign-In CLI clients, supporting
        both: 1. Authorization code redemption (grant_type=authorization_code) -
        NOT idempotent 2. Token refresh (grant_type=refresh_token) - Idempotent
        within token validity window The operation behavior is determined by the
        grant_type parameter in the request body: **Authorization Code Flow
        (NOT Idempotent):** - JSON or form-encoded body with client_id,
        grant_type=authorization_code, code, redirect_uri, code_verifier -
        Returns access_token, token_type, expires_in, refresh_token, and
        id_token - Each authorization code can only be used ONCE for security
        (prevents replay attacks) **Token Refresh Flow (Idempotent):** -
        JSON or form-encoded body with client_id, grant_type=refresh_token,
        refresh_token - Returns access_token, token_type, expires_in, and
        refresh_token (no id_token) - Multiple calls with same refresh_token
        return consistent results within validity window Authentication and
        authorization: - Confidential clients: sigv4 signing required with
        signin:ExchangeToken permissions - CLI clients (public): authn/authz
        skipped based on client_id & grant_type Note: This operation cannot be
        marked as @idempotent because it handles both idempotent (token
        refresh) and non-idempotent (auth code redemption) flows in a single
        endpoint.

        Args:
            input:
                An instance of `CreateOAuth2TokenInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateOAuth2TokenOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, CREATE_O_AUTH2_TOKEN, [], plugins
        )
        return await pipeline(call)

    async def create_o_auth2_token_with_iam(
        self, input: CreateOAuth2TokenWithIAMInput, plugins: list[Plugin] | None = None
    ) -> CreateOAuth2TokenWithIAMOutput:
        """
        Grants permission to exchange client credentials for an OAuth 2.0 access
        token scoped to a resource that can be used to access AWS services from
        applications

        Args:
            input:
                An instance of `CreateOAuth2TokenWithIAMInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateOAuth2TokenWithIAMOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, CREATE_O_AUTH2_TOKEN_WITH_IAM, [], plugins
        )
        return await pipeline(call)

    async def delete_console_authorization_configuration(
        self,
        input: DeleteConsoleAuthorizationConfigurationInput,
        plugins: list[Plugin] | None = None,
    ) -> DeleteConsoleAuthorizationConfigurationOutput:
        """
        Delete console authorization configuration with automatic scope
        detection

        Args:
            input:
                An instance of `DeleteConsoleAuthorizationConfigurationInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteConsoleAuthorizationConfigurationOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, DELETE_CONSOLE_AUTHORIZATION_CONFIGURATION, [], plugins
        )
        return await pipeline(call)

    async def delete_resource_permission_statement(
        self,
        input: DeleteResourcePermissionStatementInput,
        plugins: list[Plugin] | None = None,
    ) -> DeleteResourcePermissionStatementOutput:
        """
        Remove a permission statement from the account's SignIn resource-based
        policy

        Args:
            input:
                An instance of `DeleteResourcePermissionStatementInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteResourcePermissionStatementOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, DELETE_RESOURCE_PERMISSION_STATEMENT, [], plugins
        )
        return await pipeline(call)

    async def get_console_authorization_configuration(
        self,
        input: GetConsoleAuthorizationConfigurationInput,
        plugins: list[Plugin] | None = None,
    ) -> GetConsoleAuthorizationConfigurationOutput:
        """
        Get console authorization configuration with automatic scope detection

        Args:
            input:
                An instance of `GetConsoleAuthorizationConfigurationInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetConsoleAuthorizationConfigurationOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, GET_CONSOLE_AUTHORIZATION_CONFIGURATION, [], plugins
        )
        return await pipeline(call)

    async def get_resource_policy(
        self, input: GetResourcePolicyInput, plugins: list[Plugin] | None = None
    ) -> GetResourcePolicyOutput:
        """
        Retrieve the account's consolidated SignIn resource-based policy

        Args:
            input:
                An instance of `GetResourcePolicyInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetResourcePolicyOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, GET_RESOURCE_POLICY, [], plugins
        )
        return await pipeline(call)

    async def introspect_o_auth2_token_with_iam(
        self,
        input: IntrospectOAuth2TokenWithIAMInput,
        plugins: list[Plugin] | None = None,
    ) -> IntrospectOAuth2TokenWithIAMOutput:
        """
        Grants permission to inspect the metadata and state of an OAuth 2.0
        access token or refresh token Implements RFC 7662 OAuth 2.0 Token
        Introspection over a SigV4-authenticated endpoint. Inspects the metadata
        of an access_token or refresh_token issued by AWS Sign-In and returns
        the claims associated with it. Inactive token semantics (RFC 7662 §2.2):
        when the supplied token is unknown, expired, revoked, malformed, or
        owned by a different account, the response body is exactly { \"active\":
        false } with all other claims omitted.

        Args:
            input:
                An instance of `IntrospectOAuth2TokenWithIAMInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `IntrospectOAuth2TokenWithIAMOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, INTROSPECT_O_AUTH2_TOKEN_WITH_IAM, [], plugins
        )
        return await pipeline(call)

    async def list_resource_permission_statements(
        self,
        input: ListResourcePermissionStatementsInput,
        plugins: list[Plugin] | None = None,
    ) -> ListResourcePermissionStatementsOutput:
        """
        Retrieve all permission statements in the account's SignIn
        resource-based policy

        Args:
            input:
                An instance of `ListResourcePermissionStatementsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListResourcePermissionStatementsOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, LIST_RESOURCE_PERMISSION_STATEMENTS, [], plugins
        )
        return await pipeline(call)

    async def put_console_authorization_configuration(
        self,
        input: PutConsoleAuthorizationConfigurationInput,
        plugins: list[Plugin] | None = None,
    ) -> PutConsoleAuthorizationConfigurationOutput:
        """
        Enable console authorization configuration with automatic scope
        detection

        Args:
            input:
                An instance of `PutConsoleAuthorizationConfigurationInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `PutConsoleAuthorizationConfigurationOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, PUT_CONSOLE_AUTHORIZATION_CONFIGURATION, [], plugins
        )
        return await pipeline(call)

    async def put_resource_permission_statement(
        self,
        input: PutResourcePermissionStatementInput,
        plugins: list[Plugin] | None = None,
    ) -> PutResourcePermissionStatementOutput:
        """
        Create a permission statement in the account's SignIn resource-based
        policy

        Args:
            input:
                An instance of `PutResourcePermissionStatementInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `PutResourcePermissionStatementOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, PUT_RESOURCE_PERMISSION_STATEMENT, [], plugins
        )
        return await pipeline(call)

    async def revoke_o_auth2_token_with_iam(
        self, input: RevokeOAuth2TokenWithIAMInput, plugins: list[Plugin] | None = None
    ) -> RevokeOAuth2TokenWithIAMOutput:
        """
        Grants permission to revoke an OAuth 2.0 refresh token and its
        associated refresh tokens Revokes a refresh_token issued by AWS Sign-In,
        invalidating the entire token chain so that the refresh_token can no
        longer be used to mint new access_tokens. Idempotency: revoking an
        already-revoked, expired, or otherwise invalid token still returns 200
        OK with an empty body. Only the refresh_token type is accepted.

        Args:
            input:
                An instance of `RevokeOAuth2TokenWithIAMInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `RevokeOAuth2TokenWithIAMOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, REVOKE_O_AUTH2_TOKEN_WITH_IAM, [], plugins
        )
        return await pipeline(call)
