# Code generated by smithy-python-codegen DO NOT EDIT.

from copy import deepcopy
import logging
from typing import Any, cast

from smithy_aws_core.config import ConfigSource
from smithy_aws_core.identity import AWSCredentialsIdentity
from smithy_aws_core.identity.chain import IdentityChain
from smithy_core.aio.client import AsyncClient, ClientCall, RequestPipeline
from smithy_core.aio.eventstream import DuplexEventStream
from smithy_core.deserializers import DeserializeableShape
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.schemas import APIOperation
from smithy_core.serializers import SerializeableShape
from smithy_http.aio.interfaces import HTTPClient
from smithy_http.plugins import user_agent_plugin

from .config import AsyncConnectHealthConfig, Plugin
from .models import (
    ACTIVATE_SUBSCRIPTION,
    ActivateSubscriptionInput,
    ActivateSubscriptionOutput,
    CREATE_DOMAIN,
    CREATE_SUBSCRIPTION,
    CreateDomainInput,
    CreateDomainOutput,
    CreateSubscriptionInput,
    CreateSubscriptionOutput,
    DEACTIVATE_SUBSCRIPTION,
    DELETE_DOMAIN,
    DeactivateSubscriptionInput,
    DeactivateSubscriptionOutput,
    DeleteDomainInput,
    DeleteDomainOutput,
    GET_DOMAIN,
    GET_MEDICAL_SCRIBE_LISTENING_SESSION,
    GET_PATIENT_INSIGHTS_JOB,
    GET_SUBSCRIPTION,
    GetDomainInput,
    GetDomainOutput,
    GetMedicalScribeListeningSessionInput,
    GetMedicalScribeListeningSessionOutput,
    GetPatientInsightsJobInput,
    GetPatientInsightsJobOutput,
    GetSubscriptionInput,
    GetSubscriptionOutput,
    LIST_DOMAINS,
    LIST_SUBSCRIPTIONS,
    LIST_TAGS_FOR_RESOURCE,
    ListDomainsInput,
    ListDomainsOutput,
    ListSubscriptionsInput,
    ListSubscriptionsOutput,
    ListTagsForResourceInput,
    ListTagsForResourceOutput,
    MedicalScribeInputStream,
    MedicalScribeOutputStream,
    START_MEDICAL_SCRIBE_LISTENING_SESSION,
    START_PATIENT_INSIGHTS_JOB,
    StartMedicalScribeListeningSessionInput,
    StartMedicalScribeListeningSessionOutput,
    StartPatientInsightsJobInput,
    StartPatientInsightsJobOutput,
    TAG_RESOURCE,
    TagResourceInput,
    TagResourceOutput,
    UNTAG_RESOURCE,
    UntagResourceInput,
    UntagResourceOutput,
    _MedicalScribeOutputStreamDeserializer,
)
from .user_agent import aws_user_agent_plugin


logger = logging.getLogger(__name__)


class AsyncConnectHealthClient(AsyncClient):
    """
    Amazon Connect Health is an AI-powered healthcare service built on
    Amazon Connect. It provides pre-built agents that automate patient
    engagement workflows and support clinical documentation at the point of
    care.

    You can use the Amazon Connect Health API to programmatically manage
    domains, configure patient engagement agents, run patient insights jobs,
    and stream ambient documentation sessions. This API reference describes
    the available API operations and data types for Amazon Connect Health.

    We recommend that you use the AWS SDKs to make programmatic API calls to
    Amazon Connect Health.
    """

    def __init__(
        self,
        config: AsyncConnectHealthConfig | None = None,
        plugins: list[Plugin] | None = None,
    ):
        """
        Constructor for `AsyncConnectHealthClient`.

        Args:
            config:
                Optional configuration for the client. Here you can set things like
                the endpoint for HTTP services or auth credentials.
            plugins:
                A list of callables applied once to the client's base configuration.
                Their changes are inherited by every operation invocation.
        """
        super().__init__()
        self._config = config
        self._plugins = plugins
        self._client_plugins: list[Plugin] = [aws_user_agent_plugin, user_agent_plugin]

    async def _ensure_setup(self) -> AsyncConnectHealthConfig:
        if not self._setup_done:
            async with self._derive_lock:
                if self._closed:
                    raise RuntimeError(
                        "Cannot invoke an operation on a client that has been closed."
                    )
                if not self._setup_done:
                    if self._config is None:
                        config = await AsyncConnectHealthConfig.resolve()
                    else:
                        # Copy so plugins don't mutate the caller's config.
                        config = deepcopy(self._config)
                    for plugin in self._client_plugins:
                        plugin(config)
                    if self._plugins:
                        for plugin in self._plugins:
                            plugin(config)
                    # Publish state only after setup fully succeeds, so a
                    # failed _post_setup leaves the caller's config untouched
                    # (no re-applied plugins) and the transport closeable.
                    await self._post_setup(config)
                    self._transport = config.transport
                    self._config = config
                    self._setup_done = True
        assert self._config is not None
        return self._config

    async def _post_setup(self, config: AsyncConnectHealthConfig) -> None:
        if config.aws_credentials_identity_resolver is None:
            config_context = config.resolution_context()
            config_file = None
            profile_name = None
            if config_context is not None:
                config_file = await config_context.parsed_profiles()
                if config_context.profile_source is ConfigSource.OVERRIDE:
                    profile_name = config_context.profile_name
            config.aws_credentials_identity_resolver = await IdentityChain.create(
                AWSCredentialsIdentity,
                config_file=config_file,
                profile_name=profile_name,
                region_override=config.region,
                http_client=cast(HTTPClient | None, config.transport),
            )

    async def _prepare_call[I: SerializeableShape, O: DeserializeableShape](
        self,
        input: I,
        operation: APIOperation[I, O],
        default_plugins: list[Plugin],
        plugins: list[Plugin] | None,
    ) -> tuple[RequestPipeline[Any, Any], ClientCall[I, O]]:
        if self._closed:
            raise RuntimeError(
                "Cannot invoke an operation on a client that has been closed."
            )
        config = await self._ensure_setup()
        if default_plugins or plugins:
            # Keep operation-plugin mutations scoped to this call.
            config = deepcopy(config)
            for plugin in default_plugins:
                plugin(config)
            if plugins:
                for plugin in plugins:
                    plugin(config)
        if (
            config.protocol is None
            or config.transport is None
            or config.endpoint_resolver is None
            or config.auth_scheme_resolver is None
            or config.auth_schemes is None
        ):
            raise ExpectationNotMetError(
                "protocol, transport, endpoint_resolver, auth_scheme_resolver,"
                " and auth_schemes MUST be set on the config to make calls."
            )
        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy,
            retry_mode=config.retry_mode,
            max_attempts=config.max_attempts,
        )
        return self._build_call(
            input, operation, config=config, retry_strategy=retry_strategy
        )

    async def activate_subscription(
        self, input: ActivateSubscriptionInput, plugins: list[Plugin] | None = None
    ) -> ActivateSubscriptionOutput:
        """
        Activates a Subscription to enable billing for a user.

        Args:
            input:
                An instance of `ActivateSubscriptionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ActivateSubscriptionOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, ACTIVATE_SUBSCRIPTION, [], plugins
        )
        return await pipeline(call)

    async def create_domain(
        self, input: CreateDomainInput, plugins: list[Plugin] | None = None
    ) -> CreateDomainOutput:
        """
        Creates a new Domain for managing HealthAgent resources.

        Args:
            input:
                An instance of `CreateDomainInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateDomainOutput`.
        """
        pipeline, call = await self._prepare_call(input, CREATE_DOMAIN, [], plugins)
        return await pipeline(call)

    async def create_subscription(
        self, input: CreateSubscriptionInput, plugins: list[Plugin] | None = None
    ) -> CreateSubscriptionOutput:
        """
        Creates a new Subscription within a Domain for billing and user
        management.

        Args:
            input:
                An instance of `CreateSubscriptionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateSubscriptionOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, CREATE_SUBSCRIPTION, [], plugins
        )
        return await pipeline(call)

    async def deactivate_subscription(
        self, input: DeactivateSubscriptionInput, plugins: list[Plugin] | None = None
    ) -> DeactivateSubscriptionOutput:
        """
        Deactivates a Subscription to stop billing for a user.

        Args:
            input:
                An instance of `DeactivateSubscriptionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeactivateSubscriptionOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, DEACTIVATE_SUBSCRIPTION, [], plugins
        )
        return await pipeline(call)

    async def delete_domain(
        self, input: DeleteDomainInput, plugins: list[Plugin] | None = None
    ) -> DeleteDomainOutput:
        """
        Deletes a Domain and all associated resources.

        Args:
            input:
                An instance of `DeleteDomainInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `DeleteDomainOutput`.
        """
        pipeline, call = await self._prepare_call(input, DELETE_DOMAIN, [], plugins)
        return await pipeline(call)

    async def get_domain(
        self, input: GetDomainInput, plugins: list[Plugin] | None = None
    ) -> GetDomainOutput:
        """
        Retrieves information about a Domain.

        Args:
            input:
                An instance of `GetDomainInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetDomainOutput`.
        """
        pipeline, call = await self._prepare_call(input, GET_DOMAIN, [], plugins)
        return await pipeline(call)

    async def get_medical_scribe_listening_session(
        self,
        input: GetMedicalScribeListeningSessionInput,
        plugins: list[Plugin] | None = None,
    ) -> GetMedicalScribeListeningSessionOutput:
        """
        Retrieves details about an existing Medical Scribe listening session

        Args:
            input:
                An instance of `GetMedicalScribeListeningSessionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetMedicalScribeListeningSessionOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, GET_MEDICAL_SCRIBE_LISTENING_SESSION, [], plugins
        )
        return await pipeline(call)

    async def get_patient_insights_job(
        self, input: GetPatientInsightsJobInput, plugins: list[Plugin] | None = None
    ) -> GetPatientInsightsJobOutput:
        """
        Get details of a started patient insights job.

        Args:
            input:
                An instance of `GetPatientInsightsJobInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetPatientInsightsJobOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, GET_PATIENT_INSIGHTS_JOB, [], plugins
        )
        return await pipeline(call)

    async def get_subscription(
        self, input: GetSubscriptionInput, plugins: list[Plugin] | None = None
    ) -> GetSubscriptionOutput:
        """
        Retrieves information about a Subscription.

        Args:
            input:
                An instance of `GetSubscriptionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetSubscriptionOutput`.
        """
        pipeline, call = await self._prepare_call(input, GET_SUBSCRIPTION, [], plugins)
        return await pipeline(call)

    async def list_domains(
        self, input: ListDomainsInput, plugins: list[Plugin] | None = None
    ) -> ListDomainsOutput:
        """
        Lists Domains for a given account.

        Args:
            input:
                An instance of `ListDomainsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListDomainsOutput`.
        """
        pipeline, call = await self._prepare_call(input, LIST_DOMAINS, [], plugins)
        return await pipeline(call)

    async def list_subscriptions(
        self, input: ListSubscriptionsInput, plugins: list[Plugin] | None = None
    ) -> ListSubscriptionsOutput:
        """
        Lists all Subscriptions within a Domain.

        Args:
            input:
                An instance of `ListSubscriptionsInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListSubscriptionsOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, LIST_SUBSCRIPTIONS, [], plugins
        )
        return await pipeline(call)

    async def list_tags_for_resource(
        self, input: ListTagsForResourceInput, plugins: list[Plugin] | None = None
    ) -> ListTagsForResourceOutput:
        """
        Lists the tags associated with the specified resource

        Args:
            input:
                An instance of `ListTagsForResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ListTagsForResourceOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, LIST_TAGS_FOR_RESOURCE, [], plugins
        )
        return await pipeline(call)

    async def start_medical_scribe_listening_session(
        self,
        input: StartMedicalScribeListeningSessionInput,
        plugins: list[Plugin] | None = None,
    ) -> DuplexEventStream[
        MedicalScribeInputStream,
        MedicalScribeOutputStream,
        StartMedicalScribeListeningSessionOutput,
    ]:
        """
        Starts a new Medical Scribe listening session for real-time audio
        transcription

        Args:
            input:
                An instance of `StartMedicalScribeListeningSessionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            A `DuplexEventStream` for bidirectional streaming.
        """
        pipeline, call = await self._prepare_call(
            input, START_MEDICAL_SCRIBE_LISTENING_SESSION, [], plugins
        )
        return await pipeline.duplex_stream(
            call,
            MedicalScribeInputStream,
            MedicalScribeOutputStream,
            _MedicalScribeOutputStreamDeserializer().deserialize,
        )

    async def start_patient_insights_job(
        self, input: StartPatientInsightsJobInput, plugins: list[Plugin] | None = None
    ) -> StartPatientInsightsJobOutput:
        """
        Starts a new patient insights job.

        Args:
            input:
                An instance of `StartPatientInsightsJobInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `StartPatientInsightsJobOutput`.
        """
        pipeline, call = await self._prepare_call(
            input, START_PATIENT_INSIGHTS_JOB, [], plugins
        )
        return await pipeline(call)

    async def tag_resource(
        self, input: TagResourceInput, plugins: list[Plugin] | None = None
    ) -> TagResourceOutput:
        """
        Associates the specified tags with the specified resource

        Args:
            input:
                An instance of `TagResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `TagResourceOutput`.
        """
        pipeline, call = await self._prepare_call(input, TAG_RESOURCE, [], plugins)
        return await pipeline(call)

    async def untag_resource(
        self, input: UntagResourceInput, plugins: list[Plugin] | None = None
    ) -> UntagResourceOutput:
        """
        Removes the specified tags from the specified resource

        Args:
            input:
                An instance of `UntagResourceInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `UntagResourceOutput`.
        """
        pipeline, call = await self._prepare_call(input, UNTAG_RESOURCE, [], plugins)
        return await pipeline(call)
