# Code generated by smithy-python-codegen DO NOT EDIT.

from types import MappingProxyType

from smithy_core.prelude import INTEGER, STRING
from smithy_core.schemas import Schema
from smithy_core.shapes import ShapeID, ShapeType
from smithy_core.traits import Trait


INPUT_VALIDATION_ERROR = Schema.collection(
    id=ShapeID("com.amazonaws.sagemakerruntimehttp2#InputValidationError"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=400),
    ],
    members={"Message": {"target": STRING}, "ErrorCode": {"target": STRING}},
)

INTERNAL_SERVER_ERROR = Schema.collection(
    id=ShapeID("com.amazonaws.sagemakerruntimehttp2#InternalServerError"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="server"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=500),
    ],
    members={"Message": {"target": STRING}, "ErrorCode": {"target": STRING}},
)

INTERNAL_STREAM_FAILURE = Schema.collection(
    id=ShapeID("com.amazonaws.sagemakerruntimehttp2#InternalStreamFailure"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="server")],
    members={"Message": {"target": STRING}},
)

SENSITIVE_BLOB = Schema(
    id=ShapeID("com.amazonaws.sagemakerruntimehttp2#SensitiveBlob"),
    shape_type=ShapeType.BLOB,
    traits=[Trait.new(id=ShapeID("smithy.api#sensitive"))],
)

REQUEST_PAYLOAD_PART = Schema.collection(
    id=ShapeID("com.amazonaws.sagemakerruntimehttp2#RequestPayloadPart"),
    members={
        "Bytes": {
            "target": SENSITIVE_BLOB,
            "traits": [Trait.new(id=ShapeID("smithy.api#eventPayload"))],
        },
        "DataType": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#eventHeader"))],
        },
        "CompletionState": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#eventHeader"))],
        },
        "P": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#eventHeader"))],
        },
    },
)

REQUEST_STREAM_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.sagemakerruntimehttp2#RequestStreamEvent"),
    shape_type=ShapeType.UNION,
    traits=[Trait.new(id=ShapeID("smithy.api#streaming"))],
    members={"PayloadPart": {"target": REQUEST_PAYLOAD_PART}},
)

INVOKE_ENDPOINT_WITH_BIDIRECTIONAL_STREAM_INPUT = Schema.collection(
    id=ShapeID(
        "com.amazonaws.sagemakerruntimehttp2#InvokeEndpointWithBidirectionalStreamInput"
    ),
    members={
        "EndpointName": {
            "target": STRING,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpLabel")),
            ],
        },
        "Body": {
            "target": REQUEST_STREAM_EVENT,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpPayload")),
            ],
        },
        "TargetVariant": {
            "target": STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="X-Amzn-SageMaker-Target-Variant",
                )
            ],
        },
        "ModelInvocationPath": {
            "target": STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="X-Amzn-SageMaker-Model-Invocation-Path",
                )
            ],
        },
        "ModelQueryString": {
            "target": STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="X-Amzn-SageMaker-Model-Query-String",
                )
            ],
        },
    },
)

MODEL_STREAM_ERROR = Schema.collection(
    id=ShapeID("com.amazonaws.sagemakerruntimehttp2#ModelStreamError"),
    traits=[Trait.new(id=ShapeID("smithy.api#error"), value="client")],
    members={"Message": {"target": STRING}, "ErrorCode": {"target": STRING}},
)

RESPONSE_PAYLOAD_PART = Schema.collection(
    id=ShapeID("com.amazonaws.sagemakerruntimehttp2#ResponsePayloadPart"),
    members={
        "Bytes": {
            "target": SENSITIVE_BLOB,
            "traits": [Trait.new(id=ShapeID("smithy.api#eventPayload"))],
        },
        "DataType": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#eventHeader"))],
        },
        "CompletionState": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#eventHeader"))],
        },
        "P": {
            "target": STRING,
            "traits": [Trait.new(id=ShapeID("smithy.api#eventHeader"))],
        },
    },
)

RESPONSE_STREAM_EVENT = Schema.collection(
    id=ShapeID("com.amazonaws.sagemakerruntimehttp2#ResponseStreamEvent"),
    shape_type=ShapeType.UNION,
    traits=[Trait.new(id=ShapeID("smithy.api#streaming"))],
    members={
        "PayloadPart": {"target": RESPONSE_PAYLOAD_PART},
        "ModelStreamError": {"target": MODEL_STREAM_ERROR},
        "InternalStreamFailure": {"target": INTERNAL_STREAM_FAILURE},
    },
)

INVOKE_ENDPOINT_WITH_BIDIRECTIONAL_STREAM_OUTPUT = Schema.collection(
    id=ShapeID(
        "com.amazonaws.sagemakerruntimehttp2#InvokeEndpointWithBidirectionalStreamOutput"
    ),
    members={
        "Body": {
            "target": RESPONSE_STREAM_EVENT,
            "traits": [
                Trait.new(id=ShapeID("smithy.api#required")),
                Trait.new(id=ShapeID("smithy.api#httpPayload")),
            ],
        },
        "InvokedProductionVariant": {
            "target": STRING,
            "traits": [
                Trait.new(
                    id=ShapeID("smithy.api#httpHeader"),
                    value="X-Amzn-Invoked-Production-Variant",
                )
            ],
        },
    },
)

MODEL_ERROR = Schema.collection(
    id=ShapeID("com.amazonaws.sagemakerruntimehttp2#ModelError"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="client"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=424),
    ],
    members={
        "Message": {"target": STRING},
        "OriginalStatusCode": {"target": INTEGER},
        "OriginalMessage": {"target": STRING},
        "LogStreamArn": {"target": STRING},
        "ErrorCode": {"target": STRING},
    },
)

SERVICE_UNAVAILABLE_ERROR = Schema.collection(
    id=ShapeID("com.amazonaws.sagemakerruntimehttp2#ServiceUnavailableError"),
    traits=[
        Trait.new(id=ShapeID("smithy.api#error"), value="server"),
        Trait.new(id=ShapeID("smithy.api#httpError"), value=503),
    ],
    members={"Message": {"target": STRING}, "ErrorCode": {"target": STRING}},
)

INVOKE_ENDPOINT_WITH_BIDIRECTIONAL_STREAM = Schema(
    id=ShapeID(
        "com.amazonaws.sagemakerruntimehttp2#InvokeEndpointWithBidirectionalStream"
    ),
    shape_type=ShapeType.OPERATION,
    traits=[
        Trait.new(
            id=ShapeID("smithy.api#http"),
            value=MappingProxyType(
                {
                    "method": "POST",
                    "uri": "/endpoints/{EndpointName}/invocations-bidirectional-stream",
                }
            ),
        )
    ],
)

AMAZON_SAGE_MAKER_RUNTIME_HTTP2 = Schema(
    id=ShapeID("com.amazonaws.sagemakerruntimehttp2#AmazonSageMakerRuntimeHttp2"),
    shape_type=ShapeType.SERVICE,
    traits=[
        Trait.new(
            id=ShapeID("aws.auth#sigv4"), value=MappingProxyType({"name": "sagemaker"})
        ),
        Trait.new(
            id=ShapeID("smithy.rules#endpointBdd"),
            value=MappingProxyType(
                {
                    "version": "1.1",
                    "parameters": MappingProxyType(
                        {
                            "UseDualStack": MappingProxyType(
                                {
                                    "builtIn": "AWS::UseDualStack",
                                    "required": True,
                                    "default": False,
                                    "documentation": "When true, use the dual-stack endpoint. If the configured endpoint does not support dual-stack, dispatching the request MAY return an error.",
                                    "type": "boolean",
                                }
                            ),
                            "UseFIPS": MappingProxyType(
                                {
                                    "builtIn": "AWS::UseFIPS",
                                    "required": True,
                                    "default": False,
                                    "documentation": "When true, send this request to the FIPS-compliant regional endpoint. If the configured endpoint does not have a FIPS compliant endpoint, dispatching the request will return an error.",
                                    "type": "boolean",
                                }
                            ),
                            "Endpoint": MappingProxyType(
                                {
                                    "builtIn": "SDK::Endpoint",
                                    "required": False,
                                    "documentation": "Override the endpoint used to send this request",
                                    "type": "string",
                                }
                            ),
                            "Region": MappingProxyType(
                                {
                                    "builtIn": "AWS::Region",
                                    "required": False,
                                    "documentation": "The AWS region used to dispatch the request.",
                                    "type": "string",
                                }
                            ),
                        }
                    ),
                    "conditions": (
                        MappingProxyType(
                            {
                                "fn": "isSet",
                                "argv": (MappingProxyType({"ref": "Endpoint"}),),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "isSet",
                                "argv": (MappingProxyType({"ref": "Region"}),),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "aws.partition",
                                "argv": (MappingProxyType({"ref": "Region"}),),
                                "assign": "PartitionResult",
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "stringEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "name",
                                            ),
                                        }
                                    ),
                                    "aws",
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "stringEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "name",
                                            ),
                                        }
                                    ),
                                    "aws-cn",
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "stringEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "name",
                                            ),
                                        }
                                    ),
                                    "aws-us-gov",
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "stringEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "name",
                                            ),
                                        }
                                    ),
                                    "aws-iso",
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "stringEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "name",
                                            ),
                                        }
                                    ),
                                    "aws-iso-b",
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "stringEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "name",
                                            ),
                                        }
                                    ),
                                    "aws-eusc",
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "stringEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "name",
                                            ),
                                        }
                                    ),
                                    "aws-iso-f",
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (MappingProxyType({"ref": "UseFIPS"}), True),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "supportsFIPS",
                                            ),
                                        }
                                    ),
                                    True,
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (
                                    MappingProxyType({"ref": "UseDualStack"}),
                                    True,
                                ),
                            }
                        ),
                        MappingProxyType(
                            {
                                "fn": "booleanEquals",
                                "argv": (
                                    MappingProxyType(
                                        {
                                            "fn": "getAttr",
                                            "argv": (
                                                MappingProxyType(
                                                    {"ref": "PartitionResult"}
                                                ),
                                                "supportsDualStack",
                                            ),
                                        }
                                    ),
                                    True,
                                ),
                            }
                        ),
                    ),
                    "results": (
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: FIPS and custom endpoint are not supported",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: Dualstack and custom endpoint are not supported",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": MappingProxyType({"ref": "Endpoint"}),
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://runtime.sagemaker.{Region}.{PartitionResult#dnsSuffix}:8443",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://runtime.sagemaker.{Region}.{PartitionResult#dualStackDnsSuffix}:8443",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://runtime-fips.sagemaker.{Region}.{PartitionResult#dnsSuffix}:8443",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://runtime-fips.sagemaker.{Region}.{PartitionResult#dualStackDnsSuffix}:8443",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://runtime.sagemaker-fips.{Region}.{PartitionResult#dualStackDnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "FIPS and DualStack are enabled, but this partition does not support one or both",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://runtime.sagemaker-fips.{Region}.{PartitionResult#dnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "FIPS is enabled but this partition does not support FIPS",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://runtime.sagemaker.{Region}.{PartitionResult#dualStackDnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "DualStack is enabled but this partition does not support DualStack",
                                "type": "error",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "endpoint": MappingProxyType(
                                    {
                                        "url": "https://runtime.sagemaker.{Region}.{PartitionResult#dnsSuffix}",
                                        "properties": MappingProxyType({}),
                                        "headers": MappingProxyType({}),
                                    }
                                ),
                                "type": "endpoint",
                            }
                        ),
                        MappingProxyType(
                            {
                                "conditions": (),
                                "error": "Invalid Configuration: Missing Region",
                                "type": "error",
                            }
                        ),
                    ),
                    "root": 2,
                    "nodeCount": 23,
                    "nodes": "/////wAAAAH/////AAAAAAAAABYAAAADAAAAAQAAAAQF9eEPAAAAAgAAAAUF9eEPAAAAAwAAABMAAAAGAAAABAAAABMAAAAHAAAABQAAABMAAAAIAAAABgAAABMAAAAJAAAABwAAABMAAAAKAAAACAAAABMAAAALAAAACQAAABMAAAAMAAAACgAAAA8AAAANAAAADAAAAA4F9eEOAAAADQX14QwF9eENAAAACwAAABEAAAAQAAAADAX14QkF9eELAAAADAAAABIF9eEKAAAADQX14QgF9eEJAAAACgAAABUAAAAUAAAADAX14QUF9eEEAAAADAX14QcF9eEGAAAACgX14QEAAAAXAAAADAX14QIF9eED",
                }
            ),
        ),
        Trait.new(
            id=ShapeID("aws.api#service"),
            value=MappingProxyType(
                {
                    "sdkId": "SageMaker Runtime HTTP2",
                    "arnNamespace": "sagemaker",
                    "cloudFormationName": "SageMakerRuntime",
                    "endpointPrefix": "runtime.sagemaker",
                }
            ),
        ),
        Trait.new(
            id=ShapeID("aws.protocols#restJson1"),
            value=MappingProxyType({"http": ("h2",), "eventStreamHttp": ("h2",)}),
        ),
    ],
)
